### ISSUE TITLE
Ubuntu Blog IMG tags are mangled when aggregated on planet.ubuntu.com

### ISSUE THREAD

**Issue by ian-weisser** [canonical/ubuntu.com#10245]
Images embedded in Ubuntu Blog posts are not shown on the planet.ubuntu.com aggregator. An HTMl string is shown instead of the image.

Example Ubuntu Blog Post: https://ubuntu.com//blog/winners-of-the-21-10-wallpaper-competition

**Comment by carkod** [comment]
Is this on planet.ubuntu.com? We don't own that project, you should file a bug https://bugs.launchpad.net/planet-ubuntu
