### ISSUE TITLE
Errors downloading font on ubuntu.com

### ISSUE THREAD

**Issue by mtruj013** [canonical/ubuntu.com#10312]
## Summary
These issues pop up on the ubuntu.com landing page, although no styling seems to be broken 

## Screenshot
![Image Pasted at 2021-9-6 14-30](https://user-images.githubusercontent.com/17607612/132228120-7dafdfd5-2524-4d55-a1f4-ec2d94adb852.png)

[If relevant, please include a screenshot.]

## Browser details

[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.]

**Comment by bethcollins92** [comment]
@bartaz or @sowasred2012 do you know what's going on with these warnings?

**Comment by bartaz** [comment]
@bethcollins92 
No, it seems to only happen in Firefox. 
And I also don't see same errors on vanillaframework.io, so not sure - does ubuntu.com use different font files?

**Comment by bethcollins92** [comment]
@bartaz yeh it's weird it's only on firefox. Also, I can't see any different font files on ubuntu.com

**Comment by bartaz** [comment]
@bethcollins92 I guess it would need more investigation to better understand what these errors/warnings mean and what need to be changed to avoid them.

**Comment by petesfrench** [comment]
I don't get the font error on Firefox, but another set of errors mostly relating to the cookie policy:
![image](https://user-images.githubusercontent.com/58276363/148548161-e8b7fb79-865c-4ea5-ac95-343cfb584eae.png)

So not sure if this is still relevant.

**Comment by petesfrench** [comment]
@mtruj013 can you see if you can replicate this?

**Comment by sowasred2012** [comment]
I couldn't see these errors on Firefox, but I checked Chrome and they appeared:
![Screenshot from 2022-01-19 15-11-20](https://user-images.githubusercontent.com/2376968/150158928-e1bf5ee3-0828-46c8-8bac-796b370baa4f.png)

The odd thing is that on subsequent page loads, six errors appear, not 10. I'll look into what the error means.

**Comment by petesfrench** [comment]
We are loading fonts directly in our HTML: https://github.com/canonical/ubuntu.com/blob/main/templates/templates/base.html#L59 as well as in Vanilla https://github.com/canonical/vanilla-framework/blob/main/scss/_base_fontfaces.scss 
It looks like the Vanilla font types are being prioritized and thus the ones we include on u.com are not being used.
One option would be to remove them entirely, or we could just not preload them
