### ISSUE TITLE
Dynamic meta images

### ISSUE THREAD

**Issue by bethcollins92** [canonical/ubuntu.com#10346]
see brief [here](https://docs.google.com/document/d/1G2qGO8dnIaF7SG2f2uLFw4zpfgM8ggkP6jzPlf3tPLo/edit#)
see WIP demo [here](https://github.com/canonical-web-and-design/ubuntu.com/pull/9353)

**Comment by SirSamTumless** [comment]
@bethcollins92 I think I might move this out of this iteration for something a bit more pressing.

**Comment by carkod** [comment]
@anthonydillon is this still relevant?

**Comment by anthonydillon** [comment]
It would be good but will take investigation. Maybe worth spec'ing fully as a project?

**Comment by tbille** [comment]
Still relevant and cool idea.
Closing this issue, we track the work here: https://warthogs.atlassian.net/browse/WD-2178
