### ISSUE TITLE
allow multiple selections in cve status

### ISSUE THREAD

**Issue by setharnold** [canonical/ubuntu.com#10577]
Hello,

Can the `Status` drop-down on the following page be turned into checkboxes or some other mechanism to allow selecting multiple states at once?

In this case I'd like to see a single list of all Needed, Needs Triage, and Ignored CVEs in the 16.04 ESM list. This currently requires three separate page loads and manually merging the three lists.

Thanks

---
*Reported from: https://ubuntu.com/security/cve?q=&package=docker.io&priority=&version=xenial&status=

**Comment by carkod** [comment]
This may need some UX?

**Comment by davegoddard42** [comment]
UX designs here: https://miro.com/app/board/o9J_loZycW4=/?invite_link_id=965509045419

**Comment by setharnold** [comment]
I'm very sorry I didn't return to this sooner, but this solution doesn't quite work.

Consider the case of trying to find all CVEs in 18.04 that are in state `needs-triage`, `needed`, `deferred`, and `ignored`. (This represents CVEs that we know about but haven't released security fixes for, yet.)

The drop-down for the version on the second line actually prevents selecting the same version as the first condition. The user is still forced to perform multiple searches on the page in order to answer the question "what isn't yet fixed on the version of Ubuntu that I'm running?"

I honestly don't know if it makes sense to let the user select different versions for different statuses -- it may, it may not -- but what we have now doesn't answer questions that we get from our customers.

Hopefully this screenshot will save a thousand words :)

Thanks

![unselectable](https://user-images.githubusercontent.com/5447148/142136178-6840d63a-2e02-4ff0-98aa-ff81f73126fc.png)

**Comment by davegoddard42** [comment]
Hi @setharnold - I think what I've proposed does cover the issue - but maybe I'm misunderstanding. I'll set up a call with you to chat through.

**Comment by davegoddard42** [comment]
Chatted to @setharnold who's happy with the UX design work.

**Comment by davegoddard42** [comment]
@cristinadresch I wrongly closed this as I thought it was purely a UX issue. Reopening it so that it can be built

**Comment by britneywwc** [comment]
Hi, we have an on-going task to overhaul CVE pages and it addresses the issue of selecting multiple CVE statuses. Will be closing issue for now as it is implemented in the CVE overhaul project but feel free to reopen this if needed.
You can check out the demo here: https://ubuntu-com-13412.demos.haus/security/cves?q=
