### ISSUE TITLE
Suggestions for /advantage instructions

### ISSUE THREAD

**Issue by orndorffgrant** [canonical/ubuntu.com#10602]
Bringing this issue over to this repo based on https://github.com/canonical/ubuntu-advantage-client/issues/1824 (from @ariannalozano)

### Machines dropdown
Currently, the instructions suggest running `apt upgrade` to ensure ubuntu-advantage-tools is up to date. A more precise way of ensuring this is to run:
```
sudo apt update
sudo apt install ubuntu-advantage-tools
```
That is what we suggest in our discourse documentation https://discourse.ubuntu.com/t/ubuntu-advantage-client/21788

Additionally, (the rest of this issue is quoting @ariannalozano): Something else that I've noticed is that our message is not clear about the UA Client in /advantage, and this is something that commonly trips up new customers. In an effort to make customer more self sufficient, I believe it would be beneficial to have a quick one liner on what the UA client is the "machines" column, once that has been addressed, we could have a 1-liner that provides the commands needed to check the latest version.

#### Example suggested machines dropdown content
Installing the UA client
The UA client is a tool that helps automate the enablement of UA services like ESM, Livepatch, FIPS, and more. It is installed through apt. Make sure to confirm you have the latest Ubuntu Advantage client which is equal to or greater than version 27.
```
$ sudo apt update
$ sudo apt install ubuntu-advantage-tools
$ ua --version
```

### ESM Dropdown
I believe it would be in the best interest of our customers if we provided more context about sudo apt upgrade for specifically ESM.

#### Example suggested ESM dropdown content
Extended Security Maintenance (ESM)
For Ubuntu 14.04 LTS and 16.04 LTS as shown above, ESM will be automatically enabled after attaching the UA client to your account. After ubuntu-advantage-tools is installed and your machine is attached, ESM should be enabled. If ESM is not enabled, you can enable it with the following command:
```
$ sudo ua enable esm-infra
```

With the ESM repository enabled, you may see a number of additional package updates available that were not available previously. Even if your system had indicated that it was up to date before installing the ubuntu-advantage-tools and attaching, make sure to check for new package updates after ESM is enabled using apt upgrade. If you have cron jobs set to install updates, or other unattended upgrades configured, be aware that this will likely result in a number of package updates with the ESM content.

Running apt upgrade will now apply all of package updates available, including the ones in ESM.
```
$ sudo apt upgrade
```
More information: https://ubuntu.com/security/esm

To disable esm:
```
ua disable esm-infra
```

---
*Reported from: https://ubuntu.com/advantage*

**Comment by albertkol** [comment]
@lechsandecki @wgx this has not moved at all for a long time. If we still want to do this, please re-open.
