### ISSUE TITLE
UR Setup ProtoMegaNav test with humans

### ISSUE THREAD

**Issue by cassiocassio** [canonical/ubuntu.com#10639]
- [x] Set dates for interviews
- [x] Start recruiting at https://ubuntu.com/download/desktop/thank- [ ]you ?
- [x] Set number of interviews reasonable ?
- [ ] Recruit spec somewhat ideal
- [ ] Invitation email craft and iterate
- [ ] Decide incentive, make spreadsheet for amazon vouchers?
- [ ] Make calendly meeting round robin dates and times and people and nice encouraging copy
- [ ] Research objectives draft, share, comment
- [ ] Scope of prototypes required to test of objectives MEETING
- [ ] Interview prototcol, discussion guide
- [ ] Metrics to capture during interview agree
- [ ] Metrics can capture after from video
- [ ] Draft simplest tags to support analysis
- [ ] Run trial test - [ ] aim for 30~40 mins for 12 interviews?
- [ ] Dummy tagging, analysis
- [ ] Need 3 days of analysis for this
- [ ] Need 2 days to make a Miro of whaat we've leaned, obvious changes, decisions to make
- [ ] Workshop not a meeting to share, next steps

**Comment by sowasred2012** [comment]
@cassiocassio can this issue be closed?

**Comment by sowasred2012** [comment]
Confirmed with @cassiocassio this was done
