### ISSUE TITLE
/about - accent letters not rendering properly

### ISSUE THREAD

**Issue by anasereijo** [canonical/ubuntu.com#11053]
the accent letters ǒ and ō aren't rendering properly - ǒ seems lighter and ō is bolder?

browser: Chrome Version 96.0.4664.93 (Official Build) (x86_64)
OS: macOS big Sur 11.4

<img width="719" alt="Screenshot 2021-12-15 at 12 10 46" src="https://user-images.githubusercontent.com/36884067/146184426-dd238dca-f741-4f1c-967e-fd6110f4a948.png">

---
*Reported from: https://ubuntu.com/about*

**Comment by fitojb** [comment]
These letters are substituted from a system fallback font. I’m not sure where font bugs go these days, but it’s either [here](https://bugs.launchpad.net/ubuntu-font-family/+bugs?orderby=-id&start=0) or [here](https://github.com/daltonmaag/ubuntu/issues)

(On a slightly related note, a phonetic transcription in the IPA might be better for international users)

**Comment by petesfrench** [comment]
Closing as this appears to have been solved by the variable font upgrade as mentioned above
![image](https://github.com/user-attachments/assets/b9e1e1a3-7f58-439e-8e55-5d967000a8e8)
