### ISSUE TITLE
Update sqlalchemy to 1.4.29

### ISSUE THREAD

**Issue by sowasred2012** [canonical/ubuntu.com#11127]
After merging a large batch of dependency updates (Update all dependencies #11081), including sqlalchemy 1.3.23 => 1.4.29, we ran into a number of issues with the dependency update on sqlalchemy while building the Jenkins job on staging:
- AttributeError: 'BaseFilterQuery' object has no attribute '_mapper_zero when trying to view /security/cve
- We realised we needed to update a secret in k8s to use the new URL format, postgresql:// rather than postgres://

We need to investigate how to solve the first issue, so that we can safely update the version.

(we rolled the version back in https://github.com/canonical-web-and-design/ubuntu.com/pull/11126)

**Comment by carkod** [comment]
No longer required after database removal
