### ISSUE TITLE
[CVE-search] UX investigation

### ISSUE THREAD

**Issue by petesfrench** [canonical/ubuntu.com#11233]
Investigate use cases for the CVE search.
 - Do we need to be able to search individual version-status combinations at one time
 - Is it sufficient to allow only a multi-search (multiple versions to one status and vise-versa)
 - about CVEs search, another thing that I remember reading in some issue, is that they seem to use a lot the https://ubuntu.com/security/cves.json endpoint? so maybe our search doesn't need to be too sophisticated, if they are using the endpoint they can build their own queries. Something to be considered

**Comment by davegoddard42** [comment]
@petesfrench I haven't sorry. It hasn't been added to an iteration, other things have taken precedence sorry.

**Comment by petesfrench** [comment]
@davegoddard42 My mistake, I hadn't seen it had been Ice-boxed!
