### ISSUE TITLE
Discourse sub-nav missing on topic pages

### ISSUE THREAD

**Issue by nottrobin** [canonical/ubuntu.com#11468]
On topic pages like [this one](https://discourse.ubuntu.com/t/pattern-accordion/27604), I see:

![image](https://user-images.githubusercontent.com/519935/162583478-961c5728-d6c5-4076-be5b-8976365fcc49.png)

Pretty sure it should be showing categories in that sub-nav space, more like the homepage:

![image](https://user-images.githubusercontent.com/519935/162583489-80f7022e-360b-4460-9832-6205ed1a1cd2.png)

With the categories etc.

This is using Ubuntu 21.10, and is the same in both Firefox 99.0 Snap (logged in), and Chromium 100.0.4896.75 Snap (logged out).

**Comment by carkod** [comment]
@sowasred2012 how is it going?

**Comment by carkod** [comment]
None of the Discourse topic pages feature a sub navigation? I think this is more of an Discourse feature issue.
