### ISSUE TITLE
certified links to Download are confusing to people

### ISSUE THREAD

**Issue by bladernr** [canonical/ubuntu.com#11581]
Each certificate for a certification points to 

https://ubuntu.com/download/server

That used to be great, but updates at some point now has server as a landing page that has confused some users.

First, it lands to Ubuntu Server VMs... people looking to download Ubuntu Server are probably, IMO, looking for ISO images, not Multipass, they want to install Ubuntu Server on their Servers.

Second, the buttons are not as descriptive as they could be.  For example the one that actually takes you to an ISO download says "Manual server installation".  Even to me, knowing what to expect, that does not say to me "This is where you download an Ubuntu Server ISO Image".  And that is the thing that has tripped up some users... they don't see something that explicitly says "Get the ISO image HERE".

Third, there seems to be no way to directly get to the ISO page.

At least, when I land on 

https://ubuntu.com/download/server

from a certificate, and then click the "Manual server installation" button, I THEN see a page with download buttons for the ISO images for 22.04 and 20.04 plus links to older releases, BUT the URL in the browser remains as 

https://ubuntu.com/download/server

So to resolve this issue, we need one of two things:

1: rename that second button so that it is more explicit that it is where you get the ISOs OR make it the default wiht Multipass as the second.
2: provide us a static url to get to the same frame that has the ISO download information and change the download links on the certificate data to point to that URL instead.

*I'm not sure off the top of my head if currently those links are still provided by us on the back end, or by the front end that you maintain now when the certificate pages are generated.

Here's the thing that is confusing people:
<img width="1023" alt="Screen Shot 2022-05-06 at 10 08 42 AM" src="https://user-images.githubusercontent.com/4295496/167094827-ff4dc99a-0f3c-4a2d-8ad0-3601c0557938.png">

**Comment by pmahnke** [comment]
@bladernr I think https://ubuntu.com/download/server/step2 is a direct link to this, I will also check if we can rename the button.

**Comment by codersquid** [comment]
> *I'm not sure off the top of my head if currently those links are still provided by us on the back end, or by the front end that you maintain now when the certificate pages are generated.

Those links are not provided by the backend.

**Comment by davegoddard42** [comment]
The download server page is quite sensitive politically. I'm looking at doing work here to improve the page generally. Before anything is changed, can you loop me in. Thanks

**Comment by davegoddard42** [comment]
This will be solved by https://github.com/canonical/ubuntu.com/pull/11930

We are going to swap the tabs over, so ubuntu.com/download/server will now land on the server download page, not the multipass page. 

I'm aware of the custom URL (ubuntu.com/download/server/step2) so we've proposed the following structure so if any of those links are used, they will go to the right place:

We will create a new URL - /download/server/multipass that points to Multipass tab (option 2). The URL doesn't need to change when a user clicks the "tab" on the server page.

In addition, we will create two redirects:
**download/server/step1** which sends users to **/download/server/multipass**
**download/server/step2** which sends users to **/download/server**

This will preserve functionality whilst allowing the switch to go ahead.
