### ISSUE TITLE
Contact form modal closes unexpectedly when selecting text

### ISSUE THREAD

**Issue by sowasred2012** [canonical/ubuntu.com#11648]
### What happens
When entering information into an input field in a contact form modal, if you decide to select the text in an input and then release the mouse button over the opaque modal background, the modal closes unexpectedly. Releasing the mouse button while still within the modal doesn't.

### What I expect to happen
The modal should stay open regardless of where the mouse button is released when selecting text within the form.

### Video
You can't see the cursor in this unfortunately, but it's easily recreated:
![Peek 2022-05-26 12-10](https://user-images.githubusercontent.com/2376968/170478074-88378d37-bf50-4bfd-a682-6341c9c1bc72.gif)

**Comment by carkod** [comment]
Maybe we should remove the background close functionality? If implement it should be in Vanilla modal?
