### ISSUE TITLE
[copy update] /aws/pro

### ISSUE THREAD

**Issue by sowasred2012** [canonical/ubuntu.com#11685]
See the release section in the hero section: https://docs.google.com/document/d/1pLRWJZSpE04nYt-yHBtCjxGI7VZsigcP2UJIBmR8i-0/edit

**Comment by petesfrench** [comment]
We are waiting on copy from Malina

**Comment by davegoddard42** [comment]
Still with Mailna. Will chase up again

**Comment by davegoddard42** [comment]
Format has been agreed on and the copy docs have been updated to follow the new design. Waiting on copy consensus from the team. To be updated by Malina.

**Comment by davegoddard42** [comment]
I've written down the context with links to the design in my handover document. It's the final topic in the file.

https://docs.google.com/document/d/1uiJ00ycDhyBP_QOIwSV5Jc21I-h0eZft1dONsIAqOxA/edit#
