### ISSUE TITLE
Update images on tutorial pages

### ISSUE THREAD

**Issue by minkyngkm** [canonical/ubuntu.com#11689]
Some images on tutorial pages seem to be linked from google drive rather than the asset server or discourse.(We've got a few issues saying images are missing or not displaying on tutorial pages - #11679, #11673, #11669) 
According to @evilnick  this can be difficult to track down the original image if the google drive owner leaves the company.

Would there be any way we can scan through all the tutorial pages for these type of images (writing a script or something) and update the images?

**Comment by carkod** [comment]
Maybe something like a linkchecker https://github.com/canonical-web-and-design/ubuntu.com/runs/6769361590?check_suite_focus=true

**Comment by anthonydillon** [comment]
I think a script would be difficult and it will be hard to keep updating them as people add and edit tutorials. I would vote for best effort to keep on top of these as they come in.

**Comment by petesfrench** [comment]
Closing based on Ant's suggestion
