### ISSUE TITLE
Getting 403 when searching "apache kafka" 

### ISSUE THREAD

**Issue by minkyngkm** [canonical/ubuntu.com#11696]
![ezgif com-gif-maker (6)](https://user-images.githubusercontent.com/57550290/172886541-2cac6e20-a49f-4316-9d22-d29ac1c8ea4c.gif)

**Comment by carkod** [comment]
Related https://staging.ubuntu.com/security/cves?q=&package=git

**Comment by anthonydillon** [comment]
Thanks @carkod, leaving this one with you for now

**Comment by sowasred2012** [comment]
@carkod what's the status of the RT? I don't have a login for that URL.

**Comment by carkod** [comment]
> @carkod what's the status of the RT? I don't have a login for that URL.

I updated the link to use the other IS site. It's triaged but it's not being worked on by IS, it has priority normal

**Comment by carkod** [comment]
Seems to be fixed
