### ISSUE TITLE
/engage/unlisted/whatever is 500ing

### ISSUE THREAD

**Issue by carkod** [canonical/ubuntu.com#11729]
## Summary

When you go to https://ubuntu.com/engage/unlisted/seeking-satisfaction-customer-centric-digital-transformation-in-logistics you get a 500, this should return a 404 because the page is not found.

## Screenshot

![random-url](https://user-images.githubusercontent.com/14939793/173881051-13235e7d-026d-48f5-80c7-bbd0ca8c0eca.png)

**Comment by gloriaquintanilla** [comment]
I have the same issue when I use the search functionality and try to download certain [
