### ISSUE TITLE
OpenStack support period is incorrect

### ISSUE THREAD

**Issue by ist199099** [canonical/ubuntu.com#11778]
According to https://wiki.ubuntu.com/OpenStack/CloudArchive#Ubuntu_20.04_LTS, on Ubuntu 20.04 LTS, OpenStack Wallaby and Yoga are supported for 36 months (3 years). However, the release cycle page on ubuntu.com says that these versions are only supported for 18 months.

---
*Reported from: https://ubuntu.com/about/release-cycle

**Comment by tytus-kurek** [comment]
I can see that the release chart at https://ubuntu.com/about/release-cycle#openstack-release-cycle indicates that both OpenStack Wallaby and OpenStack Yoga on Ubuntu 20.04 LTS are supported for 36 months (3 years). I'm not sure where the confusion is coming from.

**Comment by ist199099** [comment]
The confusion is coming from the text: "In turn, OpenStack versions which are shipped on Ubuntu LTS through the Ubuntu Cloud Archive are supported by Canonical for 18 months only."

**Comment by tytus-kurek** [comment]
@ist199099 I see. Changes proposed here:

https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit#

Please review.

**Comment by sowasred2012** [comment]
Closing, the copy updates were accepted and pushed live: https://github.com/canonical/ubuntu.com/pull/11825

**Comment by ist199099** [comment]
There is still an issue: backports of OpenStack LTS versions to the previous Ubuntu LTS release are supported via the Ubuntu Cloud Archive for 36 months without any subscription.
