### ISSUE TITLE
Dead link and typographical error on ubuntu.com/about/packages

### ISSUE THREAD

**Issue by NucciTheBoss** [canonical/ubuntu.com#11786]
## Summary

In the **Charms are packages for cloud software operations** section on ubuntu.com/about/packages, there appears to be a misplaced box at the end of the paragraph and the *Get started making a charm* link takes you to a non-existent Discourse page.

## Process

1. Navigate to https://ubuntu.com/about/packages
2. Scroll down to **Charms are packages for cloud software operations** section (see the misplaced box)
3. Click on *Get started making a charm* hyperlink.

## Current and expected result

Noticed the box and did not expect it to be there. When I clicked *Get started making a charm* link I was taken to an "Oops not found" page rather than being taken to introductory documentation for making charms.

### Misplaced box
![image](https://user-images.githubusercontent.com/40342202/176543593-e3b916e2-694f-4486-8e56-382888fd5077.png)

### Non-existent Discourse page
![image](https://user-images.githubusercontent.com/40342202/176543775-70c11c59-09d1-4527-a3ee-9bf354eb850b.png)

## Browser details

Vivaldi | 5.3.2679.61 (Stable channel) stable (64-bit)
-- | --
Revision | fcd44035934deba382cb933a4c62bd4fa7690078
OS | Linux
JavaScript | V8 10.2.154.10
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.136 Safari/537.36
Command Line | /usr/bin/vivaldi-stable --new-window --enable-crashpad --flag-switches-begin --flag-switches-end --save-page-as-mhtml
Executable Path | /opt/vivaldi/vivaldi
Profile Path | /home/nucci/.config/vivaldi/Default

I also have the uBlock origin extension enabled.

**Comment by carkod** [comment]
@NucciTheBoss Thanks for reporting this. Can you explain what do you mean by "misplaced box"

**Comment by NucciTheBoss** [comment]
Sure thing, I have the box highlighted below:

![misplaced_box_highlighted](https://user-images.githubusercontent.com/40342202/176701623-a9a196ae-c06e-42e2-956a-37e56680d7ff.png)

Looks like a character is supposed to be there after Ubuntu, but my web browser does not seem to recognize it.

**Comment by Lukewh** [comment]
@carkod https://juju.is/docs/sdk/hello-world would be a good link – courtesy of @mcjaeger
