### ISSUE TITLE
typo in a blog

### ISSUE THREAD

**Issue by shahzadhaider1** [canonical/ubuntu.com#11833]
blog link: https://ubuntu.com/blog/openstack-vs-aws
heading of paragraph: Move to hybrid/multi-cloud incrementally
line having typo: Take the following baby steps before first before you overinvest.
Suggestion: Take the following baby steps first before you overinvest.

---
*Reported from: https://ubuntu.com/blog/openstack-vs-aws*

**Comment by shahzadhaider1** [comment]
<img width="705" alt="Screenshot 2022-07-13 at 6 11 50 PM" src="https://user-images.githubusercontent.com/76992801/178743920-bd034bc8-3115-4eb3-83d5-6c680e1c6e76.png">

check the third line

**Comment by anthonydillon** [comment]
@shahzadhaider1 Thank you for taking the time to report this issue to us. I have fixed the typo.
