### ISSUE TITLE
The aria-labelledby attribute must point to IDs of elements in the same document

### ISSUE THREAD

**Issue by Horlix** [canonical/ubuntu.com#11880]
IDs not found include:
- `<input type="checkbox" aria-labelledby="Dell" class="p-checkbox__input js-enable-apply-filters" name="vendor" value="Dell">`
- `<input type="checkbox" aria-labelledby="HP" class="p-checkbox__input js-enable-apply-filters" name="vendor" value="HP">`
- `<input class="p-checkbox__input u-no-margin--top" name="canonicalUpdatesOptIn" aria-labelledby="CanonicalUpdatesOptIn" value="yes" type="checkbox">`

Example URLS
- https://ubuntu.com/certified/desktops?offset=0
- https://ubuntu.com/certified/desktops?release=16.04%20LTS
- https://ubuntu.com/blog/wslconf-the-first-conference-dedicated-to-windows-subsystem-for-linux-goes-virtual

This may need to change to aira-label

**Comment by Horlix** [comment]
Full set of URLs

[The aria-controls attribute must point to IDs of elements in the same document.csv](https://github.com/canonical-web-and-design/ubuntu.com/files/9213367/The.aria-controls.attribute.must.point.to.IDs.of.elements.in.the.same.document.csv)

**Comment by lizzochek** [comment]
Hello @Horlix , thanks for filing an issue, this has been fixed
