### ISSUE TITLE
Several links on a page share the same link text and surrounding context, but go to different destinations

### ISSUE THREAD

**Issue by Horlix** [canonical/ubuntu.com#11881]
Link text: Community

Example URLs
- https://ubuntu.com/
- https://ubuntu.com/16-04
- https://ubuntu.com/16-04/azure

Example:
`<a class="p-navigation__link-anchor" href="#community-content" onfocus="fetchDropdown('/templates/navigation-community-h', 'community-content');">Community</a>`

Full list can be provided in CSV

**Comment by Horlix** [comment]
Full list of URLs

[Several links on a page share the same link text and surrounding context, but go to different destinations.csv](https://github.com/canonical-web-and-design/ubuntu.com/files/9213376/Several.links.on.a.page.share.the.same.link.text.and.surrounding.context.but.go.to.different.destinations.csv)

**Comment by lizzochek** [comment]
Hello @Horlix. As of now the links to the community pages are on the footer only and lead to correct community pages. If you believe this is still incorrect, please reopen the issue and provide more details. Thank you
