### ISSUE TITLE
Link is broken. The src or href is an empty string.

### ISSUE THREAD

**Issue by Horlix** [canonical/ubuntu.com#11906]
Full set of URLs provided.

[Link is broken. The src or href is an empty string.csv](https://github.com/canonical-web-and-design/ubuntu.com/files/9214028/Link.is.broken.The.src.or.href.is.an.empty.string.csv)

**Comment by AshishRaikwar1290** [comment]
assign me this issue

**Comment by immortalcodes** [comment]
Hi, thanks for reporting this, we now have a service running that actually checks for broken links but still it would be really cool to have someone else run a script and try to see if we are covering everything.
Could you please may be do it for the updated code and make a new issue for it.
Thanks for actively participating.
