### ISSUE TITLE
Update github repos for github actions

### ISSUE THREAD

**Issue by minkyngkm** [canonical/ubuntu.com#11919]
## Summary

Some [github actions](https://github.com/canonical/ubuntu.com/actions) are not working. 

![image](https://user-images.githubusercontent.com/57550290/182327101-d528643a-0a46-4ec1-9af0-3c94d3b12a33.png)

## Process

maybe github repos in `/ubuntu.com/.github/workflows` need to be updated?

![image](https://user-images.githubusercontent.com/57550290/182326792-cfabb14f-1a14-4015-a59d-1c636f0c0813.png)

**Comment by carkod** [comment]
where is that `github.repository == 'canonical-web-and-design/ubuntu.com`? or can you go there and fix it?
