### ISSUE TITLE
Centos Logo is wrong on Ubuntu's Homepage

### ISSUE THREAD

**Issue by 13r0ck** [canonical/ubuntu.com#11953]
![website_wrong](https://user-images.githubusercontent.com/58987761/185246503-718fb144-f6b3-4b62-90b3-1f64e67e4352.png)

---
*Reported from: https://ubuntu.com/*

**Comment by sowasred2012** [comment]
For dev: correct logo is here https://assets.ubuntu.com/v1/89451f56-centos.png

**Comment by 13r0ck** [comment]
@sowasred2012 that link also seems to have the same issue
