### ISSUE TITLE
Homepage features the same campaign link from 2019 below the takeover

### ISSUE THREAD

**Issue by fitojb** [canonical/ubuntu.com#11955]
![image](https://user-images.githubusercontent.com/554953/185614804-16fb5cf8-470b-4b33-b183-dcf136e73e7c.png)

This post is from October 2021. I assume the event is over now?

**Comment by mtruj013** [comment]
Thanks @fitojb! For devs, relevant file is here https://github.com/canonical/ubuntu.com/search?q=cloud+expo
