### ISSUE TITLE
impish server downloads still offered

### ISSUE THREAD

**Issue by guiverc** [canonical/ubuntu.com#11959]
https://ubuntu.com/download/server still offers *impish* or 21.10 download as an option (via torrent).

Maybe this should be removed....  (support question had me notice it)

---
*Reported from: https://ubuntu.com/download/server*

**Comment by carkod** [comment]
Hi @guiverc thanks for reporting this. Why do you think this should be removed? Isn't it better to have an alternative version available?

**Comment by sowasred2012** [comment]
Closing, the server page only shows 22.04 and 22.10 now.
