### ISSUE TITLE
MegaMenu InfoArchitecture refinement

### ISSUE THREAD

**Issue by cassiocassio** [canonical/ubuntu.com#11969]
# Mostly IA Things to improve in the MegaNav whilst building

## Visual clues to start on the left

- [x] lyubo tries dark grey panel - [ ] get visual OK, UX feedback  from some eyeballs

## Humanise and lighten e.g. more colour, iconography

- [x] all the icons are now orange blocks? 
- [x] not going to go well, probably abandon

## Get Ubuntu Grouping

- [ ] logic of IoR etc, all a bit tangled
- [ ] **revisit with Ollie and other PdMs**

## Big Green button

- [x] New alignment in situ OK
- [ ] **Identify all the places we have the buttons**

## Placement and Naming of /Advantage

- [ ] Surely has changed with /Pro?
- [ ] **Check with Lech** and get feedback for wording before and after launch of /Pro.
- [ ] Possibly have to build /Pro version waiting in the wings ready to go, if we're not sure which will launch first?

## PRODUCTS 
- [ ] **Reorder and simplify the categories**
- [ ] Fewer choices, by 2 or 3
- [ ] **Get all the PdMs to agree**
- [ ] **Get Lech's help on that agreement**
- [ ] Easier fix - [ ] break into logical groups like telephone numbers

## Products 2
- [ ] **default top option in all cases** confirm that PdMs are happy.
- [ ] Central area revisit layout as nice to have

**Comment by sowasred2012** [comment]
@cassiocassio is this what you're working on now or can we close this one?
