### ISSUE TITLE
Misleading info on tutorials/create-a-usb-stick-on-macos

### ISSUE THREAD

**Issue by tauchris** [canonical/ubuntu.com#11984]
Page "2-requirements" says:

You will need:

A 2GB or larger USB stick/flash drive

But all current versions of Ubuntu desktop come in ISO files that are larger than 2GB.  I had to download a very old LTS release (16.04.7) to find an ISO that would fit on my 2GB USB drive.

Page should really say: "A **4GB** or larger USB stick/flash drive" as the first requirement.

**Comment by carkod** [comment]
Hi @tauchris thanks for reporting this. But the right place for this discussion is in [Discourse](https://discourse.ubuntu.com/t/create-a-bootable-usb-stick-on-macos/14016), please head over and take a look at the comments, and if it doesn't solve your issue, please post your questions there. Thanks!
