### ISSUE TITLE
kernel lifecycle image needs refreshing

### ISSUE THREAD

**Issue by setharnold** [canonical/ubuntu.com#11987]
Hello, the kernel versions image, and probably text, need refreshing on this page:

---
*Reported from: https://ubuntu.com/kernel/lifecycle*

Thanks

**Comment by carkod** [comment]
Hi @setharnold can you make the suggestions required for the refresh in the [copy doc](https://docs.google.com/document/d/1d01SFs7c56ge2o92g6Rwr3SjG8rtxm3jNwIyL1N8mQg/edit#heading=h.929qtgja1pr8)?

**Comment by setharnold** [comment]
Unfortunately I cannot, I came to this page to learn the details myself! :)

Thanks

**Comment by anthonydillon** [comment]
Reached out to Brett Grandbois for help to review this content.

**Comment by anthonydillon** [comment]
@EdoardoBarbieriCanonical could you help us with request?

**Comment by EdoardoBarbieriCanonical** [comment]
Hi Ijlal,

Are you the best person to look into this? If so, Here
<https://docs.google.com/document/d/1d01SFs7c56ge2o92g6Rwr3SjG8rtxm3jNwIyL1N8mQg/edit#heading=h.929qtgja1pr8>
is
the copy doc.

Best,
Edoardo

**Comment by anthonydillon** [comment]
@tbille as someone working with Kernel can I ask you to work with them on updating the charts here?

**Comment by setharnold** [comment]
Hello, a co-worker was asking about 22.04 LTS missing from this page earlier today. It'd be nice to make sure this is still moving along. :)

Thanks

**Comment by EdoardoBarbieriCanonical** [comment]
It is moving along. You can check the progress in the comments of this copydoc page: https://docs.google.com/document/d/1d01SFs7c56ge2o92g6Rwr3SjG8rtxm3jNwIyL1N8mQg/edit# and in this Jira ticket: https://warthogs.atlassian.net/browse/WD-2248

**Comment by EdoardoBarbieriCanonical** [comment]
This is now live at https://ubuntu.com/kernel/lifecycle


Please check https://github.com/canonical/ubuntu.com/pull/12858 and https://warthogs.atlassian.net/browse/WD-2248 for further details

**Comment by mtruj013** [comment]
As per Edoardo's comment above looks like this has been addressed, closing
