### ISSUE TITLE
Blog links shouldn't check hashed stylesheets

### ISSUE THREAD

**Issue by carkod** [canonical/ubuntu.com#11994]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

[Linkchecker](https://github.com/canonical/ubuntu.com/runs/8151368403?check_suite_focus=true) (and probably some others) shouldn't be checking hashed stylesheets.

## Solution

Maybe add some condition to check ending.

**Comment by anthonydillon** [comment]
@carkod I don't understand. The only error in the link is the styles.css which exists so not sure why that is erroring with 404.

**Comment by carkod** [comment]
> @carkod I don't understand. The only error in the link is the styles.css which exists so not sure why that is erroring with 404.

What I mean is that, why is linkchecker checking stylesheets? Is that intended? Because stylesheets like ` https://ubuntu.com/static/css/styles.css?v=3df9d45` the `3df9d45` would constantly change, therefore, of course the previous stylesheet would 404?

**Comment by carkod** [comment]
> The hash is just to cache bust to the latest version in the browser. It doesn't need to exist to load the styles.css. Ignoring styles would only stop notifying us when it was not present.

Ok I see, so we do want to be notified when it is not present. I thought it was just to check links, not stylesheets or other types of assets like images.

**Comment by anthonydillon** [comment]
Your right, but it would be over-engineering to have a linkcheckers for assets and one for links. Might as well catch them in a single run.
