### ISSUE TITLE
Cert problem on your releases website.

### ISSUE THREAD

**Issue by alexkingnz** [canonical/ubuntu.com#12007]
You have a certificate problem:

https://duckduckgo.com/?q=release+notes+ubuntu+22.04+server&t=ffab&ia=web
Top hit:

https://www.releases.ubuntu.com/22.04/

That site shows a browser warning: 

"Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for www.releases.ubuntu.com. The certificate is only valid for releases.ubuntu.com."

---
*Reported from: https://ubuntu.com/contact-us*

**Comment by sowasred2012** [comment]
@alexkingnz thanks for flagging this, we're investigating it now.

**Comment by sowasred2012** [comment]
@alexkingnz this issue is now resolved.
