### ISSUE TITLE
Switches to enable FIPS and others are misleading

### ISSUE THREAD

**Issue by panlinux** [canonical/ubuntu.com#12019]
I'm looking at my subscriptions, and I wanted to use FIPS. I see a switch, which is disabled. I try to enable it, but when clicking on save the site says "something went wrong. Please try again later".

Asking for support, they tell me that those switches only control what is auto-enabled when attaching a computer, not what is *available* to that computer.

I think this information is missing from the page. The way it is, it feels like I have to flip those switches to select what I want to have enabled in my account, when in fact the switches control what is *auto-enabled* after a system is attached.

---
*Reported from: https://ubuntu.com/advantage*

**Comment by wgx** [comment]
@panlinux Thanks for this feedback. The UI shows this message:

![image](https://user-images.githubusercontent.com/930099/189857930-2029cb6e-7057-40fe-aa02-64833df294ad.png)

Which is designed to convey that meaning. I'll add it to a list of copy to review to try to make it clearer. 

FIPS can only be enabled if Livepatch is first disabled, the UI tooltips mention this.
