### ISSUE TITLE
wrong link

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/ubuntu.com#12015]
The link should not point to the google doc in chapter `Adding Juju topology to metrics`

---
*Reported from: https://ubuntu.com/blog/model-driven-observability-part-2-juju-topology-metrics*

**Comment by mtruj013** [comment]
Thanks for flagging @beliaev-maksim! I've left a comment on the marketing channel for clarification on what the correct link is supposed to be. Comment [here](https://chat.canonical.com/canonical/pl/z7yzpc3hzffymp7ethfxih8fno).

**Comment by mtruj013** [comment]
Fixed, closing
