### ISSUE TITLE
minor doc issue

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/ubuntu.com#12016]
point number 3 is empty and should be removed

![20220909_12-43-09](https://user-images.githubusercontent.com/51964909/189332883-56bff369-0441-4d76-88df-5415c3590805.png)

---

*Reported from: https://ubuntu.com/blog/model-driven-observability-part-3-taming-alert-storms*

**Comment by sowasred2012** [comment]
@beliaev-maksim thanks for flagging this - updated!
