### ISSUE TITLE
Update Indico US plugin banner

### ISSUE THREAD

**Issue by petesfrench** [canonical/ubuntu.com#12024]

**Comment by spencerbygraves** [comment]
This is the new design approved by Mauro.

![image](https://user-images.githubusercontent.com/9105999/189924535-85bd4217-dd96-4b59-8eea-36d9e1f022d5.png)

**Comment by spencerbygraves** [comment]
@petesfrench could you try this for the illustration please, let me know if it doesn't work. Thanks.

https://assets.ubuntu.com/v1/88af8658-ubuntu+summit-illustration.svg
