### ISSUE TITLE
Free personal token missing "Features" tab

### ISSUE THREAD

**Issue by panlinux** [canonical/ubuntu.com#12020]
When the personal token subscription is selected, there is only a "Documentation" tab and it shows a sudo command to attach a machine:
```
To attach a machine: sudo ua attach C......
```
But when another subscription is selected, a new tab called "Features" becomes available, next to "Documentation", and is the default one shown.

I think the free personal token should also have a "Features" tab which documents what is available via that token.

---
*Reported from: https://ubuntu.com/advantage*

**Comment by sowasred2012** [comment]
@panlinux thanks for raising this, looping in @wgx and @jpmartinspt for their input

**Comment by wgx** [comment]
Hi @panlinux I'm pretty sure it's because we don't allow those features to be configured over the web *for personal tokens* - but you can still change those settings on the command line.

@jpmartinspt Can you add anything to this?

**Comment by jpmartinspt** [comment]
@panlinux we changed the documentation tab to show documentation links for every feature that free accounts are entitled to.

**Comment by carkod** [comment]
Issue seem to be resolved. Feel free to reopen
