### ISSUE TITLE
Ubuntu Core docs: Update to add expandable navigation

### ISSUE THREAD

**Issue by degville** [canonical/ubuntu.com#12026]
Can we update https://ubuntu.com/core/docs to work with the latest expandable navigation, as currently used on juju.is.

Thank you!

Graham
---
*Reported from: https://ubuntu.com/core/docs*

**Comment by SaidMarar** [comment]
@degville 
We can use side navigation as a solution like we did here #10852.
For expandable navigation, i think it is not implemented yet [#4122](https://github.com/canonical/vanilla-framework/issues/4122)

**Comment by degville** [comment]
@SaidMarar
Thanks for getting back to me. I think the expandable navigation work has recently been completed and applied to our juju.is docs and, more recently, on microk8s.io (https://github.com/canonical/microk8s.io/pull/554).

The side navigation you linked to does look good too though.

**Comment by SaidMarar** [comment]
@degville Cool ! working on it :)
