### ISSUE TITLE
Investigate how reliable geo-ip location is for country dial-codes

### ISSUE THREAD

**Issue by petesfrench** [canonical/ubuntu.com#12046]
Currently our forms on U.com are using the [intl-tel-input](https://github.com/jackocnr/intl-tel-input) package to select the country-code when inputting a phone number. One feature of this plugin is to look up the users IP and preset the country-code field appropriately. If it is reliable enough we could implement it but it needs some investigation.

**Comment by petesfrench** [comment]
There is a PR that implements geo-location here: https://github.com/canonical/ubuntu.com/pull/12298/files#diff-e5d76e33e89be8d4c395191a332c515286f347e6c5087d0c4dd2f9391e9169edR1385

**Comment by carkod** [comment]
Looks like it's complete? Closing
