### ISSUE TITLE
Avoid complex and large tables.

### ISSUE THREAD

**Issue by Horlix** [canonical/ubuntu.com#12054]
It is advised to not have complex and large tables and to avoid merged cells. On https://ubuntu.com/security/cves there is a complex pattern with extremely large table.

We would advise:

- Breaking each issue in to a table
- Ensure table headings are set
- Allow for a scrolling TH so users can keep a record of the cells
- Ensure table is responsive
- User headings per issue

We have produced a number of patterns to be reviewed.

**Comment by carkod** [comment]
@juanruitina  if you are working on CVEs at some point, could you take a look at how we can improve this?

**Comment by juanruitina** [comment]
Absolutely, we are evaluating accessibility issues as well.

**Comment by sowasred2012** [comment]
These are the patterns proposed by HeX: https://canonical.hexdev.uk/security/cves.html
