### ISSUE TITLE
The logos across the HPC page have different font sizes and weights

### ISSUE THREAD

**Issue by anthonydillon** [canonical/ubuntu.com#12051]
The logos used across the page are different sizes and so the text is all over the place. Please revisit this page from a design stand point.

![image](https://user-images.githubusercontent.com/1413534/191926029-a3e45819-0f9b-4148-b84e-fa1862f1f0f0.png)

---
*Reported from: https://ubuntu.com/hpc*

**Comment by mtruj013** [comment]
The fix for this is live, closing
