### ISSUE TITLE
Keyboard enter on fields

### ISSUE THREAD

**Issue by Horlix** [canonical/ubuntu.com#12055]
When a keyboard user selects the enter key on any of the files on the table the form is submitted (correct behaviour) but when the user is selecting enter on the Status field a new line is created. If this is repeated on the new row the status field will then remove a row.

https://ubuntu.com/security/cves

Expected behaviour would be to add or review a row when the correct buttons are selected.

**Comment by juanruitina** [comment]
We have simplified the search so we use filters instead of the previous dropdowns, so this is not a problem anymore.
