### ISSUE TITLE
Review UX on /hpc

### ISSUE THREAD

**Issue by marinacastejon** [canonical/ubuntu.com#12080]
This [page](https://ubuntu.com/hpc) needs a UX review and probably a redesign. 
The visual part to harmonise the logos has been tackled in this other [issue](https://github.com/canonical/ubuntu.com/pull/12077), so please ignore that part. 

Gloria Quintanilla (Head of Content Strategy), pointed out that she specifically advised against have all those repeated links "Get in touch to learn more". 
The PM Jon Thor
Message for the UX designer: feel free to contact them to get more context. 

Please estimate this issue once you've understood what needs to be updated.

**Comment by elioqoshi** [comment]
Copydoc here:
https://docs.google.com/document/d/1d4E1IA2mEu72q277sihNSkl7QRKsU1ezwA3jVgJ0TCE/edit#

Working on this now

**Comment by elioqoshi** [comment]
Mocking up preview here: https://www.figma.com/proto/NgiuI3rQmyLBljKHyJrZXK/HPC?page-id=1%3A2544&node-id=4%3A206&viewport=413%2C750%2C0.26&scaling=min-zoom

**Comment by mtruj013** [comment]
Hi @elioqoshi! Could you assign the pdm please?

**Comment by elioqoshi** [comment]
That's @JonThorK but I can't assign him.

Jon, can you confirm if the design is good to go for build?

**Comment by JonThorK** [comment]
It's good to go, thank you Elio and team.
