### ISSUE TITLE
sftp-server libary not proppery linkt

### ISSUE THREAD

**Issue by Foleor81** [canonical/ubuntu.com#12144]
Hello,

Is use Ubuntu 22.10 (beta)

When i want send a directory over the network with the the following command. 
 
scp -r /media/roelof/One\ Touch/Muziek/Deep\ House/ root@192.168.2.4:/media/Muziek
root@192.168.2.4 password: #######

I get the following error

bash: line 1: /usr/lib/sftp-server: No such file or directory
scp: Connection closed. 

The propper location off the sftp-server libary is 
/snap/core20/1623/usr/lib/sftp-server

Greetingz 

*Reported from: https://ubuntu.com/community*

**Comment by carkod** [comment]
Hi @Foleor81, you may have better luck asking the question in https://bugs.launchpad.net/ubuntu or stackoverflow. This is the repo for the ubuntu.com website.
