### ISSUE TITLE
Bug in active machine counter

### ISSUE THREAD

**Issue by hirechbaghdad** [canonical/ubuntu.com#12151]
I enabled Ubuntu Pro subscription on my surface book 1.
There was an error in connectivity, so i switch back to live patch then restarted the computer and tried again, it gave me the same error again, but whenever i go to the Ubuntu Pro Dashboard, the counter is now 2 instead of 0 which means that the activation process uses a counter segment rather than a checking API

In order to fix it, you will need to rebuild the Pro command line tool to use Check_Value_process instead of Counter_Trigger

---
*Reported from: https://ubuntu.com/pro*

**Comment by jpmartinspt** [comment]
@hirechbaghdad if you think this is still an issue I would suggest raising in the [pro client repo](https://github.com/canonical/ubuntu-pro-client).
