### ISSUE TITLE
[22.10 launch] /download/server

### ISSUE THREAD

**Issue by minkyngkm** [canonical/ubuntu.com#12163]
Brief: https://docs.google.com/document/d/11dBtq73CSqcnUH_6ki8nwMQipXFNkgEY_Du0nVb15Zk/edit
copy doc: https://docs.google.com/document/d/1Qob4Ni_y1ffIdSWqaw2xH0dxiHZQmkRGP5nuoBhIfyM/edit

Also please update /server according to
copy doc: https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4/edit

**Comment by carkod** [comment]
@minkyngkm can you also do the /server changes? I put them together because they are not a lot
