### ISSUE TITLE
[22.10 launch] download-content metanav update

### ISSUE THREAD

**Issue by carkod** [canonical/ubuntu.com#12171]
download-content metanav - replace “22.04 LTS” button with “Get Ubuntu Desktop” leading to /download/desktop

![image](https://user-images.githubusercontent.com/14939793/195561673-c555dbfa-12ef-42ba-adf4-8e3c9413d941.png)

Use the launch 22-10-release branch

**Comment by minkyngkm** [comment]
@carkod isn't this automatically updated once it's released?
