### ISSUE TITLE
Possible typo on Ubuntu 14 ESM page (2022 vs 2024)

### ISSUE THREAD

**Issue by droisman** [canonical/ubuntu.com#12206]
Hi,

The page https://ubuntu.com/blog/ubuntu-14-04-esm-support says "April 2022" while multiple sources (e.g. https://ubuntu.com/about/release-cycle) show "April 2024."

I suspect a typo on the first page. Please confirm and correct? Thank you.

---
*Reported from: https://ubuntu.com/blog/ubuntu-14-04-esm-support*

**Comment by mtruj013** [comment]
Hi @lechsandecki, could you confirm the correct date for this please? Thanks!

**Comment by lechsandecki** [comment]
it's always for 10 years, so for 14.04 it should be April 2024, please

**Comment by carkod** [comment]
Fixed https://admin.insights.ubuntu.com/2019/05/07/ubuntu-14-04-esm-support/ it might take a bit of time to update the live page, as it is cached
