### ISSUE TITLE
Update typo on /kubernetes/charmed-k8s page

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/ubuntu.com#12202]
## Summary

Potential typo under "Kubernetes on OpenStack" heading

## Process

1. Navigate to https://ubuntu.com/kubernetes/charmed-k8s
2. Scroll down to "Kubernetes on OpenStack" heading
3. Go to first bullet point

## Current and expected result

Current result:
> A single platform for containerised and workloads

Expected result? (unsure):
> A single platform for containerised workloads

## Screenshot

![typo](https://user-images.githubusercontent.com/115640263/196532693-93ba0ad7-39dc-463f-b56c-fb52b3cc54e1.png)

**Comment by petesfrench** [comment]
Hi, good catch, that's definitely not right. Thanks for reporting.
