### ISSUE TITLE
Verify your download link isn't working

### ISSUE THREAD

**Issue by alete89** [canonical/ubuntu.com#12218]
The link simply does nothing

![image](https://user-images.githubusercontent.com/4999277/197244242-6dfec0ff-f6d4-40aa-9d47-86e5317d6180.png)

---
*Reported from: https://ubuntu.com/download/desktop/thank-you?version=22.04.1

**Comment by anthonydillon** [comment]
@alete89 thank you very much for taking the time to report this issue. Confirmed and set high priority in this issue.

**Comment by sowasred2012** [comment]
@alete89 thanks for reporting this - the issue is resolved, and the fix is now live.
