### ISSUE TITLE
lag and flicker

### ISSUE THREAD

**Issue by samohik** [canonical/ubuntu.com#12234]
[Screencast from 2022-10-26 23-11-17.webm](https://user-images.githubusercontent.com/91695502/198127887-29bd91e0-284e-4322-9ef6-aecca958558e.webm)
![Screenshot from 2022-10-26 23-16-27](https://user-images.githubusercontent.com/91695502/198128167-278b297d-0c20-43ac-aaef-5b61d8cb92b8.png)
![Screenshot from 2022-10-26 23-15-52](https://user-images.githubusercontent.com/91695502/198128172-f8128eab-c7d3-40bb-866d-8e2c59b758c1.png)

---
*Reported from: https://ubuntu.com/support*

**Comment by petesfrench** [comment]
Hi @samohik, thank you for reporting this issue. Can you please file a issue with Ubuntu distro? https://help.ubuntu.com/community/ReportingBugs  This is the repo for the website ubuntu.com

**Comment by samohik** [comment]
[Screencast from 2022-10-26 23-11-17.webm](https://user-images.githubusercontent.com/91695502/198127887-29bd91e0-284e-4322-9ef6-aecca958558e.webm)
I have visual distortions of the folders when I resize them, this effect is observed only on wayland with nvidia drivers under x11, there is no such visual bug
