### ISSUE TITLE
outdated ubuntu pro client information adds complexity

### ISSUE THREAD

**Issue by setharnold** [canonical/ubuntu.com#12256]
Hello, the ubuntu pro beta page includes some information about the ubuntu pro client; it's a complicated section, and now that the date is after `October 9th, 2022` we should replace the entire section with:

`sudo apt update && sudo apt upgrade && sudo apt install ubuntu-advantage-tools`

There's a huge amount of unnecessary information on the page: it's got a lot of 'noise' showing how to tell what's available, what was installed, etc etc, but the truth is that there's a very simple process to get ubuntu pro, and I think we should make it look very simple up front:

```
Visit https://ubuntu.com/pro and create a token
sudo apt update
sudo apt upgrade
sudo apt install ubuntu-advantage-tools
sudo pro attach <token>
sudo pro enable esm-apps --beta
sudo apt update
sudo apt upgrade
```

Perhaps something needs some massaging but something like this that can be pasted, all visible on one browser screen.

Once this is given, all the extra details can follow.

Thanks

---
*Reported from: https://ubuntu.com/pro/beta*

**Comment by jpmartinspt** [comment]
This page has been revamped has part of the Pro release. Feel free to re-open if you think the issue is still there.

**Comment by setharnold** [comment]
Hello @jpmartinspt I think this page is still far too complicated:

> If you run a previous version of the client, you have two options:
>    You could wait for the pro client update, which is now released and phased to get to all Ubuntu machines, or [..]

This text hasn't been relevant for six weeks. The `pro --version` command isn't wrong, it will give an error message if the program isn't installed or the user path is wrong, etc. but we should probably just assume that it's all fine. It probably is, unless the user intentionally uninstalled the program.

Step two is perhaps *interesting* but it's also complex and not actually a step to getting Ubuntu Pro set up. Maybe it belongs in an annex?

Step three is the first thing that's actually specific to this task.

Steps four and five are great. (There's a `$ $` in one of them, no big deal.)

Step six is dangerous. Users who do not already know what FIPS or DISA STIG configurations are should not be lead-by-the-hand to install them. Feel free to say that they are available -- afterall, we need to advertise :) -- but putting these commands in a code block is probably going to encourage someone somewhere to run commands that they shouldn't. The recourse we tell people is to *reinstall*. (It can be fixed by hand, but if someone is asking us how, they probably don't have the technical skills to do it themselves.)

Thanks
