### ISSUE TITLE
"Find out more about our retail partners" link goes to a 404 page on /desktop/developers

### ISSUE THREAD

**Issue by minkyngkm** [canonical/ubuntu.com#12289]
## Summary

"Find out more about our retail partners" link goes to a 404 page on /desktop/developers

## Process

1. Go to https://ubuntu.com/desktop/developers 
2. Scroll down and click "Find out more about our retail partners" 

## Screenshot

![image](https://user-images.githubusercontent.com/57550290/202559338-02b20214-8738-4ee7-b525-853d41f73fe0.png)

**Comment by petesfrench** [comment]
I requested a new link in the [copydoc](https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit)

**Comment by sowasred2012** [comment]
Agreed in standup to update the link to canonical.com/partners/desktop
