### ISSUE TITLE
remove "Charmed Office Hours" from /model-driven-operations

### ISSUE THREAD

**Issue by minkyngkm** [canonical/ubuntu.com#12290]
https://docs.google.com/document/d/1G4sSrM-FQIL2c1Uj8PvW6oGUKcJ9HAK5TwnKhFa4sOY/edit#

**Comment by petesfrench** [comment]
We have a greed to remove the sentence about 'Charmed office hours' until we have a working link

**Comment by sowasred2012** [comment]
@petesfrench can this not be assigned out using the tool?

**Comment by petesfrench** [comment]
@jkfran Would you be able to work on this please?

**Comment by jkfran** [comment]
@petesfrench sure
