### ISSUE TITLE
[copy update] /iot/intel-iot

### ISSUE THREAD

**Issue by petesfrench** [canonical/ubuntu.com#12291]
https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit#heading=h.c3t8qaqgiw9b

**Comment by sowasred2012** [comment]
@petesfrench can this not be assigned out using the tool?

**Comment by petesfrench** [comment]
@sowasred2012 Yes, could you take a look please as the script is not working for me

**Comment by petesfrench** [comment]
@goulinkh Could you take a look at this please
