### ISSUE TITLE
UBUNTU PRO IS LOUD

### ISSUE THREAD

**Issue by xnox** [canonical/ubuntu.com#12327]
UBUNTU PRO

And nothing else on the first screen. Are you sure that Ubuntu PRO font size is correct?

![image](https://user-images.githubusercontent.com/19779/204588429-c54858cf-6027-4229-b413-2fde6e564c62.png)

Also in comparison logos are tiny and impossible to understand what they are. I cannot recognize them.

![image](https://user-images.githubusercontent.com/19779/204588549-056a79d3-5260-4f2c-8d04-ac6e5589cbbe.png)

---
*Reported from: https://ubuntu.com/pro*

**Comment by sowasred2012** [comment]
Hi @xnox - thanks for raising your concerns. I've passed the feedback along, but this is the intended design and it's unlikely to change in the immediate future.
