### ISSUE TITLE
Page should be removed for it not to be listed

### ISSUE THREAD

**Issue by campbieil** [canonical/ubuntu.com#12328]
Can we please remove this page?

---
*Reported from: https://ubuntu.com/engage/at-t-azure-webinar*

**Comment by sowasred2012** [comment]
Closing, this page was removed.

**Comment by sowasred2012** [comment]
On second thoughts, reopening - @anthonydillon do you have access to Google's search console, so we can remove this page from their search results entirely? I'd do it, but don't have the access.
