### ISSUE TITLE
Page refers to Ubuntu Advantage throughout

### ISSUE THREAD

**Issue by alysonrose88** [canonical/ubuntu.com#12330]
Hi team,

I've just noticed that this webpage refers to Ubuntu Advantage throughout and thus needs updating to refer to Ubuntu Pro.

Best
Aly

---
*Reported from: https://ubuntu.com/security/esm*

**Comment by anthonydillon** [comment]
Here are a few other places:
- https://ubuntu.com/legal/ubuntu-advantage
- https://ubuntu.com/support
- https://ubuntu.com/pricing (page description)
- https://ubuntu.com/server/docs/install/subscription

**Comment by petesfrench** [comment]
@anthonydillon Do all instances of Ubuntu Advantage need to be replaced with Ubuntu Pro on u.com?

**Comment by mrgnr** [comment]
@petesfrench https://ubuntu.com/support there is still one here, the others have been fixed

**Comment by britneywwc** [comment]
I believe all the "Ubuntu Advantage" page references from this ticket have been changed to "Ubuntu Pro". Closing this ticket as resolved. If there are anymore references, please feel free to open another ticket. Thank you!
