### ISSUE TITLE
dead link to ubuntu in WSL tutorial

### ISSUE THREAD

**Issue by setharnold** [canonical/ubuntu.com#12355]
Hello, one of our WSL tutorials has a dead link to Ubuntu in it:

https://www.microsoft.com/en-us/p/ubuntu/9pdxgncfsczv?rtc=1&activetab=pivot:overviewtab  --> 
https://www.microsoft.com/library/errorpages/smarterror.aspx?correlationId=m7KGaHj0qkqMpyCB.0.0.2

The tutorial where I found it:

https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-11-with-gui-support#3-download-ubuntu

Thanks

**Comment by anthonydillon** [comment]
@setharnold that link redirects to https://apps.microsoft.com/store/detail/ubuntu/9PDXGNCFSCZV?hl=en-us&gl=us which works for me? Do you still see the error?

**Comment by setharnold** [comment]
Thanks for checking; it works now!
