### ISSUE TITLE
ssh Service Name Changed

### ISSUE THREAD

**Issue by russ-lewis** [canonical/ubuntu.com#12385]
The documentation says that, to restart the sshd server, use "sshd.service".  It appears that the correct service is now named "ssh.service" - at least, that's what worked for me.  (Sorry that I don't know which file to update, or I'd just submit the pull request myself.)

---
*Reported from: https://ubuntu.com/server/docs/service-openssh*

**Comment by petesfrench** [comment]
Thank you for flagging this issue, we will get to it asap.

For whoever works on this, here is the relevant discourse tutorial: https://discourse.ubuntu.com/t/service-openssh/11896

**Comment by petesfrench** [comment]
@evilnick Do you have any ideas about this? or who would be best to ask?

**Comment by evilnick** [comment]
server docs are generated from discourse - I think this is the current page for that topic - https://ubuntu.com/server/docs/service-openssh . If the issue still persists it would be useful to open a comment there instead
