### ISSUE TITLE
Add download button to xilinx certified pages

### ISSUE THREAD

**Issue by petesfrench** [canonical/ubuntu.com#12381]
Felicia has requested that any certified page from the vendor Xilinx should include a download button that leads to https://ubuntu.com/download/amd-xilinx

See [this conversation thread](https://chat.canonical.com/canonical/pl/hnpqjthn9fdd5xcfbxirbyu74e) for more info

**Comment by jpmartinspt** [comment]
I thought it was only for `core` device pages apparently there are more device pages where they want the button. There is some existing logic I was unsure I should change so I passed the ball to sites.

**Comment by petesfrench** [comment]
This work is being tracked here https://warthogs.atlassian.net/browse/WD-1403
