### ISSUE TITLE
Duplicated page navigation in Discourse-generated docs

### ISSUE THREAD

**Issue by fitojb** [canonical/ubuntu.com#12386]
https://ubuntu.com/security/certifications/docs/disa-stig/installation
![imatge](https://user-images.githubusercontent.com/554953/209100240-1be4c6c2-e2bb-49a0-a57b-7a8037974c10.png)

There are two links to go “back” and two links to go “forward”; I expect only one of each

**Comment by carkod** [comment]
Fixed

**Comment by immortalcodes** [comment]
Duplicate of #12913 , The conversations are on the other issue.
Thanks for reporting
