### ISSUE TITLE
Update ubuntu.com/kubernetes/compare copy

### ISSUE THREAD

**Issue by AlexsJones** [canonical/ubuntu.com#12399]
## Summary

Hello, I would like to request the [this](https://ubuntu.com/kubernetes/compare) site copy is updated in line with other platform changes and developments. I am the director of the team and have the authority to request it.

Many thanks!

## Process

Please see the suggested changes as the requested items to update.

(https://docs.google.com/document/d/1JngYmRhohPo62yU72V1xpzCCILI21SmHKKttBxHjPog/edit)

**Comment by carkod** [comment]
Issue moved to [canonical/web-squad #6326](https://github.com/canonical/web-squad/issues/6326) via [**Zenhub**](https://www.zenhub.com/)
