### ISSUE TITLE
Create Canoical Kubernetes combination images

### ISSUE THREAD

**Issue by petesfrench** [canonical/ubuntu.com#12405]
Felipe has requested the creation of two images, combining the Canonical Kubernetes logo with a partner logo.
These are the two partner logo for the two images:
https://assets.ubuntu.com/v1/a0da6c7e-dell-technologies-logo.png
https://drive.google.com/file/d/1f_5mJxqMD5aTlh_tV5dSVPO14OikZh4j/view?usp=share_link
EXAMPLE: ![image.png](https://images.zenhubusercontent.com/609109f935b2ad43af7db68e/e7da2e45-0349-41b1-bc27-d728e69a0eb6)
copydoc: https://docs.google.com/document/d/1enaCJ4Vt9a_2_l6xYccnZ-fBVUejPSmfMi8LP2aDA9c/edit#

**Comment by bogdans-canonical** [comment]
@petesfrench , @felipevanni , do we need 2 images? One HPE and one Dell?

**Comment by bogdans-canonical** [comment]
FYI, here is the jira ticket:
https://warthogs.atlassian.net/browse/WD-1164

**Comment by felipevanni** [comment]
> @petesfrench , @felipevanni , do we need 2 images? One HPE and one Dell?

Yes, we need both as Dell changed its logo/name

**Comment by bogdans-canonical** [comment]
@felipevanni , OK, what's the due date?

**Comment by egezeytun** [comment]
Dell and HPE done. We are updating the one with Lenovo too so that they all follow our new styling guidelines.

Jira ticket for the brand task: https://warthogs.atlassian.net/browse/WD-1164

Cc @petesfrench @felipevanni

**Comment by carkod** [comment]
Should we move this over to Jira? I believe this is not completed.

**Comment by mtruj013** [comment]
Based on the jira ticket looks like this has been addressed, closing
