### ISSUE TITLE
Ubuntu _Advantage_ (not Pro) listed under the Products menu

### ISSUE THREAD

**Issue by mfoliveira** [canonical/ubuntu.com#12404]
Not sure if that's on purpose; reporting just in case.

If you click the `Products` menu at the top, right-hand corner,
the 9th option is `Ubuntu Advantage`, which seems outdated
considering the rename to `Ubuntu Pro` (as in the target page).

---
*Reported from: https://ubuntu.com/*

**Comment by anthonydillon** [comment]
@mfoliveira thank you very much for taking the time to report this issue to us. I am working on an update now.
