### ISSUE TITLE
manual title says 22.04 even tho i downloaded 12.10

### ISSUE THREAD

**Issue by mrseal52** [canonical/ubuntu.com#12415]
---
*Reported from: https://ubuntu.com/download/desktop/thank-you?version=22.10

**Comment by fitojb** [comment]
By manual you mean the Ubuntu Desktop Guide? That is OK, because the online version of that site is updated only for LTS versions. Anyway, the downloaded ISO will always contain the correct offline docs.

**Comment by fitojb** [comment]
I think it’s an easy change to remove the version number from the link :)
