### ISSUE TITLE
Place to get Pro token is hard to notice

### ISSUE THREAD

**Issue by nobuto-m** [canonical/ubuntu.com#12411]
Pro client guides users to https://ubuntu.com/pro to obtain a token.

```
$ sudo ua attach
Attach requires a token: sudo pro attach <TOKEN>
To obtain a token please visit: https://ubuntu.com/pro.
```

However, the actual link to obtain the token is not in the main page body but only in the header and footer as it's highlighted as pink in the following screenshot. The user flow should be more noticeable in my opinion.

![Screenshot 2023-01-11 at 15-02-43 Ubuntu Pro Ubuntu_s](https://user-images.githubusercontent.com/4356209/211730135-2f8a9e37-38d5-4c35-9c1e-22d5e5eafce8.png)

---
*Reported from: https://ubuntu.com/pro*

**Comment by jpmartinspt** [comment]
@nobuto-m there are two call to actions when you land on the Pro page now. do you think this issue is still relevant with the new page?

**Comment by nobuto-m** [comment]
> @nobuto-m there are two call to actions when you land on the Pro page now. do you think this issue is still relevant with the new page?

Do you mean the new green "Get Ubuntu Pro now" button? If so, yes, it's definitely better than the previous page. Thanks!

**Comment by jpmartinspt** [comment]
Yeah, there should be that button and another one that redirects you to the dashboard in case you already have subscriptions.

**Comment by nobuto-m** [comment]
Actually it didn't address my initial point. Let's say I'm a paying customer of Pro and would like to fetch my token.

Even with the new page, the green button is to purchase additional Pro seats and the white one next to it is for personal use. So there is no obvious option to check the token with existing purchased seats.

https://ubuntu.com/pro
![image](https://user-images.githubusercontent.com/4356209/227120100-5e1bcc1c-a561-485e-8dba-fa3377af717f.png)
