### ISSUE TITLE
Reference to "Ubuntu Advantage" instead of "Ubuntu Pro" in the Meganav

### ISSUE THREAD

**Issue by dgtlntv** [canonical/ubuntu.com#12410]
## Summary

In the Meganav, under Products "Ubuntu Pro" is still listed as "Ubuntu Advantage". 

## Screenshot

![Screenshot from 2023-01-10 15-56-39](https://user-images.githubusercontent.com/68336485/211589023-2621989b-2811-4e82-a2e9-f1b4976cb74e.png)

**Comment by britneywwc** [comment]
Thanks for flagging, it was renamed to "Ubuntu Pro" now with one of the recent meganav updates. I've attached a screenshot below for your reference. Closing this issue as resolved.
<img width="1199" alt="Screenshot 2024-07-24 at 2 50 37 PM" src="https://github.com/user-attachments/assets/82bf1943-ecda-4787-b26e-369857df7332">
