### ISSUE TITLE
&AMP; is showing instead of &

### ISSUE THREAD

**Issue by yurii-vasyliev** [canonical/ubuntu.com#12425]
## Summary

Within the blog posts, we can see sometimes `&AMP;` instead of `&`.

## Process

Go to https://ubuntu.com/blog and find any post with that issue.

## Current and expected result

it's showing `&AMP;` instead of `&`

## Screenshot

https://capture.dropbox.com/hqlNlqLyQrhZZ2BB

## Browser details

Chrome, MacOS

**Comment by carkod** [comment]
Fixed. Removed dup "category"
