### ISSUE TITLE
Free Pro personal token incorrect count for community members

### ISSUE THREAD

**Issue by setharnold** [canonical/ubuntu.com#12453]
Hello, our documentation for Ubuntu Pro says that there's two free tiers, one for everybody with five machines, and one for Ubuntu members with fifty machines:

> Anyone can use Ubuntu Pro for free on up to 5 machines, or 50 if you are an official Ubuntu Community member.

https://ubuntu.com/pro

You can see from my launchpad page https://launchpad.net/~seth-arnold that I'm a member of https://launchpad.net/~ubuntumembers but this isn't reflected in my own dashboard:

![count](https://user-images.githubusercontent.com/5447148/214359481-94a93bed-db59-48c2-a9a1-9ec31cea2a8b.png)

This was reported to me by https://launchpad.net/~jdstrand

Thanks

---
*Reported from: https://ubuntu.com/pro/dashboard*

**Comment by jdstrand** [comment]
In case it is helpful, I'm former Canonical (2 years ago) but https://login.ubuntu.com/+emails does not list my old Canonical address: only valid ones that I use (my preferred email, my @ubuntu.com email, etc.
