### ISSUE TITLE
NO SUPPORT with a price

### ISSUE THREAD

**Issue by nobuto-m** [canonical/ubuntu.com#12465]
I personally know what "no support" in this context means and why it costs.

![image](https://user-images.githubusercontent.com/4356209/214878764-2c0823db-36da-42f5-8b48-a2668c8c84c1.png)

However, when somebody looks into this page for the first time, this table "NO SUPPORT = $30" is confusing as in "what am I paying for if there is no support".

Probably, "self-support", "no phone support", or "no ticket support" is more general term in this context. "No support" is a strong word to me and causes confusions IMO.

---
*Reported from: https://ubuntu.com/pricing/pro*

**Comment by mtruj013** [comment]
Hi @lechsandecki, are you the most appropriate pdm to reach out to for input on this?

**Comment by lechsandecki** [comment]
I see your point. Yes, we could rename it to "bits-only" or "self-support", as suggested
