### ISSUE TITLE
Pressing [Enter] doesn't start CVE search

### ISSUE THREAD

**Issue by nobuto-m** [canonical/ubuntu.com#12478]
How to reproduce:
1. Go to https://ubuntu.com/security/cves
2. Type keywords in the "CVE ID or description contains" field
3. Press [Enter]

Expected:
the search is executed and the URL is changed to `https://ubuntu.com/security/cves?q=foobar` or equivalent.

Actual:
Nothing happens.

![image](https://user-images.githubusercontent.com/4356209/215368297-1309dc08-676a-425b-91eb-c5a2ca7b306b.png)

---
*Reported from: https://ubuntu.com/security/cves*

**Comment by petesfrench** [comment]
@carkod Should this not be included in the CVE overhaul?
