### ISSUE TITLE
CVE package search is exact match only

### ISSUE THREAD

**Issue by nobuto-m** [canonical/ubuntu.com#12477]
When searching with a package name, it requires users to type the exact and complete package name.

For example, if a user would like to search MySQL or PostgreSQL CVEs, they must know those database versions beforehand. For example:

"mysql-8.0" returns an expected result for Ubuntu 22.04 LTS.
https://ubuntu.com/security/cves?q=&package=mysql-8.0

However, "mysql" doesn't contains expected result for Ubuntu 22.04 LTS.
https://ubuntu.com/security/cves?q=&package=mysql

The same condition applies to PostgreSQL.

"postgresql-14" works.
https://ubuntu.com/security/cves?q=&package=postgresql-14

However, "postgresql" doesn't contains expected result:
https://ubuntu.com/security/cves?q=&package=postgresql

It would be good if the field allows a partial match or at least offers a checkbox to explicitly enable partial match search.

[with keyword "postgresql-14"]
![image](https://user-images.githubusercontent.com/4356209/215367823-8d6925bb-b81d-4570-8079-79e235859075.png)

[with keyword "postgresql"]
![image](https://user-images.githubusercontent.com/4356209/215367788-b2004154-409b-49f4-bb8e-a972a7f5c74f.png)

---
*Reported from: https://ubuntu.com/security/cves?q=

**Comment by mtruj013** [comment]
Addressed in https://github.com/canonical/ubuntu-com-security-api/pull/153, closing
