### ISSUE TITLE
Ubuntu Pro: visual glitches

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/ubuntu.com#12473]
Hi, great work on the Ubuntu Pro page! I somehow wasn't involved in qa'ing it before it went live, and would like to point out a few small glitches:

https://www.figma.com/file/ZAihKxF2wmj9wvoPSnPKmY/Commercial%3A-Ubuntu-Pro?node-id=3227%3A17378&t=S5f4fQZb7w42mHsb-1

**Comment by theVJagrawal** [comment]
hey @lyubomir-popov I want to work on this issue so can you please elaborate it more

**Comment by lyubomir-popov** [comment]
@theVJagrawal I'm affraid this is an internall issue and requiores access to files that are not accessible to contributors.

**Comment by lyubomir-popov** [comment]
@carkod can you please schedule this in?
