### ISSUE TITLE
Claims that non-existing things are supported

### ISSUE THREAD

**Issue by xnox** [canonical/ubuntu.com#12548]
A what's covered has the following contents:

RELEASE | UBUNTU BASE OS SECURITY COVERAGE | SECURITY UPDATES - UNIVERSE REPO (APPLICATIONS & TOOLCHAINS) | KERNEL LIVEPATCH | ARCHITECTURES SUPPORTED WITH ESM
-- | -- | -- | -- | --
Ubuntu 14.04 LTS (Trusty Tahr) | Until 2024 | n/a | yes | x86
Ubuntu 16.04 LTS (Xenial Xerus) | Until 2026 | Until 2026 | yes | x86
Ubuntu 18.04 LTS (Bionic Beaver) | Until 2028 | Until 2028 | yes | x86, ARM, S390X, POWER, RISC-V
Ubuntu 20.04 LTS (Focal Fossa) | Until 2030 | Until 2030 | yes | x86, ARM, S390X, POWER, RISC-V
Ubuntu 22.04 LTS (Jammy Jellyfish) | Until 2032 | Until 2032 | yes | x86, ARM, S390X, POWER, RISC-V

Ubuntu 18.04 LTS does not have RISC-V architecture at all, hence it cannot possibly have RISC-V ESM support.

kernel livepatch is not a yes/no boolean, but architecture specific, at the moment it is x86 only. It might gain S390X soon on focal and up (to be announced). There is no live-patch capability on ARM POWER RISC-V.

---
*Reported from: https://ubuntu.com/security/esm*

**Comment by mtruj013** [comment]
Looks like this has been addressed, closing 
![image](https://github.com/user-attachments/assets/9a41cd01-dc63-4ada-a78f-f16d7458c90e)
