### ISSUE TITLE
Support conflict

### ISSUE THREAD

**Issue by anantav51** [canonical/ubuntu.com#12541]
It says "Ubuntu 16.04 LTS is supported until 2026" in the description but in the table right below it it says it's only supported up to April 2024.
---
*Reported from: https://ubuntu.com/16-04*

**Comment by petesfrench** [comment]
Hi Anantav51, for me the table also shows support until 2026: 
![image.png](https://images.zenhubusercontent.com/609109f935b2ad43af7db68e/5c55f96e-df60-45ca-a776-5266507819cd)
Could you tell us how to replicate the issue you had please?

**Comment by petesfrench** [comment]
Thank you for the extra information, we will fix this ASAP.
