### ISSUE TITLE
CI takes 6 hours on failure & takes GitHub runner out of pool for `canonical` organization

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/ubuntu.com#12558]
When the [.github/workflows/pr.yaml](https://github.com/canonical/ubuntu.com/blob/main/.github/workflows/pr.yaml) `run-image` job fails, it can take 6 hours to fail instead of the [normal 1-2 minutes](https://github.com/canonical/ubuntu.com/actions/runs/4203428385/jobs/7292808614).

![6hr](https://user-images.githubusercontent.com/115640263/219665220-8f3f1b16-8ff3-4556-b528-5a1c0485a2c8.png)

From: https://github.com/canonical/ubuntu.com/actions/runs/4201489112/jobs/7288543596

The `canonical` organization is currently reaching the maximum concurrent GitHub runner limit: https://chat.canonical.com/canonical/pl/p7qq3g4se7brjchzszyoiqfxqr

**Comment by petesfrench** [comment]
@nottrobin could you look into this please
