### ISSUE TITLE
Remove redirects to 'advantage' pages

### ISSUE THREAD

**Issue by petesfrench** [canonical/ubuntu.com#12567]
## Summary

- Our redirects folder still contains a lot of redirects that send you to pages containing the word 'advantage'. In some cases these are caught by another redirect that takes you to the appropriate pro page, however some are leading to 404s.

**Comment by sumanbiswas7** [comment]
Hello 👋 @petesfrench, Could you mind telling me which redirects folder you're talking about? Maybe I can fix this.
