### ISSUE TITLE
OpenStack logo on https://ubuntu.com doesn't stand out on.

### ISSUE THREAD

**Issue by sumanbiswas7** [canonical/ubuntu.com#12582]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

The OpenStack logo on [homepage](https://ubuntu.com) doesn't stand out on the grey background.

## Steps to reproduce
1. Go to [homepage](https://ubuntu.com)
2. Refresh until the OpenStack logo appears

## Screenshot
![Screenshot 2023-02-22 103916](https://user-images.githubusercontent.com/89641167/220528239-fbcaf868-2db7-4299-9092-f167fefe8918.png)

**Comment by petesfrench** [comment]
Thanks for reporting this issue, this has now been updated to the following:
![image.png](https://images.zenhubusercontent.com/609109f935b2ad43af7db68e/abd0f886-6f5e-4017-8a92-2af41ee2128e)
