### ISSUE TITLE
Links to Netplan are broken

### ISSUE THREAD

**Issue by hobpet** [canonical/ubuntu.com#12597]
These provide 404:
https://netplan.readthedocs.io/en/latest/examples.html#configuring-network-bridges
https://netplan.readthedocs.io/en/latest/examples.html

---
*Reported from: https://ubuntu.com/server/docs/virtualization-libvirt*

**Comment by hobpet** [comment]
This seems to be the new one: https://netplan.readthedocs.io/en/stable/examples/#configuring-network-bridges

**Comment by carkod** [comment]
Hi @hobpet thanks for reporting. This is the repo of ubuntu.com. Could you report this on the specific documentation page?  You can find it at the bottom of the page. Thank you!

https://discourse.ubuntu.com/t/virtualization-libvirt/11522?_ga=2.158373234.995254615.1677254307-540604496.1669524745

**Comment by carkod** [comment]
> Hi @carkod, As you can see on the initial comment, it is an Ubuntu documentation issue. I've used the link at the bottom of the page that added this, that shows the page with the problem: Reported from: https://ubuntu.com/server/docs/virtualization-libvirt

Sorry, what I meant is this link

<img width="907" alt="Screenshot 2023-02-24 at 15 59 43" src="https://user-images.githubusercontent.com/14939793/221229953-ab1a0b06-d8bc-4de1-9ffc-14e76f439c40.png">

The documentation pages show on https://ubuntu.com/ but they are maintained by a different team, and there is usually a discussion around it, which you can find on Discourse https://discourse.ubuntu.com/t/virtualization-libvirt/11522?_ga=2.158373234.995254615.1677254307-540604496.1669524745

**Comment by hobpet** [comment]
Ah, OK.
I've scrolled further down, where there is this link that I used as suggested by itself:  [Report a bug on this site](https://github.com/canonical-websites/www.ubuntu.com/issues/new?body=%0a%0a%0a---%0a*Reported%20from:%20https://ubuntu.com/server/docs/virtualization-libvirt*)

`https://github.com/canonical-websites/www.ubuntu.com/issues/new?body=%0a%0a%0a---%0a*Reported%20from:%20https://ubuntu.com/server/docs/virtualization-libvirt*`

That has created this issue.
