### ISSUE TITLE
The ubuntu logo has poor visibility on this background and is using the old logo

### ISSUE THREAD

**Issue by petesfrench** [canonical/ubuntu.com#12604]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

The ubuntu logo has poor visibility on this background and is using the old logo:
![image](https://user-images.githubusercontent.com/58276363/221514437-e4744b97-28d0-4483-8025-ae05729c594d.png)

**Comment by shivamsinghcse** [comment]
Hey! can You Please assign this issue i really want to contribute in this project because i use it as my main os

**Comment by petesfrench** [comment]
Hey @shivamsinghcse, thanks for your interest in contributing! It looks like this issue has since been fixed so I will close it now.
