### ISSUE TITLE
Update featured apps in /desktop/features

### ISSUE THREAD

**Issue by juanruitina** [canonical/ubuntu.com#12606]
I noticed a couple of things that we could tweak on the list of featured apps for Desktop:

* Firefox and Chromium logos are outdated (the ones in Snapcraft are OK).
* Atom has been [sunset](https://github.blog/2022-06-08-sunsetting-atom/), should we feature [Visual Studio Code](https://snapcraft.io/code) instead?
* "[Discover more apps in the Snap Store.](https://snapcraft.io/store)" should use a chevron: "[Discover more apps in the Snap Store.](https://snapcraft.io/store)" 

---
*Reported from: https://ubuntu.com/desktop/features*

**Comment by carkod** [comment]
This is best if we add it as a comment to the [copy doc](https://docs.google.com/document/d/1nLHJlZ3igDwAAOUDP03wp4iKLxZts8110EA2ZOF5uaU/edit) for the page/product owner to take a look at.
