### ISSUE TITLE
"Ubuntu Pro (esm-apps --beta) tutorial" in pro/dashboard

### ISSUE THREAD

**Issue by nobuto-m** [canonical/ubuntu.com#12665]
https://ubuntu.com/pro/dashboard still refers `--beta` as follows.

> Documentation
> 
> Documentation & tutorials
> 
> Ubuntu Pro (esm-apps --beta) tutorial
>     To attach a machine: sudo pro attach XYZ

https://github.com/canonical/ubuntu.com/blob/b27c4d054d99ccf67277779d045b09da8551281e/static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx#L95-L99

https://github.com/canonical/ubuntu.com/blob/b27c4d054d99ccf67277779d045b09da8551281e/static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx#L161-L168

---
*Reported from: https://ubuntu.com/pro/dashboard*

**Comment by jpmartinspt** [comment]
This has been fixed and should be deployed soon.
