### ISSUE TITLE
OpenStack chart is out of date

### ISSUE THREAD

**Issue by coreycb** [canonical/ubuntu.com#12714]
OpenStack Zed and Antelope should be added to the support lifecycle chart.

---
*Reported from: https://ubuntu.com/about/release-cycle*

**Comment by immortalcodes** [comment]
Hey, the chart has been updated could you take a look?
@coreycb

**Comment by coreycb** [comment]
Hey Madhur, I'm no longer with Canonical and someone from Canonical should probably be reviewing this. Thank you.

**Comment by immortalcodes** [comment]
This page has been recently redesigned, I checked the releases you mentioned and they are no longer supported.
I am closing this issue but if you feel that this still lacks the required information at some point.
Feel free to re-open this issue.
Thanks for reporting this!
