### ISSUE TITLE
Please update kernel release cycle to cover 22.04 LTS

### ISSUE THREAD

**Issue by tomreyn** [canonical/ubuntu.com#12741]
Please update the text and graphic on https://ubuntu.com/about/release-cycle#ubuntu-kernel-release-cycle to also cover 22.04 LTS.
Thanks.

---
*Reported from: https://ubuntu.com/about/release-cycle

**Comment by immortalcodes** [comment]
I think it covers it with the new diagram. But if you still think it does not feel free to re-open the issue.
