### ISSUE TITLE
/aws recommends 20.04 although /aws/pro says 22.04 is the latest

### ISSUE THREAD

**Issue by nobuto-m** [canonical/ubuntu.com#12771]
The following page mentions that Ubuntu Pro **22.04** LTS is the latest and Ubuntu Pro **20.04** LTS is in the previous releases.
https://ubuntu.com/aws/pro

However, the following page assumes that **20.04** is the default option.
https://ubuntu.com/aws

![image](https://user-images.githubusercontent.com/4356209/231325086-0452cf85-dd64-492a-9b91-cc2af245d85d.png)

---
*Reported from: https://ubuntu.com/aws*

**Comment by nobuto-m** [comment]
This may be actually because of FIPS and co.
https://ubuntu.com/security/fips

**Comment by immortalcodes** [comment]
Could you check if this is resolved now?

**Comment by nobuto-m** [comment]
No longer the case
