### ISSUE TITLE
ros-esm CVE requests are flooding git.launchpad.net

### ISSUE THREAD

**Issue by cjwatson** [canonical/ubuntu.com#12784]
## Summary

https://github.com/canonical/ubuntu.com/blob/main/webapp/security/views.py#L468 is absolutely flooding git.launchpad.net with a continuous flow of multiple requests per second for files that have had precisely two commits ever and at the time of writing haven't changed since September 2022.  I know that it says it's a temporary fix pending redesign, but this is enough to be contributing to operational problems.  Please put some kind of caching in place so that you aren't doing these expensive fetches every time anyone views a CVE page on the website.

**Comment by hloeung** [comment]
Or maybe bake these into the image and update on build time/release?
