### ISSUE TITLE
Stack Trace Disclosure (Python)

### ISSUE THREAD

**Issue by devplayer55221** [canonical/ubuntu.com#12794]
While searching for some Wifi adapter driver, I found that the Ubuntu page is disclosing stack trace, and it is revealed that Python 2.7.17 is being used in the backend.
The URL affected is: [https://help.ubuntu.com/community/WifiDocs/](https://help.ubuntu.com/community/WifiDocs/)

![ubuntu website error](https://user-images.githubusercontent.com/29159942/231857049-0aa5e5bb-4926-4d9f-8f05-87bc1e8d7913.png)

---
*Reported from: https://ubuntu.com/*

**Comment by immortalcodes** [comment]
Thanks for pointing this out. This page has been fixed.
