### ISSUE TITLE
Navigating to /hpc returns HTTP 500 Server Error

### ISSUE THREAD

**Issue by NucciTheBoss** [canonical/ubuntu.com#12822]
Hey folks! When attempting to load https://ubuntu.com/hpc I am greeted by a 500: Server Error and a link directed towards reporting an issue here. This is what I see when I try to load the page:

![image](https://user-images.githubusercontent.com/40342202/234091384-c4228c84-79f8-44c2-9274-f3f702df99a7.png)

**Comment by dvdgomez** [comment]
I am also seeing this
