### ISSUE TITLE
Filling out the form in engage/aws-pro-onboarding leads to 404

### ISSUE THREAD

**Issue by nobuto-m** [canonical/ubuntu.com#12827]
The following page has a form to submit user data to "Download the whitepaper".
https://ubuntu.com/engage/aws-pro-onboarding

It leads to the "thank-you" page as:
https://ubuntu.com/engage/aws-pro-onboarding/thank-you
But the page doesn't exist.

```
$ curl -s https://ubuntu.com/engage/aws-pro-onboarding | grep returnURL
        <input type="hidden" name="returnURL" aria-label="returnURL" value="/engage/aws-pro-onboarding/thank-you" />
```

---
*Reported from: https://ubuntu.com/engage/aws-pro-onboarding*

**Comment by tobegreater** [comment]
`N`

**Comment by carkod** [comment]
Thanks for reporting, I think there is a conflict here in this page, it's indicated that it's a whitepaper, however, a webinar is provided instead and no whitepaper is provided. So left a comment for the author of the engage page](https://discourse.ubuntu.com/t/getting-started-with-ubuntu-pro-on-aws/27695/2?u=carkod)

**Comment by carkod** [comment]
Removed form for now, as whitepaper is not provided.
