### ISSUE TITLE
Typo in the "Open source security" section

### ISSUE THREAD

**Issue by nothingneko** [canonical/ubuntu.com#12826]
I'm not sure if this was intentional (spelling in UK English) or a typo, thought I'd report it to be safe
![image](https://user-images.githubusercontent.com/37665485/234312609-653da4c1-6ad1-418f-a9f0-e7b0382bb92e.png)

---
*Reported from: https://ubuntu.com/*

**Comment by carkod** [comment]
Thanks for reporting. Yes, at Canonical we use British English across our sites.
