### ISSUE TITLE
Incorrect command example on GoPaddle blog post

### ISSUE THREAD

**Issue by RomanKolo** [canonical/ubuntu.com#12835]
The first example command on the page is 
` microk8s microk8s enable community`
but should be
` microk8s enable community`

This is about 2/3rds of the way down on https://ubuntu.com/blog/gopaddle-a-low-code-internal-developer-platform-for-canonicals-microk8s-edge-cloud

---
*Reported from: https://ubuntu.com/blog/gopaddle-a-low-code-internal-developer-platform-for-canonicals-microk8s-edge-cloud*

**Comment by immortalcodes** [comment]
Thanks for pointing this out, this has been updated in the blog but it could be bigger issue than that and same has been communicated to Microk8s team.
