### ISSUE TITLE
Link 'Charmed OpenStack' leads to the wrong place

### ISSUE THREAD

**Issue by pmatulis** [canonical/ubuntu.com#12841]
The visible link **Charmed OpenStack** on https://ubuntu.com/openstack points to https://jaas.ai/openstack , which is being redirected to the root of https://charmhub.io .

![image](https://user-images.githubusercontent.com/6303808/236422685-87e1b1b9-fea0-404e-a7e3-aa1d931e5270.png)

Maybe the visible link should be **OpenStack charms** and should go instead to https://charmhub.io/?q=OpenStack

**Comment by LeaDevelop** [comment]
I had a looksy, I can take care of this issue :)

**Comment by LeaDevelop** [comment]
@anthonydillon thank you for the review! Could you also please close the issue as well, I don't have permissions to assign branch or PR 😊 and it did not auto close issue after merge, despite using issue id in the name of the PR #13205
