### ISSUE TITLE
Link 'Report a bug on this site' is broken

### ISSUE THREAD

**Issue by pmatulis** [canonical/ubuntu.com#12840]
In the footer of ubuntu.com there is a broken link. The visible link is **Report a bug on this site**.

![image](https://user-images.githubusercontent.com/6303808/236422104-394ad0ac-8587-4962-827b-f7b3bbb8997f.png)

**Comment by LeaDevelop** [comment]
I can take a look at this issue

**Comment by LeaDevelop** [comment]
@anthonydillon thank you for the review! Could you also please close the issue as well, I don't have permissions to assign branch or PR 😊 and it did not auto close issue after merge, despite using issue id in the name of the PR #13208
