### ISSUE TITLE
Dead link in tutorial "How to install a Windows 11 VM using LXD"

### ISSUE THREAD

**Issue by IamLizu** [canonical/ubuntu.com#12853]
## Summary

In the "[2. Prepare your Windows image](https://ubuntu.com/tutorials/how-to-install-a-windows-11-vm-using-lxd#2-prepare-your-windows-image:~:text=2.%20Prepare%20your%20Windows%20image)" section of the tutorial, there is a link to download Windows 11 which leads to a blank page.

## Screenshot

![image](https://github.com/canonical/ubuntu.com/assets/26184316/ce8dd90b-3b11-4e8d-a9da-1a0754a8349b)

**Comment by carkod** [comment]
That looks like it was an issue on Microsoft's side. It works now.
