### ISSUE TITLE
navigation item with `u-show--small` class looks a bit off on small screens

### ISSUE THREAD

**Issue by minkyngkm** [canonical/ubuntu.com#12859]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

Go to navigation on ubnutu.com on small screens and click  "Enterprise"

when `p-list__item` class is with `u-show--small`, it looks a bit weird. 
<img width="513" alt="Screenshot 2023-05-11 at 12 21 24 pm" src="https://github.com/canonical/ubuntu.com/assets/57550290/2599ea65-26b4-4ef7-b7cf-78cdab0c69ee">
<img width="490" alt="Screenshot 2023-05-11 at 12 22 14 pm" src="https://github.com/canonical/ubuntu.com/assets/57550290/58cf3aa8-c2ab-4156-b0d6-e9efee7261a3">

when `p-list__item` class is with `u-show--small` display value seems to change...
![image](https://github.com/canonical/vanilla-framework/assets/57550290/c61e381c-cc25-4921-8897-4eb3e9f8bd85)

**Comment by minkyngkm** [comment]
Hey @bartaz ! Is this a bug that needs to be fixed in vanilla? What do you think?

**Comment by bartaz** [comment]
@minkyngkm hey, thanks for asking.

Overall yes, it seems that `u-show` utility (display: initial) doesn't work well with list items.

But, you can also fix it on Ubuntu.com for now by not using `u-show--small` at all.

Currently you have `u-show--small u-hide--medium u-hide--large`, in this case `u-show--small` is redundant. If you remove it, item will still be shown on small screens (correctly) and hidden on medium and large.

But, apart from fixing by removing `u-show--small` please report a but in Vanilla that it doesn't work well on list items.

**Comment by minkyngkm** [comment]
Thanks @bartaz 👍
