### ISSUE TITLE
Image: Change from Extended to Expanded Security Maintenance (ESM) 

### ISSUE THREAD

**Issue by jupeuk** [canonical/ubuntu.com#12866]
In the Ubuntu Releases image we still spell out "ESM" as **Extended** Security Maintenance when it has been changed to **Expanded** Security Maintenance recently, which is already implemented in the text of the page. Please update the image as well. Thanks!

---
*Reported from: https://ubuntu.com/about/release-cycle*

**Comment by britneywwc** [comment]
Hi @jupeuk, the page has been updated since the date of this issue and we have updated the text to "**Expanded Security Maintenance** now. I will close this issue as resolved. Thank you!
