### ISSUE TITLE
Update ubuntu logo in readme.md

### ISSUE THREAD

**Issue by petesfrench** [canonical/ubuntu.com#12872]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

Readme is still using the old logo

## Screenshot

![image](https://github.com/canonical/ubuntu.com/assets/58276363/ff357d26-de85-415e-b944-7ffe2b255e04)

## Browser details

[Please tell us what browser(s) you used when you encountered this bug and any other information that might be relevant, like if you block javascript, run an ad blocker, etc...]

**Comment by shivamsinghcse** [comment]
can you please assign this i want to contribute in this project

**Comment by anthonydillon** [comment]
You can find the logo assets on our design resources site: https://design.ubuntu.com/resources.
