### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Metz94** [canonical/ubuntu.com#12922]
Second paragraph:

Ubuntu Server brings economic and technical scalability to your "datacentre"

There is a typo on the word datacenter.
---
*Reported from: https://ubuntu.com/server/docs*

**Comment by hwittenborn** [comment]
From what I've read `center` can be spelled like `centre` in British English, so I think it might be correct since Canonical is based out of the UK. Just throwing it out as a guess.

**Comment by Metz94** [comment]
> From what I've read `center` can be spelled like `centre` in British English, so I think it might be correct since Canonical is based out of the UK. Just throwing it out as a guess.

Yes, you are right, my mistake
