### ISSUE TITLE
http://www.ubuntu.com/fan is in documentation but 404s

### ISSUE THREAD

**Issue by vorlonofportland** [canonical/ubuntu.com#12927]
The file /usr/share/doc/ubuntu-fan/README.gz as shipped in several stable Ubuntu releases (at least as far back as Ubuntu 16.04) points to http://www.ubuntu.com/fan, but this URL 404s, as reported in https://bugs.launchpad.net/ubuntu/+source/ubuntu-fan/+bug/1977946.

We should not do stable release updates in Ubuntu to fix a wrong URL in documentation; but we can fix the URL to not 404.

Per the above bug, I suggest this should become a redirect to https://wiki.ubuntu.com/FanNetworking and that, going forward, the documentation should be fixed to point to this URL directly.

**Comment by carkod** [comment]
Hey @vorlonofportland, is there a reason you can't change it in the `readme.gz`?
