### ISSUE TITLE
Wifi not detected

### ISSUE THREAD

**Issue by al-ianfebrian** [canonical/ubuntu.com#12947]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

[Last night, I installed ubuntu version 20.04 LTS, on my laptop I can't use wifi and in the settings there is only airplane mode I can't find the mode to activate wifi. Is this a bug or was there something wrong with me during ubuntu installation.
Please help...]

**Comment by elias-soykat** [comment]
@al-ianfebrian 
I recommend you to run 2 commands and update, your machine

```js
sudo apt-get upgrade

sudo apt-get update
```

then restart the laptop. hopefully, it will be resolved.

**Comment by carkod** [comment]
Stale. In any case, this is the repo for the site, for issues regarding Ubuntu please go to https://help.ubuntu.com/community/ReportingBugs
