### ISSUE TITLE
OpenStack logo is black on dark background - needs to be white

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/ubuntu.com#12965]
![image](https://github.com/canonical/ubuntu.com/assets/2741678/b8bbbc2e-19df-41ed-a6ba-59819ba5458d)

**Comment by anthonydillon** [comment]
This has been fixed. @prk9987 these takeovers should be reviewed before going live.

**Comment by lyubomir-popov** [comment]
Thank you!
