### ISSUE TITLE
Minimum, Maximum and close button bugs

### ISSUE THREAD

**Issue by TRex219961** [canonical/ubuntu.com#12990]
I use Ubuntu 23.04 in Acer Travelmate P214-52 and i receive a bugs:
i click the button: Minimum, maximum, close button in firefox it open Anydesk
Gnome version: 44.2 and X11
[Recoding.webm](https://github.com/canonical/ubuntu.com/assets/88968137/ce5d9b90-7883-44b1-a916-0c8fb26952a7)

**Comment by SajjadAemmi** [comment]
Just remove anydesk and reboot

**Comment by anthonydillon** [comment]
Sorry, this is the issue list for the Ubuntu website. For OS issues please report them on: https://bugs.launchpad.net/ubuntu
