### ISSUE TITLE
"support portal" button leads to ugly loop

### ISSUE THREAD

**Issue by setharnold** [canonical/ubuntu.com#13003]
Hello, I (a canonical employee) hit the "support portal" link on the Ubuntu Pro dashboard to see where it leads:

- https://login.ubuntu.com/saml/process
- https://portal.support.canonical.com/secur/frontdoor.jsp?sid=00D20000000145O%21AQoAQEfrPubTFAhBxmjEHB6PJk89FXjNjYkYP1k6ysXRTZ.u_DjHpeBRa0ZAAm85TNx3TQq9EcTYrOHEUtuXyxDelyTt.0D2&retURL=%2Fs%2F&loginURL=https%3A%2F%2Fsaml.salesforce.com%3Fssostartpage%3Dhttps%253A%252F%252Flogin.ubuntu.com%252F%252Bsaml%26saml_request_id%3D_2CAAAAYmZ92kRMDAwMDAwMDAwMDAwMDAwAAAA9Brbf3JKrWJOqPEBnka1md9f-UdgEsldkmeSPATYYUdSD-hUIYVe1CpPmD9GUed8sOJCAwADT0wvam9BAsK_bvAunJQTQcf2I1GD22jfaREjegW4hcLOtGOd-5YLKTQhjrl562zAmdOGxHNx1VUItuZWBjm7VZwcd7QR1GiG1CRdvM4tHCGL74pVef3giMPmflrlMVC4pZ0vTMhy5a1oAxmCKiovXuIh0dcB3VUSCE4ucSKNDNDuoqoi9DXMjl8PuQ%26logouturl%3Dhttps%253A%252F%252Flogin.ubuntu.com%252F&cshc=0000008eg7q0000000145O

It bounces around these URLs chaotically for a while; I hit the back button to see if that will stop the madness, and that goes to:

- https://help.ubuntu.com/community/SSO/SupportPortal

This has left the friendly flow of the Ubuntu Pro dashboard.

Will this happen to customers who might be able to use the Ubuntu Pro dashboard to see their tokens but not interact with the support portal?

Thanks

---
*Reported from: https://ubuntu.com/pro/dashboard*

**Comment by anthonydillon** [comment]
@albertkol @jpmartinspt

**Comment by anthonydillon** [comment]
Worked fine for me. I believe it uses SSO.

**Comment by jpmartinspt** [comment]
@setharnold do you still get stuck in the redirect loop? does it also happen when you access the portal directly?

**Comment by setharnold** [comment]
Yeah, I can reproduce the redirect loop. Trying to load https://portal.support.canonical.com also leads to a redirect loop.

Thanks

**Comment by albertkol** [comment]
Support Portal did indeed have an endless login loop. It has been fixed. This issue should not exist anymore.

**Comment by setharnold** [comment]
I was able to trigger an endless loop by loading https://portal.support.canonical.com/ -- is the solution to use https://support-portal.canonical.com/dashboard instead?

Thanks
