### ISSUE TITLE
Discrepancy of kernel lifecycle between `about/release-cycle` and `kernel/lifecycle`

### ISSUE THREAD

**Issue by nobuto-m** [canonical/ubuntu.com#13030]
We have two places mentioning the kernel lifecycle on Ubuntu. The information on those two pages should be identical.

### https://ubuntu.com/about/release-cycle#ubuntu-kernel-release-cycle

The diagram says 5.19 kernel on Ubuntu 22.04 LTS is supported for **more** than a year.

![Screenshot from 2023-07-10 16-00-14](https://github.com/canonical/ubuntu.com/assets/4356209/7bd340a9-0ceb-45de-885a-50f9ab8116b7)

### https://ubuntu.com/kernel/lifecycle

The diagram says 5.19 kernel on Ubuntu 22.04 LTS is supported for **less** than a year.

![Screenshot from 2023-07-10 15-59-53](https://github.com/canonical/ubuntu.com/assets/4356209/00580c72-1c93-4ef5-a76d-dd45bfd133e9)

---
*Reported from: https://ubuntu.com/about/release-cycle

**Comment by ksacilotto** [comment]
The top graph is indeed incorrect. The support for interim release kernels (e.g. 5.19) is 9 months in their origin series and 6 months as the HWE kernels for the point releases, so it should be the same as the image on the bottom.
We the Kernel Team are not aware from where that information in the top graph is gathered, we have already raised this issue with PM but this is still to be fixed.
