### ISSUE TITLE
Ubuntu Core 22 arm64 raspi img - Wrong SHA526 checksum

### ISSUE THREAD

**Issue by lucapalano** [canonical/ubuntu.com#13038]
The download link refers to https://cdimage.ubuntu.com/ubuntu-core/22/stable/current/ubuntu-core-22-arm64+raspi.img.xz

The SHA256 checksum reported in the "verify your download" view is wrong:
`echo "374697bd7324f10ff3c00007b75ca42885aff161cbddb63b1d14bc1551e69ce2 *ubuntu-core-22-arm64+raspi.img.xz" | shasum -a 256 --check`

It must be:
`echo "4ee6c389c09ccea7728c34c525c57e14d2f15e15a8d44d0f2894efa1abb13ea0 *ubuntu-core-22-arm64+raspi.img.xz" | shasum -a 256 --check`

Best regards,
Luca

---
*Reported from: https://ubuntu.com/download/raspberry-pi/thank-you?version=22

**Comment by carkod** [comment]
@egezeytun any idea who is the owner of https://ubuntu.com/download/raspberry-pi? This may need a copy update.

**Comment by immortalcodes** [comment]
Thanks for reporting this, the new-version has been updated on the website.
