### ISSUE TITLE
Issue with installation of Real-time kernel 

### ISSUE THREAD

**Issue by saivojjala** [canonical/ubuntu.com#13075]
## Summary
The PREEMPT RT real-time kernel installation for Ubuntu 20.04 LTS throws an error during reboot when installed on NUC11BTMi7. The version installed is 5.9.1-rt20.

## Process
The installation process followed is the same as the procedure given on https://frankaemika.github.io/docs/installation_linux.html#setting-up-the-real-time-kernel

## Current and expected result
When installed on NUC11BTMi7, the error message shown in the below screenshot appears on a loop while booting. However, the same installation worked on my personal laptop (Dell Inspiron 5491). 

## Screenshot
![Issue](https://github.com/canonical/ubuntu.com/assets/75254081/32535ae4-793e-485d-8d66-aace01f4f5d8)

What could be the issue?

**Comment by EdoardoBarbieriCanonical** [comment]
Hi @saivojjala  Please use Ubuntu 22.04 LTS with kernel version 5.15, as [real-time](https://ubuntu.com/blog/real-time-ubuntu-is-now-generally-available) Ubuntu is a [Jammy Jellyfish](https://releases.ubuntu.com/22.04/) 22.04 LTS kernel with the [5.15-rt patch set](https://cdn.kernel.org/pub/linux/kernel/projects/rt/5.15/) integrated. For further details, please see [here](https://ubuntu.com/blog/real-time-kernel-technical).

**Comment by saivojjala** [comment]
Hi @EdoardoBarbieriCanonical, I cannot use Ubuntu 22.04 LTS for my particular application as ROS1 Noetic is not compatible with it, and ROS2 does not yet have complete support for some of the frameworks I will be using.  Therefore, I require Ubuntu 20.04 LTS.

**Comment by josephtsalisbury** [comment]
@saivojjala It is probably best to file a bug against the real-time kernel in Launchpad.  That can be done here:
https://bugs.launchpad.net/ubuntu-realtime/+filebug

**Comment by saivojjala** [comment]
@josephtsalisbury I will do that. Thanks !
