### ISSUE TITLE
https://ubuntu.com/#community CONNECT Blog Weekly Newsletter Discourse Planet Teams LoCos Lists IRC should be on top not bottom

### ISSUE THREAD

**Issue by kangarooo** [canonical/ubuntu.com#13087]
https://ubuntu.com/#community CONNECT Blog Weekly Newsletter Discourse Planet Teams LoCos Lists IRC should be on top not bottom
so people could see there is teams other then loco also
![image](https://github.com/canonical/ubuntu.com/assets/73187/79a78f93-33af-4ee9-96c7-94fca5107674)

---
*Reported from: https://ubuntu.com/*

**Comment by fitojb** [comment]
This navigation dropdown is going away in a (long-delayed) redesign; see PR #12939

**Comment by britneywwc** [comment]
Thank you for raising an issue. Closing this issue as it has already been addressed with the new mega navigation redesign. Please check again on your device and feel free to reopen if needed.
