### ISSUE TITLE
engage page dropdown filter seems broken

### ISSUE THREAD

**Issue by grobbie** [canonical/ubuntu.com#13090]
## Summary

filtering on "Webinar" gives no results. From @caldav:
> it seems to be taking raw content type strings from discourse engage pages and 1) not doing any case sanitation (so, Webinar vs webinar, but both render Webinar, therefore 2 Webinar entries in the drop down 2) displays a category in the drop down even when the underlying engage page is marked as inactive, therefore hidden in the UI, resulting in an empty list.

And from @carkod:
> The way to "bullet-proof" it would be to create a fixed list of engage pages types. Because we can't control the engage page types authors use.

## Process

* go to ubuntu.com/engage
* select "Webinar' in the drop down
*  see a "no results" page

## Current and expected result

* I would expect to see a filtered list of webinars

## Screenshot
![image](https://github.com/canonical/ubuntu.com/assets/3254480/cf57ffb4-6985-44c6-b06d-f0a37aac71c9)

**Comment by Harsh0707005** [comment]
The issue has been resolved.
Close the issue
