### ISSUE TITLE
page https://ubuntu.com/kernel/lifecycle

### ISSUE THREAD

**Issue by guiverc** [canonical/ubuntu.com#13092]
it reports 5.19 as the kernel of 22.04.3  (that should be 6.2 kernel)

it doesn't mention 22.04.2 (which did use the 5.19 kernel)

---
*Reported from: https://ubuntu.com/kernel/lifecycle*

**Comment by immortalcodes** [comment]
The page has been updated. I am closing this issue but if you still feel that the information here needs amends feel free to re-open this issue.
Thanks @guiverc
