### ISSUE TITLE
Pressing "Enter" after filling out a field doesn't start the search

### ISSUE THREAD

**Issue by axinojolais** [canonical/ubuntu.com#13093]
Hi,

On https://ubuntu.com/security/cves, if I put some text in the `CVE ID or description contains` text input and press `Enter`, the search does not start. Instead, I need to click on the `Search` button.

I would expect pressing `Enter` would start the search.

Thanks

---
*Reported from: https://ubuntu.com/security/cves

**Comment by Harsh0707005** [comment]
Please assign me #13093

**Comment by juanruitina** [comment]
Duplicate of #12478

**Comment by mtruj013** [comment]
Fixed in https://github.com/canonical/ubuntu.com/pull/13188, closing
