### ISSUE TITLE
ubuntu.com meta /sitemap.xml is missing /robotics/docs/sitemap.xml

### ISSUE THREAD

**Issue by caldav** [canonical/ubuntu.com#13091]
Our meta [sitemap.xml](https://ubuntu.com/sitemap.xml) is missing a link to our [robotics doc stack sitemap](https://ubuntu.com/robotics/docs/sitemap.xml). Adding it would speed up getting new pages indexed.

**Comment by carkod** [comment]
This seems to be fixed.
