### ISSUE TITLE
Login loop in Ubuntu 23.04

### ISSUE THREAD

**Issue by Nirmith-M-R** [canonical/ubuntu.com#13102]
I have been using Ubuntu from many days, now I am facing an issue where the login page comes every time, even though I enter correct password. I have also tried all the solutions in internet for this problem , but I am unable to solve it. Please help to come out of this login loop problem.

There is no .Xauthority file also in it.
---
*Reported from: https://ubuntu.com/download/desktop*

**Comment by Harsh0707005** [comment]
This issue has been resolved
Kindly Close this issue

**Comment by elamandeep** [comment]
> This issue has been resolved
> Kindly Close this issue
I'm too facing same issue in ubuntu 22.04.6. This issue doesn't seems to be fixed.

**Comment by akbarkz** [comment]
I'm closing this issue since this repository is about `ubuntu.com` webpage, not the operating system itself. If the problem with logging in to your OS still remains, please create an issue in the corresponding repository.
