### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by lgeorgiev** [canonical/ubuntu.com#13114]
Hello, 
Images are missing on the tutorial pages.

Example: https://ubuntu.com/tutorials/install-home-assistant-on-ubuntu-core-and-create-a-motion-activated-light-automation#6-creating-the-automation-in-home-assistant

![Install-Home-Assistant-on-Ubuntu-Core-and-create-a-motion-activated-light-automation-Ubuntu](https://github.com/canonical/ubuntu.com/assets/1999598/3f026831-6806-4ef9-88a0-596393cc623a)

**Comment by carkod** [comment]
Thanks, its fixed. https://ubuntu.com/tutorials/install-home-assistant-on-ubuntu-core-and-create-a-motion-activated-light-automation
