### ISSUE TITLE
URL to download bz2 file doesnt work

### ISSUE THREAD

**Issue by markatdxb** [canonical/ubuntu.com#13126]
URL is not working 
https://security-metadata.canonical.com/oval/com.ubuntu.$(lsb_release -cs).usn.oval.xml.bz2
---
*Reported from: https://ubuntu.com/security/oval*

**Comment by Harsh0707005** [comment]
It is working, make sure you are on Ubuntu OS
This issue has been resolved.
Kindly Close this issue
