### ISSUE TITLE
Password appeared in data leak, however unable to change password.

### ISSUE THREAD

**Issue by josephlu0717** [canonical/ubuntu.com#13159]
Also I see there are 5 machines used on my free plan, however I haven't even deployed a single ubuntu distro yet. Might be the hacker? Please remove from my profile.

Also I have no access to the users on my profile? 

*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

[Please describe the issue.]

## Process

[List the steps to replicate the issue.]

## Current and expected result

[Describe what happened and what you expected.]

## Screenshot

[If relevant, please include a screenshot.]

## Browser details

[Please tell us what browser(s) you used when you encountered this bug and any other information that might be relevant, like if you block javascript, run an ad blocker, etc...]

**Comment by anthonydillon** [comment]
Hi @josephlu0717, which identity system are you talking about?

**Comment by josephlu0717** [comment]
Oh wow, apologies I didn't know There was this in my GitHub app on an iPhone 12 Pro Max. I've been responding to Shane via email (2037142@bugs.launchpad.net), but it seems he stopped responding.

I'm not sure what you mean by identity provider. Happy to provide pictures for the below, if you could provide me an email address. Story goes:

- In the built in iPhone's password manager, it says my ubuntu account has appeared in a data leak.

- When logging on via safari (ubuntu.com) -> ubuntu pro -> your subscriptions (for personal use):
1. It says I have 5 active machines: I did install ubuntu before, but don't have it installed anymore so I'm not sure which 5 machines it's referring to?

Note: I'm trying to learn development, so was testing some things out. Might have done errors along the way but I'm not sure. If your team needs any further information please let me know.

2. I also can't access "account users" tab, says access forbidden, which is weird. I should be the only user of my account.

3. I actually can't find where I got to the changing password page, but I remember it asking me to enter a verification code or something. I'm not sure where to get this - I don't have any ubuntu installed anymore lol...

Let me know if there's anything you require.

P.S. my brand new computer is acting very strangely (booting from windows USB and examining directory from command prompt, C and D drives have been swapped around, and there's forever 35GB or so sitting in RAM (the page.sys and something.sys file), plus UEFI only provides XMP profile for RAM even though my CPU is AMD), and I'm not sure if this has anything to do with it. If you know of anything please let me know.

Thanks! Happy to provide any information you might require.

**Comment by immortalcodes** [comment]
Hey @josephlu0717 ,
What I can understand from the above information is that you used a weak password over Ubuntu Pro page which was flagged by IOS, I would suggest login into your account, go to https://ubuntu.com/pro/dashboard.
You will see all the information you need there.

Also by 5 machines it means that you can use Ubuntu pro on up to 5 machines for free not necessarily you are already using actual 5 machines and hence you don't see anything on dashboard. 
If you still face issues I will suggest contacting to Ubuntu Pro support team from here
![image](https://github.com/user-attachments/assets/87692c47-e9ae-4587-a612-7c5026b2402b)
https://ubuntu.com/support/contact-us?product=contextual-footer-ua
