### ISSUE TITLE
Unqualified commitment to 10 years of support

### ISSUE THREAD

**Issue by xnox** [canonical/ubuntu.com#13199]
> 10 years of long term support and security updates
*Reported from: https://ubuntu.com/internet-of-things*

> 10 year security update commitment
That’s a decade of sleeping soundly
Ubuntu Core gets 10 years of Canonical maintenance. Your smallest devices are now as secure as your servers. No other embedded Linux comes close.
*Reported from: https://ubuntu.com/core*

Is all true, but it is subject to restrictions of Pro and ESM:

https://ubuntu.com/pro
https://ubuntu.com/security/esm

Specifically requirement to have Pro subscription to access Universe coverage (and thus build snaps with Pro universe). And requirement to meet required architectures for ESM support (and thus gain the 10 year security update commitment).

Currently, together with the bug in https://github.com/canonical/ubuntu.com/issues/13198 results in potential misrepresentation, and confusion.

**Comment by immortalcodes** [comment]
@xnox,
Could you please update if the current information lacks the appropriate information on the indicated page.
I have also tagged you on the other issue that you have linked here.
Thanks for being part of community.

**Comment by immortalcodes** [comment]
The page has been updated since you reported this issue and with no further context on this I will have to close this issue but please feel free to revisit this and re-open this issue if you feel that this needs more information/work.
Thanks

**Comment by xnox** [comment]
sure, but do note that both pages are yet again out of date. https://ubuntu.com/pro & https://ubuntu.com/security/esm all continue to reference 10 years; yet 12 years is available for certain subscribers and is mentioned on https://ubuntu.com/core. Hence inconsistent. Also note it has never been clarified who has entitlement for what and what is covered for whom or not. But they may depend on internal-only details of entitlements in the snap-store. Contact ESM & Core PMs to clarify to ensure all pages have consistent 10->12 year updates, that are in agreement across various offerings and web pages.
