### ISSUE TITLE
ESM service description has evolved in time, and no longer is accurate

### ISSUE THREAD

**Issue by xnox** [canonical/ubuntu.com#13198]
In Ubuntu Pro description
Valid since 05 October 2022

1.Expanded Security Maintenance (ESM)
1.4 ESM does not provide:
1.4.1. Coverage for architectures other than 64-bit x86 AMD/Intel for Ubuntu releases 14.04 LTS, 16.04 LTS

In inaccurate and technically incorrect. There are dozens of architectures out there, none of which are enabled by Ubuntu. And it seems to incorrectly imply a possibly to interpret these terms incorrectly.

The https://ubuntu.com/security/esm has "what's covered" and is a lot more clear and correct.
* Ubuntu 14.04 LTS - amd64
* Ubuntu 16.04 LTS - amd64, s390x
* Ubuntu 18.04 LTS - amd64, arm64, s390x, ppc64el
* Ubuntu 20.04 LTS - amd64, arm64, s390x, ppc64el, RISC-V
* Ubuntu 22.04 LTS - amd64, arm64, s390x, ppc64el, RISC-V
Which is not any more adequately described by 1.4.1 item which cannot ever stand the test of time.

Requests:
1. Please remove 1.4.1 item.
2. Please add a new item before 1.4 (to drop double negative), referencing what is covered: `Coverage is available on Ubuntu releases and specific architectures as specified on ubuntu.com/security/esm"`

Because list of architectures and releases is ever changing, whilst the terms of service remain the same. This has a better chance of standing the test of time.

---
*Reported from: https://ubuntu.com/legal/ubuntu-pro-description*

**Comment by immortalcodes** [comment]
Hey @xnox ,
The doc seems to be updated now, could you please verify if the information regarding support for the architecture still seems inadequate or incomplete.
Please update with your findings in both these issues.
Thanks for coming up with this point.

**Comment by immortalcodes** [comment]
The page has been updated since you reported this issue and with no further context on this I will have to close this issue but please feel free to revisit this and re-open this issue if you feel that this needs more information/work.
Thanks

**Comment by xnox** [comment]
On https://ubuntu.com/security/esm

24.04 LTS is missing

12 years mentions are missing
