### ISSUE TITLE
update, new  kernel >.26 high cpu usage

### ISSUE THREAD

**Issue by Red-Owl** [canonical/ubuntu.com#13207]
process _not visible_ in system monitor (module ?)
![6 2 0 26](https://github.com/canonical/ubuntu.com/assets/36891854/0500e5ad-65df-4c3e-a56a-ebfdcdd92d4c)
![6 2 0 33](https://github.com/canonical/ubuntu.com/assets/36891854/93fb88a5-cad1-4257-98c2-00097d15040b)
i have create a screen of this problem.
i use a official kernel and nvidia propietary or open driver
solution ?

**Comment by britneywwc** [comment]
Thanks for flagging, this repository is responsible for the ubuntu.com website. I believe your issue should be filed [here](https://bugs.launchpad.net/ubuntu/).
