### ISSUE TITLE
Add LXD release cycle tab/table 

### ISSUE THREAD

**Issue by 106106** [canonical/ubuntu.com#13206]
The release cycle and supported LTS versions of LXD with time frames for supportability would help dispel confusion around what versions of LXD are currently supported.

---
*Reported from: https://ubuntu.com/about/release-cycle*

**Comment by immortalcodes** [comment]
Hey, we generally keep release cycles on individual sites for our various products. For LXD you can find more information about the release cycles here https://documentation.ubuntu.com/lxd/en/latest/support.
I hope this answers your query, I am closing this issue but please feel free to re-open this issue if you feel you need more information on this.
Thanks for reporting.
