### ISSUE TITLE
Getting started not found

### ISSUE THREAD

**Issue by jardon** [canonical/ubuntu.com#13225]
Howdy, the following snippet has an invalid link.

To learn more about Juju and to bootstrap a Juju controller, check out their [getting started](https://jaas.ai/docs/getting-started-with-juju) page.

---
*Reported from: https://ubuntu.com/landscape/docs/juju-installation*

**Comment by akbarkz** [comment]
@jardon where is this wrong link located exactly, can you please clarify?

**Comment by angelpilled** [comment]
This looks like it has already been fixed
