### ISSUE TITLE
Suggestion - add pricing for MAAS install

### ISSUE THREAD

**Issue by camille-rodriguez** [canonical/ubuntu.com#13234]
Hi, 
 
I like that the different packages are all in one webpage. Could we add the details of the MAAS package (HAP) as well ?
Please reach out to me for details, happy to discuss. 

---
*Reported from: https://ubuntu.com/pricing/consulting*

**Comment by akbarkz** [comment]
@camille-rodriguez I think this should be discussed with the product manager. We are happy to help as soon as we have clear requirements from the PM.

**Comment by camille-rodriguez** [comment]
There isn't a PM for MAAS at the moment. I'll send this to Cedric

**Comment by akbarkz** [comment]
Thanks, Camille! If you don't mind, I'll close this GitHub issue, since if the request comes from PM office, they will create a Jira task for us.
