### ISSUE TITLE
Broken Link to Raspberry Pi Ubuntu Core download

### ISSUE THREAD

**Issue by dschoeck** [canonical/ubuntu.com#13242]
Broken link to Ubuntu Core on page:
https://ubuntu.com/download/raspberry-pi
Link goes to:
https://cdimage.ubuntu.com/ubuntu-core/23/stable/current/ubuntu-core-22-arm64+raspi.img.xz
but should go to:
https://cdimage.ubuntu.com/ubuntu-core/22/stable/current/ubuntu-core-22-arm64+raspi.img.xz

---
*Reported from: https://ubuntu.com/raspberry-pi*

**Comment by mtruj013** [comment]
@juanruitina tried to go through the doc on this page, but it doesn't look like we're defining the links there. Would you know who to confirm this with?
