### ISSUE TITLE
Download-URL for 23.10 image returns 404

### ISSUE THREAD

**Issue by Cumbiambero** [canonical/ubuntu.com#13240]
The https://releases.ubuntu.com/23.10/ubuntu-23.10-desktop-amd64.iso returns Not Found

---
*Reported from: https://ubuntu.com/download/desktop/thank-you?version=23.10

**Comment by anthonydillon** [comment]
Thank you for taking the time to report this issue to us. Ubuntu 23.10 cannot be downloaded right now. We apologize while we work on correcting the issue.

For more details please read: https://discourse.ubuntu.com/t/announcement-ubuntu-desktop-23-10-release-image-is-being-updated-to-resolve-a-malicious-translation-incident/39365
