### ISSUE TITLE
Kubernetes release cycle missing from the k8s docs

### ISSUE THREAD

**Issue by perk** [canonical/ubuntu.com#13252]
It would be good to have the release cycle added to this page, somehewere near the top:
https://ubuntu.com/about/release-cycle#canonical-kubernetes-release-cycle

---
*Reported from: https://ubuntu.com/kubernetes/docs/supported-versions*

**Comment by anthonydillon** [comment]
Could you take a look at this @evilnick please?

**Comment by evilnick** [comment]
Sure, I can make a PR for linking this from the docs.
