### ISSUE TITLE
Side bar items with sub pages are not clickable

### ISSUE THREAD

**Issue by nobuto-m** [canonical/ubuntu.com#13257]
For example in this page:
https://ubuntu.com/ceph/docs

There are many items in the side bar and I expect all items are clickable to take some actions. However, items that have sub items are not clickable except for the `>` icon. It's counterintuitive to me.

[Clicking anywhere in `How-to guides` guide us from `/ceph/docs` to `/ceph/docs/howtos`]
![image](https://github.com/canonical/ubuntu.com/assets/4356209/6265e6a2-9e13-41d6-a806-6d35a400d158)

[Clicking `Install` doesn't expand the sub menu unless the `>` icon is clicked explicitly]
![image](https://github.com/canonical/ubuntu.com/assets/4356209/4a5e47d0-3058-4f5a-8de6-2b862bed1d92)

---
*Reported from: https://ubuntu.com/ceph/docs*

**Comment by Shashankpantiitbhilai** [comment]
please assign it to me

**Comment by nobuto-m** [comment]
A stop gap change has been made on the Discourse content side.
