### ISSUE TITLE
Can't connect to network

### ISSUE THREAD

**Issue by Nikitf777** [canonical/ubuntu.com#13264]
Ubuntu sees wifi networks, but when I trying to connect to them, it looks like wifi rebooting (its label just disappears for a second)
It also can't connect to USB-modem of my smartphone.

Ubuntu 23.10
---
*Reported from: https://ubuntu.com/*

**Comment by LeaDevelop** [comment]
@Nikitf777 _If you have found a bug in the Ubuntu OS itself, please file it [here](https://bugs.launchpad.net/ubuntu/)_.
