### ISSUE TITLE
500 error on engage page

### ISSUE THREAD

**Issue by thisisrichardferreira** [canonical/ubuntu.com#13287]
I'm getting 500 errors on this engage page: sometimes on the page itself, and every time I submit the form and land on the next one — https://ubuntu.com/engage/migrating-from-rhel-centos-to-ubuntu-public-cloud. It was working well when I tested it yesterday.

<img width="1091" alt="Screenshot 2023-10-26 at 15 35 24" src="https://github.com/canonical/ubuntu.com/assets/12816804/f57c33a9-0b3c-4c0e-bc8d-faedf2161fe3">

**Comment by DMaxwell02** [comment]
500: Server error on tuturial page too: https://ubuntu.com/tutorials?q=custom

**Comment by Ankush-Pathak** [comment]
Here too: https://ubuntu.com/security/certifications/docs/usg/cis/compliance

**Comment by BCPayne709** [comment]
I am getting the 500 error on the landing/engage page too

**Comment by anthonydillon** [comment]
All reported pages are back in working order. Thanks for pointing them out to us.
