### ISSUE TITLE
 500: Server error

### ISSUE THREAD

**Issue by ghost** [canonical/ubuntu.com#13295]
HI ,! i clicked on previous on the page and it gave me a 501 error`

**Comment by LeaDevelop** [comment]
Hi, could you share what page you were on please

**Comment by Shaungrimm2** [comment]
Well i was the one that did that from cross jumping in sights well i was in gandi. Net and clicked on a url to git hub and got on the git hub sight link from gandi. Net and i clicked to sign into my account and then I will say it happened.     Ok thanks for your concern

Shaun Grimm

**Comment by akbarkz** [comment]
The user who reported this issue does not exist on GH anymore. Also I didn't understand why is it created on `ubuntu.com` website's repo if the user is talking about `gandi.net`.
