### ISSUE TITLE
Bad link on https://ubuntu.com/server/docs 

### ISSUE THREAD

**Issue by 0x415246** [canonical/ubuntu.com#13294]
Near bottom of the page:  Ubuntu 18.04 LTS (Bionic Beaver): [Web](https://help.ubuntu.com/18.04/serverguide/index.html) and [PDF](https://help.ubuntu.com/18.04/serverguide/serverguide.pdf)

https://help.ubuntu.com/18.04/serverguide/serverguide.pdf  results in 404
---
*Reported from: https://ubuntu.com/server/docs*

**Comment by britneywwc** [comment]
Thanks for flagging @0x415246! I believe the broken link for Ubuntu 18.04 PDF has been fixed now. Closing this issue as resolved.
