### ISSUE TITLE
Password login

### ISSUE THREAD

**Issue by krasyid822** [canonical/ubuntu.com#13291]
Kadang bingung dengan setelan password Ubuntu ini sebagai pengguna baru. Bisakah pengaturan password (lockscreen misalnya) dibuat lebih mudah? Saya bingung ketika mencarinya di pengaturan

**Comment by akbarkz** [comment]
@krasyid822 looks like you have an issue with Ubuntu OS itself. This repo is about `ubuntu.com` website only. If you want to file an issue for Ubuntu OS you can do so [here](https://bugs.launchpad.net/ubuntu/).

**Comment by krasyid822** [comment]
oh okay, sorry. im not known about it. thank you for directing
