### ISSUE TITLE
The ubuntu desktop tutorial page is blank.

### ISSUE THREAD

**Issue by ThomScottW** [canonical/ubuntu.com#13299]
![image](https://github.com/canonical/ubuntu.com/assets/67296714/97a4762f-566c-48f5-a50e-e03b35585288)

The install ubuntu desktop tutorial at https://ubuntu.com/tutorials/install-ubuntu-desktop#1-overview has no content on the page. For more information, I'm using microsoft edge Version 118.0.2088.69 (Official build) (64-bit). The same problem is present on Safari and Google Chrome.

**Comment by anthonydillon** [comment]
This has been resolved and released.
