### ISSUE TITLE
Page is blank

### ISSUE THREAD

**Issue by ts-web** [canonical/ubuntu.com#13306]
https://ubuntu.com/tutorials/install-ubuntu-desktop#3-create-a-bootable-usb-stick

![ubuntu com_tutorials_install-ubuntu-desktop](https://github.com/canonical/ubuntu.com/assets/1311744/e46c8517-5da9-4a29-8380-5cce79c86c5a)

**Comment by guttley** [comment]
Same for me

**Comment by anthonydillon** [comment]
This has been resolved and released.
