### ISSUE TITLE
Page content is not loading - basic command line for beginners 

### ISSUE THREAD

**Issue by 1eighty2** [canonical/ubuntu.com#13308]
When using command line for beginners tutorial it previously worked when I was using edge on Kali Linux. I tried Firefox with same issue and tried using edge on windows with the same outcome.

**Comment by anthonydillon** [comment]
This has been resolved and released.

**Comment by 1eighty2** [comment]
thank you, Anthony!



Adam.



Adam Bell

Security Consultant

Tel :  0191 545 1010
Mob: 07399 433818
DDI:  0191 545 1043

www.cyberwhite.co.uk<http://www.cyberwhite.co.uk/>



I know we all work differently so please, if you are receiving this e-mail outside of your normal working day, please don’t respond until you are back at work.



    ***@***.***

[Diagram  Description automatically generated with low confidence]



CyberWhite is a digital security consultancy achieving great results by doing things differently.
For more information visit www.cyberwhite.co.uk<http://www.cyberwhite.co.uk/>



CyberWhite Limited, trading as CyberWhite, registered in England & Wales, No. 11256903

Registered office: Mulberry House, 3 Defender Court, Sunderland Enterprise Park, Sunderland, SR5 3PE.



PROUD TO BE PART OF THE DEFENDER HOLDINGS GROUP



[signature_1531308123]<http://www.defender-holdings.com/>    [signature_4241114396] <http://www.vipersoft.co.uk/>

Why not help the environment and save a tree – please don't print this email unless you absolutely need to.

This email and any attachments are confidential and intended solely for the use of the individual to whom they are addressed. If you are not the intended recipient or have received this email in error, you may not reproduce, forward, disclose or use any part of it. Please notify the sender if you believe you have received it in error. Any views or opinions expressed are solely those of the author and do not necessarily represent those of CyberWhite. We do not accept legal responsibility for the content of this email or any viruses. No contracts or official orders can be concluded with us by means of email. CyberWhite reserves the right to monitor emails.
You can read our Privacy Policy here<https://www.cyberwhite.co.uk/privacy-policy/>



________________________________
