### ISSUE TITLE
White page on all tutorials

### ISSUE THREAD

**Issue by bogdan-marian** [canonical/ubuntu.com#13304]
Install Ubuntu from the stick is broken. 
https://ubuntu.com/tutorials/install-ubuntu-desktop#3-create-a-bootable-usb-stick
The summary on the left is displayed but no mater to what chapter you navigate you only get a white page. 
The same happens also for "How to write a tutorial" 
https://ubuntu.com/tutorials/guidelines#1-overview

**Comment by anthonydillon** [comment]
This has been resolved and released.
