### ISSUE TITLE
No Instructions

### ISSUE THREAD

**Issue by NathStone** [canonical/ubuntu.com#13314]
On the Install Ubuntu desktop tutorial no instructions appear on any of the sections and it is all left black
![Screenshot 1](https://github.com/canonical/ubuntu.com/assets/148255570/1af36b1a-f102-49b9-8573-76588e72f45d)
![Screenshot 2](https://github.com/canonical/ubuntu.com/assets/148255570/399ea6dd-b604-4484-ac99-6e6597ac9324)

**Comment by anthonydillon** [comment]
This has been resolved and released.
