### ISSUE TITLE
Sign up page doesnt work

### ISSUE THREAD

**Issue by DavidBuch1** [canonical/ubuntu.com#13315]
Trying to sign up for ubuntu pro and the page goes to an error

**Comment by bluecords** [comment]
Also on the login page 500: Server error
Something's gone wrong.

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
https://ubuntu.com/login

**Comment by petesfrench** [comment]
Closing as this should be fixed now, please open a new issue if it occurs again.
