### ISSUE TITLE
Broken link to https://forms.canonical.com/trademark/thanks/

### ISSUE THREAD

**Issue by andrewjamessinclair** [canonical/ubuntu.com#13324]
## Summary

After submitting a form at https://forms.canonical.com/trademarkviolation/, the user is taken to https://forms.canonical.com/trademark/thanks/, which does not seem to exist.

## Process

Fill out the form at https://forms.canonical.com/trademarkviolation/ and submit it.

## Current and expected result

Current result: user is taken to https://forms.canonical.com/trademark/thanks/, which produces the message "Not Found
The requested URL /trademark/thanks/ was not found on this server."

Expected result: user is taken to a page thanking them for submitting the form.

## Browser details

I am using Version 118.0.5993.117 (Official Build) (arm64) on a Mac with no customizations and minimal plugins / extensions (no ad block or anything like that). I don't think this issue depends on the browser though, it's simply a missing page.

**Comment by akbarkz** [comment]
@andrewjamessinclair This repo is for our `ubuntu.com` website, but the issue that you reported is for another repo. I created a similar issue there here: https://github.com/canonical/forms.canonical.com/issues/4
Please track the progress there, and I'm closing this one.
