### ISSUE TITLE
discourse.ubuntu.com - Logo squished on mobile

### ISSUE THREAD

**Issue by dgtlntv** [canonical/ubuntu.com#13320]
## Summary
Probably because of the recent discourse update when you scroll down on a post on discourse.canonical.com the Ubuntu logo is squished.

## Process

1. Be on a mobile breakpoint
2. Go to a post on discourse.canonical.com
3. Scroll down

## Screenshot

https://github.com/canonical/ubuntu.com/assets/68336485/67d3d2ae-3f5b-4f0c-8d95-a298ab2e72aa

## Browser details

Android - Chrome

**Comment by akbarkz** [comment]
The issue has been fixed on discourse.ubuntu.com
