### ISSUE TITLE
BelenaEtcher burns USB drives

### ISSUE THREAD

**Issue by met2tem** [canonical/ubuntu.com#13328]
when attempting to create a bootable USB drive, BelenaEtcher frying my thumb drive.  It was an old thumb drive so I tried again.  It has destroyed two of mine and looking through forum, it is a common problem.  Might want to take the recommendation off of your website until they fix the issue.  It looks poorly on you guys to keep it up.

---
*Reported from: https://ubuntu.com/*

**Comment by fitojb** [comment]
That application has always been fishy. Years ago, [a user suggested] to rewrite that tutorial around usbimager, a truly open-source cross-patform app that has the added benefit of not using the garbage Electron framework.

**Comment by akbarkz** [comment]
@met2tem @fitojb from what I understood, the issue you are reporting is related to Ubuntu OS, not the `ubuntu.com` website for which this repo stands for. If so, please report your issue [here](https://bugs.launchpad.net/ubuntu/) instead.
Please re-open this issue in case it's related to our website.

**Comment by fitojb** [comment]
@akbarkz No, this issue is related to the website; more specifically, to one of the Discourse-generated tutorials. This needs a tutorial rewrite.

**Comment by akbarkz** [comment]
@met2tem @fitojb We deprecated the old tutorial on how to create a bootable USB stick on MacOS in Discourse. Please refer to this up-to-date tutorial instead: https://ubuntu.com/tutorials/install-ubuntu-desktop#3-create-a-bootable-usb-stick

**Comment by immortalcodes** [comment]
Closing this issue since the relevant tutorial has been linked.
Thanks
