### ISSUE TITLE
Grayed out option doesn't look like it was already selected - `Option 1: Manual server installation`

### ISSUE THREAD

**Issue by nobuto-m** [canonical/ubuntu.com#13375]
When opening the server image download page, `Option 1: Manual server installation` is grayed out and unselectable. It actually means that it's already selected as the default option, but the UI doesn't give the impression but looks more of a forbidden option.

![image](https://github.com/canonical/ubuntu.com/assets/4356209/b979f16c-4eff-4d56-b3ae-4dff3bb93ea0)

---
*Reported from: https://ubuntu.com/download/server*

**Comment by fitojb** [comment]
Radio buttons could work here to reduce that ambiguity.
