### ISSUE TITLE
Missing word explaining where the "via" fragment points to

### ISSUE THREAD

**Issue by TerjekiG** [canonical/ubuntu.com#13380]
I believe there is a word missing between "to the" and "however"
The current text on the website says:
"The “via” fragment points to the however when it is missing"
---
*Reported from: https://ubuntu.com/core/docs/networkmanager/routing-tables*

**Comment by degville** [comment]
Thanks for letting me know. I've just fixed this - there were a couple of non-escaped characters hiding `<Gateway>`.

**Comment by TerjekiG** [comment]
Thank you! :)
