### ISSUE TITLE
Lost Video Resolution and Utilities to fix it 22.04.3 LTS

### ISSUE THREAD

**Issue by Gillicutti** [canonical/ubuntu.com#13388]
Hi.

So I turn on my computer after an update that froze half way through (and for 3 hours) that once interrupted and rerun again with Software Update gave me "partial update" message explaining there are files it can't update. Never seen that before and assumed it was because some files were updated but, as you read on, it looks like the updater, whatever update filters / parameters it has found reason to disqualify my Xubuntu from receiving the full update. See to turn off the computer thinking all is fine to then turn it on the next day and discover the display with a message about an unsupported mode floating around on it suggests the update was bad.

I move the dp cord to another port on my card and *presto* display but grainy.

Check displays and see it booted at "60 hz".  I immediately click this pulldown to reset it to 240 hz. Nope. only option for my 1920 x 1080 on my Acer 27" display is 144 hz.

I scour the web for a fix, learn I can use xandr and cvt to get the 240 hz back (which I shouldn't have to do since the update should have been a full update since I installed the Ubuntu 22.04 LTS right? Not sure so have to ask), however xandr isn't found when I type the commands to use it in terminal.

So I search the web to learn xandr is in deb x11-server-utils. I do the sudo thing to install that and get this message "The following package was automatically installed and is no longer required: libwmf0.2-7" (which doesn't make any sense to me). And I still can't execute xandr. It is still not found, not installed. Clarity or a patch to fix what happened, soon please?

I also looked in the Synaptic File Manager, searched "xandr" and I get a Lisp utility library called "alexandria" that is found, not the xandr I need to fix this video issue (60hz destroys my old eyes in minutes on the computer, 240 hz is truly necessary for me to have any useful time on the computer).

I left Windows because Microsoft would do stuff like this without caring at all about the result. Please fix this, or if someone has a suggestion I am all ears. I do not have the whole separate partitions of Linux and Home since I didn't install it that way and am terrified (due to Windows negative outcome result conditioning) to change it now. I mean every time I restart the computer the display is 60 hz again and I have to manually change it to 144. What happened in that last update that messed things up so much or am I one of very few who this last patch negatively impacted? All I can really say as not even a Linux novice is: "HELP!"

Thank you for your time and hope this is fixed soon.

**Comment by akbarkz** [comment]
@Gillicutti if you are reporting an issue related to Ubuntu OS please do it [here](https://bugs.launchpad.net/ubuntu/) instead. This is a repository for our `ubuntu.com` website.
