### ISSUE TITLE
broken image  on ubunt.com

### ISSUE THREAD

**Issue by Decode1415** [canonical/ubuntu.com#13417]
there is a broken link image at : https://ubuntu.com/tutorials/how-to-run-ubuntu-desktop-on-a-virtual-machine-using-virtualbox#1-overview

**Comment by Piyush-Bhor** [comment]
Hi @Decode1415, I would like to work on this issue! I've started looking into it and plan to submit a fix. I'll keep you updated on the progress.

**Comment by carkod** [comment]
Thanks @Decode1415 for reporting this. Can you go the link below "Suggest changes" and report this issue to the discourse topic OP.

@Piyush-Bhor thanks for offering, however this content comes from Discourse, therefore OP will fix it.

**Comment by carkod** [comment]
I had another look at the page, looks like the images are fixed? If you still see any, follow above instructions. Thanks.
