### ISSUE TITLE
Command line tutorial: Use of cat and pipe is an anti-pattern

### ISSUE THREAD

**Issue by lechten** [canonical/ubuntu.com#13416]
In the [command line tutorial](https://ubuntu.com/tutorials/command-line-for-beginners#6-a-bit-of-plumbing) you suggest pipelines of the form `cat file | ...`, which I teach as anti-pattern. Why use `cat`? The subsequent stage can receive stdin via `<`, avoiding the need for a superfluous `cat` process.

**Comment by britneywwc** [comment]
Thanks for the feedback, you can leave a comment on the tutorial Discourse post [here](https://discourse.ubuntu.com/t/the-linux-command-line-for-beginners/14304/17) to discuss the use of certain CLI patterns.
