### ISSUE TITLE
Images missing from "try ubuntu before you install" tutorial

### ISSUE THREAD

**Issue by wnim** [canonical/ubuntu.com#13436]
https://ubuntu.com/tutorials/try-ubuntu-before-you-install#5-enjoy-ubuntu

In steps 1, 2, 4, and 5 it just says "screenshot" instead of showing a screenshot.

Cheers

**Comment by carkod** [comment]
Triaged ticket https://warthogs.atlassian.net/browse/WD-8068

**Comment by mtruj013** [comment]
Related: https://warthogs.atlassian.net/browse/WD-8619, https://github.com/canonical/ubuntu.com/issues/13528

**Comment by akbarkz** [comment]
fixed
