### ISSUE TITLE
Variable name mismatch in Landscape installation instructions

### ISSUE THREAD

**Issue by roskatom** [canonical/ubuntu.com#13444]
There's a variable naming inconsistency in the [Landscape installation guide](https://ubuntu.com/landscape/install) at step 1.2.  The guide initially sets `HOSTNAME` but then references `$HOST_NAME` in the `FQDN` assignment. This inconsistency could potentially disrupt subsequent installation steps.

![image](https://github.com/canonical/ubuntu.com/assets/136211052/81cdfca1-544b-4552-9149-8f88ea3dcac3)

Additionally, the instruction 'Replace landscape.yourdomain.com' might be misinterpreted as an explicit instruction. It might be worth rephrasing it to something like this for clarity: 'Replace 'landscape' and 'yourdomain.com' with the actual hostname and domain name of your server to create the FQDN variable.'

---
*Reported from: https://ubuntu.com/landscape/install*

**Comment by rajannpatel** [comment]
> There's a variable naming inconsistency in the [Landscape installation guide](https://ubuntu.com/landscape/install) at step 1.2. The guide initially sets `HOSTNAME` but then references `$HOST_NAME` in the `FQDN` assignment. This inconsistency could potentially disrupt subsequent installation steps.
> 
> ![image](https://private-user-images.githubusercontent.com/136211052/295187484-81cdfca1-544b-4552-9149-8f88ea3dcac3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMjg2NzUsIm5iZiI6MTcwOTEyODM3NSwicGF0aCI6Ii8xMzYyMTEwNTIvMjk1MTg3NDg0LTgxY2RmY2ExLTU0NGItNDU1Mi05MTQ5LThmODhlYTNkY2FjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQxMzUyNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmI2NDk1YTVjZjU4ODdhY2U4YTcyNzA4ZjI2NzkxYWVhODI0NTZlZmVjNmM5YWE0ZjViMmQwY2Y5ZTI1NDkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uqQdKQK2St581KwmdzG60XP0izosiDVsvefBOY0XaoY)
> 
> Additionally, the instruction 'Replace landscape.yourdomain.com' might be misinterpreted as an explicit instruction. It might be worth rephrasing it to something like this for clarity: 'Replace 'landscape' and 'yourdomain.com' with the actual hostname and domain name of your server to create the FQDN variable.'
> 
> _Reported from: https://ubuntu.com/landscape/install_

The feedback to replace landscape.yourdomain.com is well thought out. I have taken this into consideration and made appropriate changes in the copydoc. I have also moved completely away from using the HOST_NAME variable, and instead consume `hostname --domain` and `hostname --long` outputs.
