### ISSUE TITLE
Problem installing Ubuntu Pro

### ISSUE THREAD

**Issue by hectordavie** [canonical/ubuntu.com#13459]
The Software Updater yesterday and today instructed me to install Ubuntu Pro.
While doing this, I erroneously asked to install Landscape (I do not know what this is).
I pressed the back arrow on the browser (Firefox) and it led to this error report.

**Comment by britneywwc** [comment]
Thanks for filing an issue @hectordavie. This repository is for the ubuntu.com website, not the Ubuntu OS. This issue is related to Ubuntu OS thus it would be better for you to file an issue [here](https://bugs.launchpad.net/ubuntu/).
