### ISSUE TITLE
Pages Are Outdated

### ISSUE THREAD

**Issue by Mafoelffen1** [canonical/ubuntu.com#13465]
Any way that these pages can be updated to reflect Linux kernel 6.5.0-X-generic series kernels in linux-generic-hwe-22.04 as related to LTS 22.04.3 for these two web pages? 6.5.0-14 was release last week into Jammy.

This is related to this LaunchPad Question: https://answers.launchpad.net/ubuntu/+question/708951 which I need to report the LTS kernel lifecycle to upstream Intel Graphics Support for driver issues...
---
*Reported from: https://ubuntu.com/kernel/lifecycle*
*Reported from: https://ubuntu.com/about/release-cycle#ubuntu-kernel-release-cycle*

**Comment by carkod** [comment]
This may be a question for our product manager Eduardo. I'll see if I can reach out to him.

**Comment by lizzochek** [comment]
Hello @Mafoelffen1 I believe the page has been updated. If you believe it is not what you meant, please reopen the issue.
