### ISSUE TITLE
Hyperlink for MacOS doesn't work

### ISSUE THREAD

**Issue by sahit999** [canonical/ubuntu.com#13485]
The hyperlink that leads to the instructions on how to create a bootable disk for MacOS does not lead to a website. Please fix this. Would help a lot of home hobbyists.

**Comment by mtruj013** [comment]
Hi @sahit999, could you share the url where you found the broken link please? Thanks

**Comment by sahit999** [comment]
Hi, On this page (https://ubuntu.com/tutorials/create-a-usb-stick-on-ubuntu#1-overview) there is a hyperlink that for Mac OS instructions that doesn’t work.  This is the link for the hyperlink: https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-macos?_gl=1*r1px7*_gcl_au*MTQ4MzkyNzc3NS4xNzA1NzE2OTQy&_ga=2.40667109.652156518.1706036947-1615627299.1705171340  From: MariaPaula Trujillo ***@***.***>Date: Tuesday, January 23, 2024 at 9:55 AMTo: canonical/ubuntu.com ***@***.***>Cc: sahit999 ***@***.***>, Mention ***@***.***>Subject: Re: [canonical/ubuntu.com] Hyperlink for MacOS doesn't work (Issue #13485)Hi @sahit999, could you share the url where you found the broken link please? Thanks—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by mtruj013** [comment]
@carkod it looks like [this](https://discourse.ubuntu.com/t/create-a-bootable-usb-stick-on-macos/14016) is the tutorial this link is supposed to route to but for some reason it 404s on u.com. Could you take a look? I might be missing something obvious

**Comment by carkod** [comment]
> @carkod it looks like [this](https://discourse.ubuntu.com/t/create-a-bootable-usb-stick-on-macos/14016) is the tutorial this link is supposed to route to but for some reason it 404s on u.com. Could you take a look? I might be missing something obvious

No idea, but it looks like that's it. We can create a redirect.

**Comment by carkod** [comment]
Fixed https://ubuntu.com/tutorials/create-a-usb-stick-on-ubuntu#1-overview
