### ISSUE TITLE
Impossible to use server download

### ISSUE THREAD

**Issue by WeStartThen** [canonical/ubuntu.com#13505]
One would think of all people to do a iso downloads page correctly and not frustrate your user with stupid garbage, you would be the ones.. but no.

The link for downloading your server .iso is unusable in a text based context.  Any kind of sys admin is gonna pull their hair out at this.  I just want a stupid dumb link I can copy and paste into whatever machine wherever I need to actually download the ISO to.  Whatever you got going on now doesn't allow this.

Ope.. found it on the second page after you click the link and it tries to automatically download..but I'm still gonna enter the ticket and waste your time for wasting my time and not just presenting a link I can copy paste on the main downloads page.

---
*Reported from: https://ubuntu.com/download/server

**Comment by mtruj013** [comment]
Thank you for the feedback, we will discuss further improvements with the team

jira ticket: https://warthogs.atlassian.net/browse/WD-8519

**Comment by britneywwc** [comment]
Closing this issue as it violates the [Ubuntu Code of Conduct](https://ubuntu.com/community/ethos/code-of-conduct).
