### ISSUE TITLE
Unable to use Landscape API, no Login to Ubuntu Pro/Landscape/Support Portal

### ISSUE THREAD

**Issue by simulans** [canonical/ubuntu.com#13538]
Both https://landscape.canonical.com and Landscape API calls result in http 503
https://ubuntu.com/ is returning 500
Cannot login to Canonical support to report issue due to the above

**Comment by InklingGirl** [comment]
Likewise, they must fix their servers ASAP.

**Comment by carkod** [comment]
We had some downtime in our nodes, I believe it should be working now.
