### ISSUE TITLE
500: Server error on Website

### ISSUE THREAD

**Issue by InklingGirl** [canonical/ubuntu.com#13539]
`500: Server error` when I try to sign in. _Ubuntu Pro_ is also not working & unable to be re-enabled right now.

**Comment by Hamberfim** [comment]
Same issue.
Ubuntu Pro/Live patch is not work and unable to sign in at: 
https://ubuntu.com/login <- results in a 500: server error

**Comment by RZed01** [comment]
Login is now back up, confirmed ESM updates now functional

**Comment by InklingGirl** [comment]
> Login is now back up, confirmed ESM updates now functional

So I saw, thank goodness.
