### ISSUE TITLE
Ubuntu Pro not loading

### ISSUE THREAD

**Issue by botolphe** [canonical/ubuntu.com#13536]
When going to ubuntu.com and logging in, I try to get to the Pro Dashboard and the server encounters an error. I have attempted this on multiple browsers as well as multiple devices and the error is the same across the board. 500 Server error

**Comment by DocTator2281** [comment]
same here. I think the site may be down for the count.

**Comment by botolphe** [comment]
Seems to be back up now... Maybe.

**Comment by RZed01** [comment]
ESM updates are now operational again.

**Comment by botolphe** [comment]
Everything is working for sure from my end!

**Comment by DocTator2281** [comment]
all is well here too. yayyy
