### ISSUE TITLE
Update the engage page logo

### ISSUE THREAD

**Issue by anthonydillon** [canonical/ubuntu.com#13554]
## Summary

The standard engage page template has an out-of-date Ubuntu logo in the top left. Can you replace that with the latest tab version?

## Process

1. Go to https://ubuntu.com/engage/arx-fit-on-ubuntu-core
2. See the Ubuntu logo is old

## Current and expected result

The logo should be the tabbed logo with maybe "Canonical Ubuntu" so it matches the logo on the homepage.
![image](https://github.com/canonical/ubuntu.com/assets/1413534/1cb8fc0d-05ef-4f2c-a4da-e68cecd9bda3)

## Screenshot

![image](https://github.com/canonical/ubuntu.com/assets/1413534/f78d5b45-1dda-4f5e-bc2d-1680122acf2c)

**Comment by carkod** [comment]
There's already a task scheduled to not just update the logo but revampt the entire page with new styles. https://warthogs.atlassian.net/browse/WD-7146

**Comment by anthonydillon** [comment]
Can we separate these tasks as incorrect branding is important to address quickly and I don't want to hold off for a large project please?

**Comment by britneywwc** [comment]
Marking this issue as resolved. The engage pages are now using the new Canonical Ubuntu logos.
<img width="216" alt="Screenshot 2024-07-22 at 3 45 40 PM" src="https://github.com/user-attachments/assets/a90d07e5-61c6-4282-b34d-6724a0cb02f1">
