### ISSUE TITLE
certification site doesn't filter category as case insensitive

### ISSUE THREAD

**Issue by kenvandine** [canonical/ubuntu.com#13557]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

When browsing certified systems on https://ubuntu.com/certified the categories don't filter as expect, it seems to be case sensitive.  Some desktop devices have a category of "desktop" and others have "Desktop".  Selecting "Desktop" in the categories selector on the left doesn't return any of the "desktop" devices.  Ideally the data will be more standardized, but the filter should probably be case insensitive.

## Process

https://ubuntu.com/certified/desktops

This will list devices in the category of "Desktop", however devices with the category "desktop" do not appear in that list.  For example https://ubuntu.com/certified/202306-31641

## Current and expected result

Currently browsing limits the results significantly, there seems to be quite a few devices with the lower case desktop.

**Comment by carkod** [comment]
Thanks, opened a ticket https://warthogs.atlassian.net/browse/WD-7146

**Comment by lizzochek** [comment]
@kenvandine the issue has been fixed. thank you for reporting this issue
