### ISSUE TITLE
Incorrect Hyperlink ["Manage your tracker settings"]

### ISSUE THREAD

**Issue by SEKHMET1Z** [canonical/ubuntu.com#13561]
Incorrect Hyperlink ["Manage your tracker settings"]

There is an incorrect hyperlink present on the bottom of the Tutorials PAGE, Upgrading Ubuntu Desktop
(https://ubuntu.com/tutorials/upgrading-ubuntu-desktop).

The hyperlink for the text "Manage your tracker settings" does not accurately link to an area discussing how to manage tracker settings. 
Instead, the hyperlink directs back to the same page (a general page about upgrading Ubuntu Desktop):
https://ubuntu.com/tutorials/upgrading-ubuntu-desktop

**Comment by lizzochek** [comment]
Hello @SEKHMET1Z . Thank you for filing an issue. This hyperlink is dedicated to open a modal to adjust your cookie settings, not redirect you to a different page and seems to be working correctly at the moment. If it doesn't work for you, please reopen the issue and add more details.
