### ISSUE TITLE
The images are not showing.

### ISSUE THREAD

**Issue by root-11** [canonical/ubuntu.com#13567]
![image](https://github.com/canonical/ubuntu.com/assets/4048422/e592b918-de0a-46f2-8d10-157eae8f9129)

https://ubuntu.com/tutorials/self-healing-kubernetes-deployments-with-microk8s-and-portainer?_ga=2.114703490.489695415.1707730610-2075649430.1707730610#2-install-ubuntu

**Comment by carkod** [comment]
Should be showing now. Thanks for reporting it.
