### ISSUE TITLE
Instagram not listed as a social media on ubuntu.com

### ISSUE THREAD

**Issue by JohnReedLOL** [canonical/ubuntu.com#13572]
I saw an ad for Ubuntu on Instagram and it took me to the Ubuntu Instagram page, @ubuntu_os - https://www.instagram.com/ubuntu_os . That being said, when I looked at the official website [https://ubuntu.com](https://ubuntu.com) , at the bottom where there were social links I saw X (Twitter), Facebook, and LinkedIn but no Instagram. Please put the link to your Instagram on your official web page.

---
*Reported from: https://ubuntu.com/?fbclid=PAAaY0tzX2OrFmE31sOgNGd0lcuolJgmaQPIK5IZVuOWc7q0ewcWaMfC0nUSE*

**Comment by mtruj013** [comment]
Thanks for flagging! @juanruitina are you happy with this?

**Comment by fitojb** [comment]
... and I'd go as far as suggesting you ditched X in favor of Threads and Mastodon...

**Comment by juanruitina** [comment]
@mtruj013 I checked with our social media manager Ahmed and he agreed, let's add the Instagram link after LinkedIn's. I'll be adding it to the main navigation as well, next to the other social links.

**Comment by mtruj013** [comment]
Ticket here: https://warthogs.atlassian.net/browse/WD-8838
