### ISSUE TITLE
download link dosn't work

### ISSUE THREAD

**Issue by seif2003** [canonical/ubuntu.com#13609]
hi, download link dosn't work
![image](https://github.com/canonical/ubuntu.com/assets/146482636/4fff25c8-df21-4d20-8802-ae8e20bc6940)

---
*Reported from: https://ubuntu.com/download/desktop*

**Comment by lizzochek** [comment]
Hello @seif2003. The issue is currently not happening on our side. If it keeps happening for you, please open a new issue and fill the templates with more details, thank you
