### ISSUE TITLE
timezone issue in Kazakhstan

### ISSUE THREAD

**Issue by gmkanat** [canonical/ubuntu.com#13628]
There is an issue with the timezone in Kazakhstan; today it changed to UTC+5, so please update it.

**Comment by carkod** [comment]
What exactly do we have to change? @akbarkz probably you know this better?

**Comment by akbarkz** [comment]
@gmkanat do you mean there is issue in Ubuntu OS with the timezone? This is a website repository, if yoy want to file an issue for Ubuntu OS, please do so in another place, it was specified in the new issue template.

**Comment by gmkanat** [comment]
yeah, that was related to Ubuntu OS, timezone was fixed after 12 hours, thanks for clarification!
