### ISSUE TITLE
Is launchpad answers useful enough to keep on the community support page?

### ISSUE THREAD

**Issue by setharnold** [canonical/ubuntu.com#13655]
On the Community Support page we have an information box for Launchpad Answers:

> [Technical answers system](https://answers.launchpad.net/ubuntu)
> 
> Use Launchpad to add your support question. Keep your query active until you get an answer or browse and search historical questions and answers.

Is Launchpad Answers useful enough to give it such a strong prominence? I'm concerned that there isn't a large enough community here to keep this useful. I've sometimes seen multiple spambots giving users terrible advice and the users have no idea.

Maybe I'm wrong, I know there's some active folks who try to keep it helpful, but are there enough of them?

Thanks

---
*Reported from: https://ubuntu.com/support/community-support*

**Comment by fitojb** [comment]
> are there enough of them?

I moved on a while ago.

Get rid of the link.

**Comment by lechsandecki** [comment]
perhaps https://discourse.ubuntu.com/ would be better than Launchpad Answers?

**Comment by setharnold** [comment]
Yeah, I don't think our Discourses are places to send people looking for technical help. (I'm not actually sure who *should* be sent there, but I do keep hearing that they are not appropriate for user support.) I think we'd be best served to just delete the link to LP Answers and leave it at that.

Thanks

**Comment by setharnold** [comment]
I'm reluctant to share this page with people because we're actively sending people seeking help to a place with no actual help for them.

We don't have to make the page perfect, but deleting this one box with outdated information would go a long way to improving it.

Thanks
