### ISSUE TITLE
Landscape Docs: Width attribute not applying on icons from Discourse

### ISSUE THREAD

**Issue by YanisaHS** [canonical/ubuntu.com#13709]
_Note: I'm the technical author on the Landscape team._

**Problem**
The width (and probably height) attribute on the `<img>` element isn't applying in the Landscape Docs. This is a new problem that began sometime between 22 March and 1 April. I successfully applied the width attribute to an `<img>` element on 22 March.

This affects the user experience because the images look strange and the visualizations are harder to parse.

**Details**

I added a new row to the table in the [About Landscape](https://ubuntu.com/landscape/docs/explanation-about-landscape) page, and now all images in that page are much larger. The screenshots below show:
1. The width attribute not applying on the page in the Landscape Docs
2. The Markdown (with HTML) I used for that image, showing it does specify `width`
3. An image that was added before 22 March, showing that the height and width attributes were applied

I also tried reverting my change, but this issue still happened after I reverted to the original version.

**1**
![Screenshot from 2024-04-01 13-39-36](https://github.com/canonical/ubuntu.com/assets/53576988/549b69a8-f78f-4ba8-af03-a31e14d4d371)

**2**
![Screenshot from 2024-04-01 13-40-16](https://github.com/canonical/ubuntu.com/assets/53576988/c6a764d4-fc29-4454-add7-56df11bd5e5c)

**3**
![image](https://github.com/canonical/ubuntu.com/assets/53576988/1f03f446-1df0-4c61-955d-96881f60aa8c)

**Examples**

Link to the original page with images that don't apply width/height: https://ubuntu.com/landscape/docs/explanation-about-landscape
Link to the corresponding Discourse page: https://discourse.ubuntu.com/t/about-landscape/38612
Link to a working page that hasn't been edited since before 22 March: https://ubuntu.com/landscape/docs/manage-repositories-web-portal

---
*Reported from: https://ubuntu.com/landscape/docs/explanation-about-landscape*

**Comment by carkod** [comment]
The main issue that we have is that Discourse strips all the HTML content that you add and then provides us with bare content, so we don't get any of the HTML code. If @petesfrench or @bartaz have any ideas, I don't think we can easily solve this.

On the other hand, something I've discovered lately is that we could potentially tackle this using a Discourse plugin, but that would require time and planning to create a new plugin and request IS to add vet it and add it.

**Comment by bartaz** [comment]
From the description of the issue it seems it was working before?

As @carkod mentioned, we have no control over this. If discourse removes the width/height values from HTML, we can't know what they were. I guess the only workaround is to use images that are at the expected size (so the file itself needs to be resized to the desired value).

**Comment by anthonydillon** [comment]
We have no control over the markup returned by discourse but we can control the image SRC. I have resized the ticks on the fly and they now work as expected.
