### ISSUE TITLE
Desktops and All-in-one devices show a laptop icon when looking at certified device pages

### ISSUE THREAD

**Issue by pieqq** [canonical/ubuntu.com#13725]
## Summary

When looking at a Desktop or All-in-One certified device, the device icon is a laptop, which is a bit misleading.

This is because both Desktops and Laptops categories are [set to use the Laptop SVG icon](https://github.com/canonical/ubuntu.com/blob/main/templates/certified/model-details.html#L19-L27).

## Steps to reproduce the behavior

1. Go to https://ubuntu.com/certified/202401-33373
2. This is an All-in-One system, but the icon on the right of the page shows a laptop (Not OK)
3. Go to https://ubuntu.com/certified/202207-30449
4. This is a Desktop system, but the icon on the right of the page shows a laptop (Not OK)

## Expected behavior

The icon used should match the device on the page. If it is a desktop, it should look like a desktop (a tower with a screen, for instance). If it's an All-in-One, it should also look like one.

## Screenshot

![image](https://github.com/canonical/ubuntu.com/assets/512471/e04e75f9-10c1-46cb-a880-7d63554dcd5e)

**Comment by britneywwc** [comment]
@juanruitina could you have a look at this please? Do we have any icons specifically for Desktop or All-in-One system?

**Comment by juanruitina** [comment]
I don't think we do, but pinging @lyubomir-popov as this is a visual matter.

**Comment by lyubomir-popov** [comment]
Hi, we don't have an illustration for "all in one" devices. Two options: remove images from all (something we can do quickly), or commission an illustration (will take time as our illustrators have long queues of already commissioned work). Which one do you prefe @pieqq?

**Comment by immortalcodes** [comment]
Since there has been no response on this, I am closing this for now.
Please feel free to re-open/comment on this issue.
