### ISSUE TITLE
Text aligment issues in mobile meganav menus

### ISSUE THREAD

**Issue by bartaz** [canonical/ubuntu.com#13729]
In meganav on small screen sizes in "Use cases" menu the sub titles are weirdly align with text touching left edge of the screen. Likely there should be some spacing there.

<img width="835" alt="image" src="https://github.com/canonical/ubuntu.com/assets/83575/01e57dfc-6025-4ca4-83ae-17d44ff3b071">

---
*Reported from: https://ubuntu.com/*

**Comment by Harsh0707005** [comment]
resolved
