### ISSUE TITLE
Mouseover information for lifecycle mixed up

### ISSUE THREAD

**Issue by sebastianlinner** [canonical/ubuntu.com#13732]
The information presented when hovering the mouse over the diagram under "Ubuntu releases" shows the wrong title for the different support-durations.
Applicable for all LTS-releases (14.04 - 22.04)

LTS standard security maintenance for Ubuntu Main (initial 5 years) - **shown as 10 years**
![standard-lts-support](https://github.com/canonical/ubuntu.com/assets/166585351/876eff0e-7f89-48a0-bf4f-f99bf2537c56)

LTS Expanded Security Maintenance (ESM) for Ubuntu Universe (10 years) - ***shown as 5 years*
![lts-esm-support](https://github.com/canonical/ubuntu.com/assets/166585351/eb2507eb-3343-4d97-b186-9d9929bb94a1)

---
*Reported from: https://ubuntu.com/about/release-cycle

**Comment by britneywwc** [comment]
Hi @sebastianlinner, I believe this is fixed now. Could you please check again?

**Comment by britneywwc** [comment]
Closing now as it's fixed, feel free to reopen if the issue still persists.
