### ISSUE TITLE
Update screenshot for Lubuntu 24.04 LTS

### ISSUE THREAD

**Issue by tsimonq2** [canonical/ubuntu.com#13784]
Please upload this image to assets.ubuntu.com and change the link on line 168 of `templates/desktop/flavours.html` to point at it:

![screen](https://github.com/canonical/ubuntu.com/assets/3689821/0f79ef15-fda4-4ddf-a7bc-bdadbdaf967e)

Thanks in advance!

**Comment by immortalcodes** [comment]
Hi @tsimonq2 ,
Is there any specific reason for replacement of this image.

**Comment by anthonydillon** [comment]
@immortalcodes @akbarkz we should update the flavours screenshots to the latest LTS as we do with the Ubuntu screenshots across the website.

**Comment by anthonydillon** [comment]
Hi, @tsimonq2 is the screenshot you have provided of 24.04 LTS or 23.10 as the webpage would suggest? 
If it's not 24.04 LTS, please provide an official screenshot of Lubuntu 24.04 LTS. And we would be happy to replace it.

**Comment by akbarkz** [comment]
Screenshots were updated on the webpage via [this PR](https://github.com/canonical/ubuntu.com/pull/13795).
