### ISSUE TITLE
Graphics acceleration with Nvidia-(GT-710)

### ISSUE THREAD

**Issue by Dasstan06** [canonical/ubuntu.com#13807]
The nvidia-driver-470 installation package does not provide graphics acceleration to my GT-710 card. It gives me errors using ubuntu-24.04 with Gnome.
Furthermore, when installing said driver it completely deconfigures the screen resolution of the GNOME Startup Session Manager.
It also recognizes two monitors when I actually use one.
![Captura desde 2024-04-25 22-33-11](https://github.com/canonical/ubuntu.com/assets/168154361/19c606bd-b448-475a-8c84-c1dff5fb6064)

---
*Reported from: https://ubuntu.com/*

**Comment by Dasstan06** [comment]
It also recognizes two monitors when I actually use one.
![Captura desde 2024-04-25 22-43-42](https://github.com/canonical/ubuntu.com/assets/168154361/606064d2-3d82-4b25-a839-9d9a216a9acd)

**Comment by MohammadsM** [comment]
I had same problem with newly installed noble and nVIDIA GT-710.
But [ertankayalar](https://askubuntu.com/users/1071958/ertankayalar) found a workaround with setting a value in /etc/environment .
`GSK_RENDERER=gl`

https://askubuntu.com/questions/1511575/ubuntu-24-04-screen-glitches-on-gnome-apps-after-install

**Comment by dalareo** [comment]
Same problem here. Solved text not appearing until hover whith @MohammadsM proposed solution

**Comment by mtruj013** [comment]
Thanks all. Just to clarify this project handles issues raised against the ubuntu.com website specifically, not the Ubuntu OS. OS bugs are tracked using launchpad, please read [here](https://help.ubuntu.com/community/ReportingBugs) for more info
