### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by 106106** [canonical/ubuntu.com#13806]
Hi, it seems like there's a missing link in the sentence

"While this is one option for deploying the on-prem server, another is to deploy to virtual machines as described here."
The "here" I believe should have a link 

---
*Reported from: https://ubuntu.com/security/livepatch/docs/livepatch_on_prem/tutorial/Getting started with Livepatch and Microk8s*

**Comment by britneywwc** [comment]
Thanks for reporting this! We're looking into adding the missing link.

**Comment by mtruj013** [comment]
Just a heads up, content for docs is pulled from discourse so it needs to be updated [there](https://discourse.ubuntu.com/t/getting-started-with-livepatch-on-prem-and-microk8s/39130/1) by the content owner(s). You can find the relevant discourse post for any given doc by scrolling to the bottom of the page and clicking on the link in the nofication banner: 
![image](https://github.com/canonical/ubuntu.com/assets/17607612/69384abf-6b4d-4c44-a274-2427fde9b1b2)
@kian99 it looks like you're the author, could you have a look please?

**Comment by kian99** [comment]
Hi, this was fixed a few minutes ago, thanks for the heads up.

**Comment by britneywwc** [comment]
Thanks everyone, closing this as the link is updated now on https://ubuntu.com/security/livepatch/docs/livepatch_on_prem/tutorial/Getting%20started%20with%20Livepatch%20and%20Microk8s
