### ISSUE TITLE
14.04 esm has been replaced by legacy

### ISSUE THREAD

**Issue by setharnold** [canonical/ubuntu.com#13836]
Hello, our Ubuntu Pro 'store' is still indicating that 14.04 ESM is available; it has been replaced by 14.04 Legacy: https://canonical.com/blog/canonical-expands-long-term-support-to-12-years-starting-with-ubuntu-14-04-lts

I understand that this is a separate product with separate pricing. A lot of this text probably needs an update.

Thanks

![esm](https://github.com/canonical/ubuntu.com/assets/5447148/81af1690-b18c-4e66-8f2f-aae8d6d007b8)

---
*Reported from: https://ubuntu.com/pro/subscribe*

**Comment by mtruj013** [comment]
@minkyngkm @abhigyanghosh30 @leiaru-c could y'all have a look please?

**Comment by abhigyanghosh30** [comment]
@lechsandecki What should we do here?

**Comment by lechsandecki** [comment]
updated the shop. thanks for the ping
legacy is available via direct sales but not in the shop
