### ISSUE TITLE
Unbuntu Pro not working

### ISSUE THREAD

**Issue by mbcharney** [canonical/ubuntu.com#13841]
500: Server error

Something's gone wrong.

    The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Try reloading the page. If the error persists, please note that it may be a [known issue](https://github.com/canonical-websites/www.ubuntu.com/issues). If not, please [file a new issue](https://github.com/canonical-websites/www.ubuntu.com/issues/new).

**Comment by fed15ora** [comment]
same as previous message - tried to access - https://ubuntu.com/pro/subscribe but get the following error -

500: Server error

Something's gone wrong.

    The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Try reloading the page. If the error persists, please note that it may be a [known issue](https://github.com/canonical-websites/www.ubuntu.com/issues). If not, please [file a new issue](https://github.com/canonical-websites/www.ubuntu.com/issues/new).

**Comment by lizzochek** [comment]
Hello @mbcharney @fed15ora, thank you for filing an issue. Currently the page you referred to is working correctly. this may have been a temporary issue. If the issue persists, please file a new issue with more details.

**Comment by fed15ora** [comment]
many thanks, it is working now.

2 Jul 2024 12:43:32 Liza ***@***.***>:
