### ISSUE TITLE
500 error specifically when searching nginx security patches

### ISSUE THREAD

**Issue by KernelDeimos** [canonical/ubuntu.com#13848]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu OS related bugs please [go here](https://help.ubuntu.com/community/ReportingBugs)*.
*Please provide as many details as possible in order to provide maintainers more context about the issue. Don't skip/remove any of the sections below. If there is no data to provide in one of the sections, please specify it by typing "N/A" or similar. That will help maintainers reproduce the issue and be able to help quickly. Thanks.*

## Summary

Trying to perform a search from the page https://ubuntu.com/security/cves for package `nginx` produces a 500 error

## Steps to reproduce the behavior

1. Go to https://ubuntu.com/security/cves
2. Type "nginx" in the field "package"
3. Click search

## Expected behavior

Search results

## Screenshot

![image](https://github.com/canonical/ubuntu.com/assets/7225168/a00f1a3a-3470-454e-acaa-edea2064e22f)

## Browser/device details

- OS: Archlinux
- Browser: Chromium

**Comment by jslarraz** [comment]
It seems to produce a 500 error also when searching for CVEs. 

Making a search for a CVE, following url is targeted https://ubuntu.com/security/cves?q=CVE-XXXX-XXXX what leads to a error 500 server error. Using following url instead seems to work properly https://ubuntu.com/security/CVE-XXXX-XXXX

**Comment by KernelDeimos** [comment]
This appears to have been fixed

**Comment by mtruj013** [comment]
Thanks for reporting @KernelDeimos. This should be fixed now, could you try again and confirm?

**Comment by lizzochek** [comment]
Hello @KernelDeimos. Currently the issue does not happen as far as I can see. If it keeps happening for you, please open a new issue. Thank you!
