### ISSUE TITLE
Authentication required failed

### ISSUE THREAD

**Issue by Anjanakvpt** [canonical/ubuntu.com#13875]
I have got an acer notebook from govt in a scholarship basis ,when I firstly op n the window it shows that authentication required. I have never been set a password before and it shows to enter password. I can't download an app ,it shows without an authentication password it can't be downloaded.please fix this problem

**Comment by carkod** [comment]
Hi @Anjanakvpt thanks for reporting this. Are you talking about the ubuntu.com website or the Ubuntu OS?
