### ISSUE TITLE
Can’t log in to Ubuntu Pro site

### ISSUE THREAD

**Issue by GAM-GC** [canonical/ubuntu.com#13877]
Supplied credentials, then asked for “Service details” to be provided (whatever they are). Got a cookie error (macaroon - cute) which is new, hence I’m here. 
I’d like to access your site to renew my Ubuntu One subscription please. 
N.B. site email is glen.mcallister@greencollar.com.au.

Thanks,
GAM

**Comment by mtruj013** [comment]
@minkyngkm @abhigyanghosh30 could you guys take a look please?

**Comment by minkyngkm** [comment]
Hi @GAM-GC It seems you can retry and it will work. Feel free to comment here if there's anything to add! @pandrey2003 Thanks! :)

**Comment by anthonydillon** [comment]
Closing this issue for now. @GAM-GC if this occurs again please comment and we will reopen this issue and look into it again.
