### ISSUE TITLE
Public notes not displayed correctly in Certified Hardware pages

### ISSUE THREAD

**Issue by pieqq** [canonical/ubuntu.com#13870]
## Summary

When Canonical issues a certificate for a hardware, Canonical staff can create notes to be displayed to the end users.

For a recent project, we needed to issue a long note that includes a lot of newlines. On our internal website (C3), it shows up correctly, but when the note is pushed to the public website, it seems all the newlines are removed, leading to a very hard to read paragraph.

## Steps to reproduce the behavior

1. Go to https://ubuntu.com/certified/202307-31886
2. Scroll down to "Notes"
3. Observe the problem

If you have access to C3, the internal certificate is at https://certification.canonical.com/certificates/2405-15681/

## Expected behavior

Newlines should not be trimmed so hard, to be able to preserve some kind of layout.

## Screenshot

Public website (incorrect):

![image](https://github.com/canonical/ubuntu.com/assets/512471/4ec92b4f-bc94-43bb-9417-1ded545a5484)

Internal website (expected layout):

![image](https://github.com/canonical/ubuntu.com/assets/512471/86b3a3e9-ac45-4be4-b865-c6cb2844326a)

**Comment by mz2** [comment]
Markdown rendering the notes would be one pretty useful solution for dealing with paragraphs of plain text.

**Comment by britneywwc** [comment]
Thanks for flagging @pieqq! I've pushed up a PR that will show the line breaks on "Notes" where appropriate.
