### ISSUE TITLE
Ubuntu 24 Faild to boot 

### ISSUE THREAD

**Issue by aouiniamine** [canonical/ubuntu.com#13886]
I've faced an issue where initially I couldn't log in with my password into my computer after it's locked.
Then I can't boot to the system with dependency sssd failing.
I opened recovery mode and removed the package, but the same issue still appeared (now without any leads to fix the issue.)
---
 *Reported from: https://ubuntu.com/*

**Comment by mtruj013** [comment]
Hi @aouiniamine , thanks for reporting. This repo deals with the ubuntu.com website only, for Ubuntu OS related bugs please [see here](https://help.ubuntu.com/community/ReportingBugs)
