### ISSUE TITLE
The thank-you pop-up goes above the navigation

### ISSUE THREAD

**Issue by petesfrench** [canonical/ubuntu.com#13906]
## Summary

The thank-you pop-up goes above the navigation

## Steps to reproduce the behavior

1. Go to https://ubuntu.com/download/desktop/thank-you?version=24.04&architecture=amd64&lts=true
2. Sign up for the news letter
3. Wait until it take you to the next page
4. Scroll and see the pop-up is above the navigation

## Expected behavior

It goes below the navigation

## Screenshot

![image](https://github.com/canonical/ubuntu.com/assets/58276363/153d19a8-30f4-429c-b8fc-3e9ce7cdf4a9)

**Comment by britneywwc** [comment]
Closing this issue as it has been fixed here: https://github.com/canonical/ubuntu.com/pull/14222
