### ISSUE TITLE
[Request] Updating ubuntu.com/kernel/lifecycle with the new diagram from ubuntu.com/about/release-cycle

### ISSUE THREAD

**Issue by thisisrichardferreira** [canonical/ubuntu.com#13915]
Hi @anthonydillon, @local-optimum mentioned I could raise an issue here on Github about pulling our new lifecycle diagram in our `ubuntu.com/about/release-cycle` page into our `ubuntu.com/kernel/lifecycle` page. More details below.

## Summary

On `ubuntu.com/kernel/lifecycle`, the diagram is an older one compared to `ubuntu.com/about/release-cycle` and should be updated to match the more recent one.

## Steps to reproduce the behavior

1. Go to [ubuntu.com/kernel/lifecycle#installation-20-04](https://ubuntu.com/kernel/lifecycle#installation-20-04).
2. Scroll down to the `Kernel release schedule` section near the bottom, just above the footer.

## Expected behavior

The lifecycle diagram displayed on [ubuntu.com/kernel/lifecycle#installation-20-04](https://ubuntu.com/kernel/lifecycle#installation-20-04) under the `Kernel release schedule` section should be the same as the one on [ubuntu.com/about/release-cycle#ubuntu-kernel-release-cycle](https://ubuntu.com/about/release-cycle#ubuntu-kernel-release-cycle) under the `Ubuntu kernel support lifecycle` section.

## Screenshot

Older lifecycle diagram as displayed on [ubuntu.com/kernel/lifecycle#installation-20-04](https://ubuntu.com/kernel/lifecycle#installation-20-04) under the `Kernel release schedule` section.

![Screenshot 2024-06-03 at 15 26 47](https://github.com/canonical/ubuntu.com/assets/12816804/c5f04122-6c3c-4b16-8897-3a129d3b5e1f)

Most recent lifecycle diagram as displayed on [ubuntu.com/about/release-cycle#ubuntu-kernel-release-cycle](https://ubuntu.com/about/release-cycle#ubuntu-kernel-release-cycle) under the `Ubuntu kernel support lifecycle` section.

![Screenshot 2024-06-03 at 15 27 14](https://github.com/canonical/ubuntu.com/assets/12816804/b5c6d7e4-cff5-4583-b5c8-a8ce79de79bb)

## Browser/device details

N/A

**Comment by mtruj013** [comment]
Thanks for reporting @thisisrichardferreira, we've planned this for the current pulse. You can track the jira ticket [here](https://warthogs.atlassian.net/browse/WD-11813)

**Comment by thisisrichardferreira** [comment]
Thanks @mtruj013!
