### ISSUE TITLE
update for new LTS versions

### ISSUE THREAD

**Issue by 106106** [canonical/ubuntu.com#13921]
The default is to 20.04 LTS for 

[Run Ubuntu Server 20.04 LTS](https://aws.amazon.com/marketplace/pp/B087QQNGF1)
and
[Launch Ubuntu Pro 20.04 LTS](https://aws.amazon.com/marketplace/pp/B087L1R4G4)

I would recommend updating to 22.04 or 24.04 

additionally Noble (24.04) isn't mentioned further down in the "Get Ubuntu Pro on AWS now:" section

---
*Reported from: https://ubuntu.com/aws*

**Comment by carkod** [comment]
PR already in progress https://github.com/canonical/ubuntu.com/pull/13924

**Comment by carkod** [comment]
Fixed by https://github.com/canonical/ubuntu.com/pull/13924
