### ISSUE TITLE
RISC-V QEMU image link is incorrect

### ISSUE THREAD

**Issue by magalilemes** [canonical/ubuntu.com#13937]
## Summary

The link to download the RISC-V Ubuntu Server preinstalled image for QEMU is incorrect and points to the the image for the SiFive Unmatched board instead.

## Steps to reproduce the behavior

1. Go to https://ubuntu.com/download/risc-v
2. Click on 'QEMU Emulator'
3. Scroll down to 'Ubuntu Server preinstalled image'
4. Check the link to which the 'Download 24.04' button points.

## Expected behavior

The download link should point to https://cdimage.ubuntu.com/releases/noble/release/ubuntu-24.04-preinstalled-server-riscv64.img.xz instead.

## Screenshot

N/A

**Comment by carkod** [comment]
Thanks for reporting. Suggested change in the [copy doc](https://docs.google.com/document/d/1kkJeq9HdH3iWV35HwihcJd3CxZw9Jy21W66lJl8VbWs/edit)

**Comment by xypron** [comment]
In Focal and Jammy we had a common image for Unmatched and QEMU. In Noble we have separate images.

The RISC-V preinstalled server image for QEMU on Ubuntu 24.04 is https://cdimage.ubuntu.com/releases/noble/release/ubuntu-24.04-preinstalled-server-riscv64.img.xz .

**Comment by lizzochek** [comment]
Hello @xypron @magalilemes. Thank you for bringing this up, the link was updated
