### ISSUE TITLE
Issue template contains expired 3rd party URL

### ISSUE THREAD

**Issue by makuhlmann** [canonical/ubuntu.com#13939]
## Summary

The issue template on this repository contains a hint to visit mybrowser.fyi to get information about your browser configuration. However the domain seems to have expired or has been abandoned.

While unlikely, this could be a security risk if a malicious actor gets ahold of the domain.

Here is the offending line:
`[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.]`

## Steps to reproduce the behavior

1. Create a new issue
2. Open the mentioned link: [mybrowser.fyi](https://mybrowser.fyi/)

## Expected behavior

A page giving you information about your web browser.

## Screenshot

![image](https://github.com/canonical/ubuntu.com/assets/19255462/50d501cf-4fa6-4648-b76f-85deb46a7f88)

## Browser/device details

- Device: Custom PC
- OS: Windows 10 21H2
- Browser Google Chrome
- Version 125.0.6422.142

**Comment by mtruj013** [comment]
Thanks for catching this @makuhlmann , fix incoming!
