### ISSUE TITLE
Video doesn't play

### ISSUE THREAD

**Issue by dimaqq** [canonical/ubuntu.com#13930]
![Screenshot 2024-06-07 at 12 07 43](https://github.com/canonical/ubuntu.com/assets/662249/7b26fe91-2f02-4665-8492-a4f845bb0986)

---
*Reported from: https://ubuntu.com/kubernetes/charmed-k8s*

**Comment by carkod** [comment]
PR already in review https://github.com/canonical/ubuntu.com/pull/13932
