### ISSUE TITLE
500 Server Error certified hardware research

### ISSUE THREAD

**Issue by copilcode** [canonical/ubuntu.com#13947]
Hi,

I've been trying to search for compatible hardware through this link : ubuntu.com/certified?q=emulex

I've a 500 coming back. Could you please fix that asap ? I need to make sure Ubuntu can be installed on my server :-)

Thanks!

Augustin

<img width="1421" alt="Screenshot 2024-06-12 at 22 04 11" src="https://github.com/canonical/ubuntu.com/assets/136515229/de1bb205-89b2-4a7e-b3e5-ac82486e3ad8">

**Comment by carkod** [comment]
Thanks for reporting this, this should work now.
