### ISSUE TITLE
Include release cycles for Juju, MASS, and LXD.

### ISSUE THREAD

**Issue by 106106** [canonical/ubuntu.com#13940]
It would be very helpful to have a single page to point to where all major products have their release cycle documented.

See
- https://juju.is/docs/juju/roadmap
- https://discourse.maas.io/t/3-5-0-release-schedule/7956/2
- https://ubuntu.com/blog/lxd_5-21-0_lts

Juju Version | End of bug fix support* | End of security fix support*
-- | -- | --
3.5 | 30 November 2024 | 30 January 2025
3.4 | 30 August 2024 | 30 November 2024
3.3 | 30 April 2024 | 30 August 2024
3.1 | No | July 2024
2.9.x - LTS | No | April 2028

MAAS Version | Support Level*
-- | --
3.4 | Fully Supported
3.3 | Fully Supported
3.2 | Bugfix only, no features, no backports
3.1 | Bugfix only, no features, no backports

LandscapeServer | End of Standard Support | End of ESM | Available For
-- | -- | -- | --
24.04 LTS | 2029 | 2034 | 22.04 LTS or 24.04 LTS
23.04 | 2029 | No ESM | 20.04 LTS or 22.04 LTS

LXD Version | End of Support
-- | --
5.21.x | June 2029
5.0 | June 2027
4.0 | June 2025

---
*Reported from: https://ubuntu.com/about/release-cycle*

**Comment by WizardBit** [comment]
Great idea! Having an easily accessible all in one place to view this information would be really beneficial.

**Comment by lizzochek** [comment]
Hello @106106 @WizardBit. I have reached out to the responsible team to process your request. Thank you for filing an issue

**Comment by immortalcodes** [comment]
@106106 
Please see this closed issue, do you think this answers to your suggestion?

**Comment by WizardBit** [comment]
@immortalcodes is there a missing link to your comment?

**Comment by immortalcodes** [comment]
Yeah, missed it, updated it now

**Comment by immortalcodes** [comment]
I think the reason why we keep our release cycles on different pages is explained [here](https://github.com/canonical/ubuntu.com/issues/14104#issuecomment-2262869208), but still feel free to re-open the issue if you want more clarification on this.
Thanks
