### ISSUE TITLE
/pro/dashboard returning 500

### ISSUE THREAD

**Issue by careyjames** [canonical/ubuntu.com#13975]
[
![Screenshot from 2024-06-20 13-23-49](https://github.com/canonical/ubuntu.com/assets/52982329/f9b447d6-e749-4e4b-8d36-95b2cd768410)
](url)

**Comment by simulans** [comment]
I'm seeing the same for Pro Dashboard, Landscape SAAS, and support portal. Landscape API calls are failing as well. It was like that from about 8:45 this morning to 10:00 EST, and now again from about 13:15 EST.

**Comment by mtruj013** [comment]
Hi @careyjames @simulans, we had an outage yesterday that affected most of our services. This has ben resolved now, but please reopen this issue if you continue to run into this problem. Thanks!
