### ISSUE TITLE
Embedded page requires 10->12 year LTS update

### ISSUE THREAD

**Issue by chrisschnabel** [canonical/ubuntu.com#13974]
The copy and image in the "Security matters most" section refers to 10 years of support. This should be updated to reflect the 12 years of support announced when 24.04 was released; based on +2year extended support.

---
*Reported from: https://ubuntu.com/embedded*

**Comment by lizzochek** [comment]
Hello @chrisschnabel. Thank you for filing an issue, it will be updated soon
