### ISSUE TITLE
This tutorial is dated and the commands/instructions don't work anymore with the new revisions of the charms/snaps

### ISSUE THREAD

**Issue by 106106** [canonical/ubuntu.com#13982]
There's multiple bugs/errors when trying to use this tutorial to get started with livepatch onprem and lets to a back experience. I suggest pointing users to the how to using LXD until this can be re-written to work with the newest versions of the charms/snaps etc.

---
*Reported from: https://ubuntu.com/security/livepatch/docs/livepatch_on_prem/tutorial/Getting started with Livepatch and Microk8s*

**Comment by britneywwc** [comment]
Hi @106106, can you comment on the Discourse post [here](https://discourse.ubuntu.com/t/getting-started-with-livepatch-on-prem-and-microk8s/39130?_gl=1*tw23wg*_gcl_au*MTg2NDMyMTcxLjE3MTg2ODE3OTQ.&_ga=2.56935018.1304205652.1721617739-452497310.1710905626) as Kian mentioned? I will close this issue for now as tutorials are pulled from its related Discourse post.
