### ISSUE TITLE
Security Notice RSS Feed broken since 11 Jun 2024

### ISSUE THREAD

**Issue by batycoon** [canonical/ubuntu.com#13983]
Website updates to current date do not update the RSS feed. Last I see is June 11th.

---
*Reported from: https://ubuntu.com/security/notices*

**Comment by cjohnston1158** [comment]
Also reported at:

https://bugs.launchpad.net/ubuntu-website-content/+bug/2070350

**Comment by mtruj013** [comment]
@batycoon @cjohnston1158 this should be fixed now, thanks for reporting. Feel free to reopen the issue if you encounter this again, thanks!

**Comment by batycoon** [comment]
Just got the RSS feed output! Thanks!
