### ISSUE TITLE
Security Notices not date sort organized on website

### ISSUE THREAD

**Issue by batycoon** [canonical/ubuntu.com#13984]
Offset "1" shows latest security notices

Offset "2" shows some of the first security notices ever (Ubuntu 4.10)

---
*Reported from: https://ubuntu.com/security/notices?offset=10*

**Comment by batycoon** [comment]
Probably duplicate of #13981

**Comment by lizzochek** [comment]
Hello @batycoon. thank you for filing an issue. Currently the notices are shown correctly according to their date. If the issue proceeds for you, please open a new issue and fill in the issue template with more details.
