### ISSUE TITLE
Pagination does not work on ubuntu.com/security/notices

### ISSUE THREAD

**Issue by seva-luchianov** [canonical/ubuntu.com#13981]
If you navigate to any page other than the first page on https://ubuntu.com/security/notices, you do not see the expected results.
The results you do see are ancient notices (`USN-12-1` up through `USN-20-1`) from 2004 and are the same for any subsequent page.

I believe this is related to passing in the `?offset=` query string which is used for pagination on both the main page and the https://ubuntu.com/security/notices.json API.

When using the json API, passing in the `?offset=` query string causes a 503 error response.
Note that going to https://ubuntu.com/security/notices.json without the offset will load the correct results.

Repro Steps:
- Navigate to https://ubuntu.com/security/notices?offset=10
Expectation: See results from 2024
Actual: See results from 2004

- Navigate to https://ubuntu.com/security/notices.json?offset=10
Expectation: See results in json format from 2024
Actual: See 503 Error

---
*Reported from: https://ubuntu.com/security/notices*

**Comment by seva-luchianov** [comment]
After further poking at the website I found that `?offset=40` and greater will start to return real results for https://ubuntu.com/security/notices

The results returned for `?offset=40` end at June 6th so this bug is still preventing users from accessing any notices between June 6th and June 17th

This behavior is _not_ mirrored for https://ubuntu.com/security/notices.json which is still broken for _any_ offset query string.

**Comment by seva-luchianov** [comment]
Looking at other issues this appears to coincide with the release of
https://github.com/canonical/ubuntu-com-security-api/pull/152/

**Comment by lizzochek** [comment]
Hello @seva-luchianov. Thank you for filing an issue, it seems to be resolved and is currently not happening. If it keeps happening for you, please file a new issue.
