### ISSUE TITLE
Pagination is still not fixed for the JSON API on ubuntu.com/security/notices.json

### ISSUE THREAD

**Issue by seva-luchianov** [canonical/ubuntu.com#14018]
https://github.com/canonical/ubuntu.com/issues/13981 is still not fixed, I just tried navigating to it today

https://ubuntu.com/security/notices.json?offset=20

<img width="582" alt="Screenshot 2024-07-01 at 10 53 57 AM" src="https://github.com/canonical/ubuntu.com/assets/7736081/991a4668-f9d8-435c-89ca-7269951bcf00">

[ubuntu.com.har.zip](https://github.com/user-attachments/files/16054742/ubuntu.com.har.zip)

**Comment by britneywwc** [comment]
Hi @seva-luchianov, thanks for raising an issue. 
This is a known issue with the security notices endpoint, you can track the progress here https://github.com/canonical/ubuntu-com-security-api/issues/165.
