### ISSUE TITLE
500: Server error when searching for specific error ubuntu

### ISSUE THREAD

**Issue by thijskalshoven** [canonical/ubuntu.com#14014]
When on the following [page](https://ubuntu.com/security/notices) and you select a specific ubuntu server and you press search you will go to the following [paeg](https://ubuntu.com/security/notices?order=newest&release=oracular&details=) which will show a error 500.

**Comment by lizzochek** [comment]
@thijskalshoven Thank you for filing an issue, currently search works correctly, no 500 is showing, that may have been a temporary server issue.
