### ISSUE TITLE
Too many search results on package search

### ISSUE THREAD

**Issue by setharnold** [canonical/ubuntu.com#14013]
Hello, I just searched for CVEs in the package `qtbittorrent` and was told that there were over 38k CVEs for this package:

https://ubuntu.com/security/cves?q=&package=qtbittorrent&priority=&version=&status=

> 1 – 20 of 38454 results

No CVEs for this package are on the first page.

![too_many_cves](https://github.com/canonical/ubuntu.com/assets/5447148/1e0e3176-dec8-4833-9624-688a38eca7f3)

---
*Reported from: https://ubuntu.com/security/cves?q=

**Comment by lizzochek** [comment]
Hello @setharnold. Thank you for filing an issue. It has already been triaged by our team, you can see updates in this issue: #13957
