### ISSUE TITLE
search on CVE page yields no results when OS version is not set

### ISSUE THREAD

**Issue by Raypresto** [canonical/ubuntu.com#14020]
### Summary

Searching on the [CVE search page](https://ubuntu.com/security/cves) yields no results when version is set to any or current, removing the version from the query, or selecting a specific version, allows results to load.

e.g. no results [with version](https://ubuntu.com/security/cves?q=&package=&priority=&version=), expected results [without version](https://ubuntu.com/security/cves?q=&package=&priority=)

### Steps to reproduce the behavior

1. Go to https://ubuntu.com/security/cves
2. Click search
![image](https://github.com/canonical/ubuntu.com/assets/6196692/7540b3ec-d058-4ac6-ae38-ac7f78e7ed08)

### Expected Behaviour

clicking search with any version or current version should return results
e.g.
![image](https://github.com/canonical/ubuntu.com/assets/6196692/d2b45bfb-12d6-4a13-886b-1185b669c59b)

### Browser details

Browser Chrome
Version 126.0.6478.127 (Official Build) (x86_64)

---
*Reported from: https://ubuntu.com/security/cves*

**Comment by lizzochek** [comment]
Hello @Raypresto . than k you for filing an issue, we are looking into it

**Comment by mtruj013** [comment]
Related issue as reported by @nobuto-m:

 > the search with “ssh” returns nothing:
https://ubuntu.com/security/cves?q=&package=ssh&priority=&version=

Empty priority param in addition to the version param needs to be addressed.
