### ISSUE TITLE
System sounds are been recognized as microfone audio input

### ISSUE THREAD

**Issue by lucas-glopes** [canonical/ubuntu.com#14033]
## Summary
When recording audio or when speaking on headphone/earphone mic on calls, **the system sounds are recognized as audio input as well as my voice.**

## More Details
The main problem I have been having is that **during calls the system sounds input cause it to become echo for people who are listening to me**. This happens probably because while other people are talking, the system sound that is being recognize is their voices (the input audio). As I mentioned before, as long as this system sounds also go to my mic input, it causes echo for who is listening, so I am never able to let my mic on or on the auto speech detection mode, as long as anyone's voice is recognized as audio input. 

**This problem started to happen since the most recent update** (by the time I'm writing this report, my system is up to date).

## OS Info
I am currently using Ubuntu 24.04 LTS, with the Linux 6.8.0-36-generic Kernel.

**Comment by lizzochek** [comment]
Hello @lucas-glopes. thank you for filing an issue, however this repository is for the ubuntu.com website, not Ubuntu OS. Here you can find community support for the OS: https://ubuntu.com/support/community-support
