### ISSUE TITLE
Images on /core do not span the full width of their parent containers on screens > 1680px

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/ubuntu.com#14053]
cc @akbarkz can we please triage this?

![image](https://github.com/canonical/ubuntu.com/assets/2741678/db19708a-6475-4e02-b4ae-e637acd5c4cf)
![image](https://github.com/canonical/ubuntu.com/assets/2741678/32f549bb-3464-4e92-8d5c-cd11519bd778)
![image](https://github.com/canonical/ubuntu.com/assets/2741678/f82ed140-89e5-4486-8ac2-d34ae93885f7)

**Comment by britneywwc** [comment]
Hi @lyubomir-popov, could you please check again? I believe the images have been updated to fit the full width now.
