### ISSUE TITLE
Intel TDX version information out of date

### ISSUE THREAD

**Issue by chrisschnabel** [canonical/ubuntu.com#14065]
>6.5 kernel, derived from the 23.10

The latest Intel TDX is 6.8 kernel, from 24.04 available. The Intel TDX content should be updated to reflect either specific reference to 24.04, or made evergreen to point the reader to https://github.com/canonical/tdx for the latest.

---
*Reported from: https://ubuntu.com/confidential-computing*

**Comment by britneywwc** [comment]
Hi Chris, please submit a Jira request [here](https://warthogs.atlassian.net/jira/software/c/projects/WD/forms/form/direct/4/10013) for this copy update.
