### ISSUE TITLE
Non-released are listed with released filter

### ISSUE THREAD

**Issue by nteodosio** [canonical/ubuntu.com#14066]
Given https://ubuntu.com/security/cves?q=&package=&status=released, I see

![s](https://github.com/canonical/ubuntu.com/assets/105225958/67158ba4-64d5-42cf-aed8-11ad8eaf35f8)

If the fist two are not released in any series, why are they listed in this view?

---
*Reported from: https://ubuntu.com/security/cves?q=

**Comment by britneywwc** [comment]
Thanks for flagging @nteodosio. This is a known issue and we have an ongoing task for the CVE overhaul which will address this status release filter bug along with other issues. You can track the progress of the overhaul here #13412
