### ISSUE TITLE
Take down Intel RealSense tutorial

### ISSUE THREAD

**Issue by chrisschnabel** [canonical/ubuntu.com#14078]
The Intel RealSense tutorial at https://ubuntu.com/tutorials/using-intel-realsense-sdk is out of date and should be taken down.

1. It uses Ubuntu 16.04
2. It references the Intel Joule which was discontinued in 2017
3. The [Intel build guides](https://dev.intelrealsense.com/docs/compiling-librealsense-for-linux-ubuntu-guide) is top google hit and instruct users to download Ubuntu anyways

**Comment by britneywwc** [comment]
Thanks @chrisschnabel, the page has been taken down now.
