### ISSUE TITLE
Monitor error

### ISSUE THREAD

**Issue by bendang29** [canonical/ubuntu.com#14088]
this happened to my tuf a17 with the latest ubuntu :0 although it works normally with my screen :v https://github.com/user-attachments/assets/764609f4-9b7d-4727-81e9-b24f8568f9e5

**Comment by britneywwc** [comment]
Hi @bendang29, please file the issue [here](https://bugs.launchpad.net/ubuntu/) as it is related to UbuntuOS and not the ubuntu.com website.
