### ISSUE TITLE
please add maas, lxd, etc lifecycles

### ISSUE THREAD

**Issue by setharnold** [canonical/ubuntu.com#14104]
Today I learned MAAS uses a different lifecycle than our other products. LXD has a confusing lifecycle (I'm sure either the previous one or the new one in isolation are perfectly fine, but the combination of two different styles of version numbers is confusing.) Probably we have other products with their own unique lifecycle that should be documented here, beyond MAAS and LXD.

Thanks

---
*Reported from: https://ubuntu.com/about/release-cycle*

**Comment by immortalcodes** [comment]
Hi,
Could you please elaborate more on this issue

**Comment by anthonydillon** [comment]
We purposely do not mention MAAS in the Ubuntu release cycle page due to this inconsistency and that lifecycle should be documented on maas.io and other products with different life cycles.
