### ISSUE TITLE
Trying to ubuntu lts but download is too slow from india 

### ISSUE THREAD

**Issue by jaganathan07** [canonical/ubuntu.com#14122]
Download is too slow 

---
*Reported from: https://ubuntu.com/download/desktop/thank-you?version=24.04

**Comment by immortalcodes** [comment]
Hi,
I am looking into this issue.

**Comment by anthonydillon** [comment]
@jaganathan07 thank you very much for taking the time to report this issue to us. Would you be able to let us know which mirror or download URL you are provided when downloading the ISO?

**Comment by jaganathan07** [comment]
Website link mentioned below https://ubuntu.com/download/desktop/thank-you?version=24.04&architecture=amd64&lts=true

**Comment by anthonydillon** [comment]
Yes that is the page which triggers the download but could you share the URL of the download itself please?

**Comment by immortalcodes** [comment]
@jaganathan07 
What you would like to do here is go to network tab while doing inspect after you have clicked the download button and reached thank-you page.
![image](https://github.com/user-attachments/assets/f46af4a3-0b11-431b-9b72-a2d2dda1a964)

And the request URL is the one that is the download URL for you

**Comment by immortalcodes** [comment]
Hi, the issue has been intimated to relevant team and we are trying to resolve this quickly.
Thanks

**Comment by akbarkz** [comment]
@jaganathan07 It appears that in India the local community-driven mirrors were used, and they were quite slow. We redirected the traffic to our main servers so they should be quicker. Please try it again and let us know.
In the meantime there is a plan to improve mirrors in India and make it better for future downloads.
