### ISSUE TITLE
searching in the /security path returns a 504 gateway timeout error

### ISSUE THREAD

**Issue by panlinux** [canonical/ubuntu.com#14132]
This url is currently returnig a 504 gateway timeout error:

https://ubuntu.com/security/cves?q=bind9&package=

---
*Reported from: https://ubuntu.com/*

**Comment by immortalcodes** [comment]
Hi @panlinux ,
Thanks for reporting this, this issue is being worked upon.

**Comment by immortalcodes** [comment]
Could you check for this URL again, now

**Comment by panlinux** [comment]
It works now, thanks!
