### ISSUE TITLE
searching for `bind` security updates crashes the server

### ISSUE THREAD

**Issue by panlinux** [canonical/ubuntu.com#14131]
This url:

https://ubuntu.com/security/notices?order=newest&release=&details=bind

is currently crashing the site, returning a 500 error.

**Comment by immortalcodes** [comment]
Hi,
Thanks for reporting this, we are in process of resolving this.

**Comment by mtruj013** [comment]
Hi @panlinux, this should be working for you now. Could you please confirm?
![image](https://github.com/user-attachments/assets/97ddf1e0-6f7b-4d9b-83f8-668bef9c8ba4)

**Comment by panlinux** [comment]
It's working great, thanks!
