### ISSUE TITLE
in https://launchpad.net/~ubuntu-users links to 404 http://www.ubuntu.com/community/ubuntustory/licensinga

### ISSUE THREAD

**Issue by kangarooo** [canonical/ubuntu.com#14147]
In https://launchpad.net/~ubuntu-users links to 404 http://www.ubuntu.com/community/ubuntustory/licensinga
Also https://ubuntu.com/community/ubuntustory/
Need to make subcategory in https://ubuntu.com/community/
![image](https://github.com/user-attachments/assets/e8742d9c-b3c4-4008-b052-92b002d74e0f)

---
*Reported from: https://ubuntu.com/community/ubuntustory/licensing*

**Comment by petesfrench** [comment]
Thanks for reporting, we will add some redirects to the most relevant pages so this doesn't happen again.

**Comment by immortalcodes** [comment]
Hey @kangarooo ,
If I understand it right, you wish to have subcategory added in the community page so that the links could re-direct to actual licenses? As of now, they just go to community page and that's it.
@petesfrench do you know more context on this?

**Comment by immortalcodes** [comment]
There have been some re-directions applied to avoid this.
Thanks for reporting @kangarooo
