### ISSUE TITLE
Incorrect EoL date for 22.04

### ISSUE THREAD

**Issue by btmorr** [canonical/ubuntu.com#14181]
End of life for 22.04 LTS HWE is listed as Aug 2024, as opposed to Apr 2027 which is listed here: https://ubuntu.com/about/release-cycle

---
*Reported from: https://ubuntu.com/kernel/lifecycle*

**Comment by ksacilotto** [comment]
The HWE kernels that are backports from interim releases have their end of life aligned with the interim release. The pages are still listing 22.04 HWE kernel as being based on 6.5, which was indeed phased out on Aug 2024. The current and last 22.04 HWE is based on 6.8, which will be supported for the same period as as the 22.04 GA 5.15 kernel, that is Apr 2027 for the standard support.

Both https://ubuntu.com/kernel/lifecycle and https://ubuntu.com/about/release-cycle#ubuntu-kernel-release-cycle pages need to be updated to reflect the 22.04 HWE kernel being based on 6.8 now.

**Comment by lizzochek** [comment]
Hello @btmorr. Thank you for filing an issue. We will update the dates. @ksacilotto please create a request for that via the form I provided.
