### ISSUE TITLE
500: Server error when signing up for Landscape SaaS

### ISSUE THREAD

**Issue by jpm-canonical** [canonical/ubuntu.com#14194]
When clicking "Get Landscape SaaS" here:

![Screenshot from 2024-08-19 15-17-34](https://github.com/user-attachments/assets/22fb813c-e556-4e65-9913-d4409e042c68)

Then filling in the form and submitting, I get this error:

![image](https://github.com/user-attachments/assets/3f5577bd-a9ff-4e83-9c65-948b29aeb569)

**Comment by petesfrench** [comment]
Thanks for reporting, this is being actively looked into

**Comment by mtruj013** [comment]
Fixed in linked pr, closing
