### ISSUE TITLE
Unable to acquire landscape account

### ISSUE THREAD

**Issue by black-vajra** [canonical/ubuntu.com#14206]
I just keep getting a server error when i get to the last step for saas (free)

**Comment by black-vajra** [comment]
from the Konsole:  Request a new registration for this computer now? [y/N]: y
Invalid account name or registration key.
Could not enable Landscape.
https://landscape.canonical.com/signup  takes me to "Manage Your SSO account" which takes me back to my account.  Tried to sign up for Landscape online but  kept getting a 500 error.  I disabled my VPN... same issue.

**Comment by black-vajra** [comment]
O.k. seems I'm not running an LTS distro on the server I'm trying to get service on so... O well.  Never mind.

**Comment by petesfrench** [comment]
Closing, the user has solved their own issue.

Also, if you have an issue with Landscape please open an issue on the relevant Landscape repository.
