### ISSUE TITLE
Pro token doesn't get copied to a clipboard

### ISSUE THREAD

**Issue by nobuto-m** [canonical/ubuntu.com#14210]
### Summary

In https://ubuntu.com/pro/dashboard, there is an icon next to the Pro token.

![dashboard](https://github.com/user-attachments/assets/e2d5b37c-2291-48e5-8b44-2508ed5fe154)

My understanding is that type of icons would copy the content to the system's clipboard so it's easier for users to paste it to somewhere else. However, by clicking the icon, nothing happens to the clipboard.

![dashboard_event](https://github.com/user-attachments/assets/9118cdcc-ef4c-47d2-a699-7391bcf4753d)

### Steps to reproduce the behavior

1. Go to https://ubuntu.com/pro/dashboard
2. Select a valid subscription
3. click the icon next to the Pro token

### Expected behavior

The Pro token gets copied to the system's clipboard.

### Browser/device details

- Firefox 129.0.1 on Ubuntu
- Chromium 127.0.6533.99 on Ubuntu

### Reported from

https://ubuntu.com/pro/dashboard

**Comment by petesfrench** [comment]
There was a decision to deprecate the use of  'Copy to clipboard' on our marketing sites. You can see this referenced in the change-log for Vanilla 3.0: https://vanillaframework.io/docs/migration-guide-to-v3#code

@minkyngkm Can you confirm whether this is the intended behavior please

**Comment by minkyngkm** [comment]
Hi, yep I think the copy-to-clipboard functionality used to be supported, but it seems it was removed in vanilla 3.0 as @petesfrench mentioned. We will create a ticket to add a custom function that restores the copy functionality. Thanks for reporting this issue @nobuto-m 👍
