### ISSUE TITLE
Install Ubuntu desktop tutorial navigation bar has "How to write a tutorial"

### ISSUE THREAD

**Issue by julian-klode** [canonical/ubuntu.com#14219]
### Summary

There seems to be an empty link to "tutorials" and a list of "How to write a tutorial" in the navigation bar at https://ubuntu.com/tutorials/install-ubuntu-desktop#1-overview

```
<div id="secondary-navigation" class="p-navigation is-secondary is-dark">
      <div class="p-navigation__row--25-75">
        <div class="p-navigation__banner">
          <div class="p-navigation__tagged-logo">
            <a class="p-navigation__link" href="/tutorials">
              <div class="p-navigation__logo-tag">
                <img class="p-navigation__logo-icon" src="https://assets.ubuntu.com/v1/82818827-CoF_white.svg" alt="">
              </div>
              <span class="p-navigation__logo-title">Tutorials</span>
            </a>
          </div>
          
            
              <a href="#" class="p-navigation__toggle--open" title="Toggle navigation"><i class="p-icon--chevron-down is-light"></i></a>
            
          
        </div>
        
        <nav class="p-navigation__nav" aria-label="Tutorials navigation">
          
            <ul class="p-navigation__items">
              
                
              
                
                  
                    
                    
                      
                      <li class="p-navigation__item ">
                        <a class="p-navigation__link" href="/tutorials/tutorial-guidelines#1-overview">How to write a tutorial</a>
                      </li>
                      
                    
                  
                
              

              
                
              
                
              
            </ul>
          
        </nav>
      </div>
    </div>
```

### Steps to reproduce the behavior

Go to web site, look at navigation bar

### Expected behavior

Don't see how to write a tutorial when reading a tutorial, or maybe it should be a list of other tutorials, but somehow only this one went in there?

### Browser/device details

Not relevant, but it's firefox on Ubuntu on large desktop

### Reported from

GitHub

**Comment by mtruj013** [comment]
Hi @julian-klode, the "How to write a tutorial" link is intentional and included on every tutorial. Please see [this](https://chat.canonical.com/canonical/pl/63nrksriobya7dbzf5tzh3nrsc) recent discussion regarding the matter. We have this [jira ticket](https://warthogs.atlassian.net/browse/WD-14404) already to track any changes our UX designers might be keen on regarding this, so I'm going to go ahead and close this issue as a duplicate. Thanks
