### ISSUE TITLE
Stuck in a page loop. 

### ISSUE THREAD

**Issue by Jw071** [canonical/ubuntu.com#14226]
### Summary

So I’ve had an in two account since like 2017 was the last time I’d actually logged in and I’m setting up a server. I wanted to try the free and pro so I go to register and I have to reset my password yada yada. I go to buy new sub subscription click on that and go through that page. You know this is for me. Whatever information was there and when I click the register button, I go back to the previous page where it said by new subscription and it’s just an endless loop of that actually have a video if you wanna see it.

### Steps to reproduce the behavior

Dashboard will have the link to buy M2 Pro go to that page fill it out. Go to the bottom where it says buy new subscription. Click that fill out the next page. Scroll out of the bottom where it says register click that go back to previous page once you’re there, it’s just back-and-forth between the two pages if you click the green button.

### Expected behavior

I was under the understanding that it would take my registration information or take me to another page and then it would supposedly go to check out where the fire prints said it would adjust my $500 payment down to zero for an individual and I never got past the register button

### Browser/device details

iPhone 13 Pro, iOS 17.5.1, and Firefox, which I just checked and there’s an update from three days ago that I need, l’ll let you know after I update and reboot

### Reported from

https://ubuntu.com/support/thank-you

**Comment by mtruj013** [comment]
@minkyngkm @abhigyanghosh30 could you have a look please? 🙏🏻

**Comment by abhigyanghosh30** [comment]
Hi @Jw071 
Could you let me know the email id for which you faced this issue?

**Comment by immortalcodes** [comment]
I am closing this issue because no further response was received, but please feel free to report another issue if you are still facing issues.
Thanks

**Comment by Jw071** [comment]
My apologies I didn’t have notifications turned on for this inbox. I
haven’t tried to go back and check again. I’ve kind of mothballed that
project to build a 32bit machine to run some old hardware but I’ll try to
get the account set-up soon.  I live in Western North Carolina in the FEMA
zone and my wired network is down but I’ll see about using my laptop to
finish the account set-up.

My apologies for the lack communication previously. I have enabled the
notifications and will jump on this ASAP.

**Comment by immortalcodes** [comment]
No issues @Jw071 , please report us back with the current issues you are facing and we would be able to help you right away.
Thanks
