### ISSUE TITLE
Grub2

### ISSUE THREAD

**Issue by angelodegiorgio** [canonical/ubuntu.com#14247]
### Summary

I have installed ubuntu along with windows before and had no problem with grub. On boot it will let you choose the operating system. In this last version, 24, I installed ubuntu with windows on 2 pc but grub does not pop up. One one pc windows loads windows automaticaly and the others ubuntu starts automatically. Please work on grub2. I have spent hours looking and trying solutions to make grub pop up.

### Steps to reproduce the behavior

see above

### Expected behavior

see above

### Browser/device details

Windows 10,  PC I7 gen 2, 20 gig memory, the other was laptop win 10, I3 gen ?

### Reported from

GitHub

**Comment by mtruj013** [comment]
Sorry to hear you're having trouble @angelodegiorgio. Unfortunately this repo deals with the ubuntu.com website only, not the Ubuntu OS. Please have a look [here](https://help.ubuntu.com/community/ReportingBugs) to file os related bugs
