### ISSUE TITLE
Outdated pricing example and 404 link for 18.04 on `For complete pricing, see Ubuntu Pro 18.04 LTS on the AWS Marketplace`

### ISSUE THREAD

**Issue by toabctl** [canonical/ubuntu.com#14263]
### Summary

`For complete pricing, [see Ubuntu Pro 18.04 LTS on the AWS Marketplace](https://aws.amazon.com/marketplace/pp/B0821T9RL2)` does mention an outdated 18.04 Pro LTS. Would be nice to have 24.04 Pro listed there.
Also the link doesn't exist.

### Steps to reproduce the behavior

look at the page

### Expected behavior

link works and points to a current LTS version

### Browser/device details

browser doesn't matter I would say

### Reported from

https://ubuntu.com/aws/pro

**Comment by lizzochek** [comment]
Hi @toabctl. Thank you for filing an issue. We are already on it and the issue will be fixed within this PR: https://github.com/canonical/ubuntu.com/pull/14266
