### ISSUE TITLE
500: Server error when opening "language models on ubuntu" website

### ISSUE THREAD

**Issue by Archdave** [canonical/ubuntu.com#14295]
https://ubuntu.com/blog/deploying-open-language-models-on-ubuntu

500: Server error

Something's gone wrong.

    The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Try reloading the page. If the error persists, please note that it may be a [known issue](https://github.com/canonical-websites/www.ubuntu.com/issues). If not, please [file a new issue](https://github.com/canonical-websites/www.ubuntu.com/issues/new).

**Comment by lizzochek** [comment]
Hello @Archdave. The page currently seems to be working fine. You might have tried to access it while it was building or encountered a temporary issue. If it still persists for you, please fill free to reopen the issue and provide more details
