### ISSUE TITLE
"See our Compliance Profiles" goes to the wrong place

### ISSUE THREAD

**Issue by setharnold** [canonical/ubuntu.com#14309]
### Summary

The "See our Compliance Profiles" button on https://ubuntu.com/security/compliance-automation currently goes to https://wiki.ubuntu.com/Security/Features . It probably should go to https://ubuntu.com/security/compliance-automation#compliance-profiles instead. (Though that's just a jump on the page. Maybe @lechsandecki will have a better place for it to land?)

### Steps to reproduce the behavior

1. Go to https://ubuntu.com/security/compliance-automation
2. Click on `See our Compliance Profiles`
3. Go to the security engineering wiki page on security features

### Expected behavior

Go to the marketing-friendly view of the security profiles available in Ubuntu Pro.

### Browser/device details

Firefox 130.0+build2-0ubuntu0.20.04.1 on Ubuntu Focal with the UBlock Origin and Tridactyl plugins, among others.

![2024-09-18_18-09](https://github.com/user-attachments/assets/d48e5e9b-1ac1-4e69-9300-d8aac4fb0b3c)

### Reported from

https://ubuntu.com/security/compliance-automation

**Comment by immortalcodes** [comment]
Hi,
Thanks for pointing this out, I have left a [comment](https://docs.google.com/document/d/13RcVvHBAoywfk3o5Dy-16F3KrMytL9-2v6wWbW444Ko/edit?disco=AAABV8SLRr4) for the stakeholder.
