### ISSUE TITLE
ubuntu 22.04 / 24.04 doesn't support wan modem fibocom L850, and doesn't have drivers

### ISSUE THREAD

**Issue by roma-ar** [canonical/ubuntu.com#14310]
### Summary

PC Thinkpad T15 Gen1, wan modem -Fibocom L850-GL

I tried to use modem in 3 versions of Ubuntu 20.04, 22.04, 24.04  -- and nothing, without success.
In versions 22.04, 24.04 the OS sees the modem but it's impossible to work, it has error that doesn't see the sim card, and I can't configure the APN.
 It works fine in windows.

How it's possible in as OS as Ubuntu it doesn't work a simple driver for wan ??????
Why developers of Ubuntu forgot to do as easy thing as an wan driver ???

For Thinkpad T460s the wan driver works but for new  Thinkpad T15 they didn't do the driver.

### Steps to reproduce the behavior

I tried to use modem in 3 versions of Ubuntu 20.04, 22.04, 24.04  -- and nothing, without success.
In versions 22.04, 24.04 the OS sees the modem but it's impossible to work, it has error that doesn't see the sim card, and I can't configure the APN.

### Expected behavior

I expect the developers will be create drivers for wan in a few months.
And all people with wan modems will receive drivers via OS update.

### Browser/device details

PC Thinkpad T15 Gen1 with wan modem -Fibocom L850-GL

### Reported from

GitHub

**Comment by immortalcodes** [comment]
Hi,
Thanks for reaching out, we mostly deal with the issues with in the Ubuntu site but you could reach out [here](https://ubuntu.com/support/community-support) for more help.
