### ISSUE TITLE
Ubuntu CL Cheat Sheet

### ISSUE THREAD

**Issue by Dadtron9000** [canonical/ubuntu.com#14344]
### Summary

Greetings. 
New user. After downloading the server files, I saw your Ubuntu Command Line Cheat Sheet.
While hovering over the 'Download' button does indicate a link, the link is not active and nothing happens.
Someone from the Ubuntu Community helped me find the resource and also suggested I file a bug report.
Thanks!

### Steps to reproduce the behavior

Click on 'Download the CLI Cheat Sheet'

### Expected behavior

Expected the down load to start. It never started.

### Browser/device details

Desktop Running Ubuntu Jelly

### Reported from

https://ubuntu.com/download/server/thank-you?version=24.04.1

**Comment by immortalcodes** [comment]
Hey, this should be fixed now.
Feel free to re-open this if issue persists.
