### ISSUE TITLE
500 Server Error on Repositories Docs

### ISSUE THREAD

**Issue by krytosvirus** [canonical/ubuntu.com#14374]
From my on-prem landscape server there is a link for [How to manage repositories in Landscape](https://ubuntu.com/landscape/docs/repositories)

The raw URL is `https://ubuntu.com/landscape/docs/repositories`

That page gives the general Ubuntu 500: Server Error page.

**Comment by immortalcodes** [comment]
Hi,
This link works now.
Thanks for reporting
