### ISSUE TITLE
link broken

### ISSUE THREAD

**Issue by surfrod** [canonical/ubuntu.com#14377]
### Summary

macOS link instructions (broken): https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-macos?_gl=1*1c5ubf5*_gcl_au*OTA5NTA5MDY0LjE3Mjc4MDU0MzA.&_ga=2.187751208.1291001555.1727805427-743268818.1727805427

original page:https://ubuntu.com/tutorials/create-a-usb-stick-on-windows#1-overview

### Steps to reproduce the behavior

as reported

### Expected behavior

fix link

### Browser/device details

mac mini / edge

### Reported from

GitHub

**Comment by immortalcodes** [comment]
Hey this link works now.
Thanks for reporting
