### ISSUE TITLE
Fix http into https, having signatures on http is not secure

### ISSUE THREAD

**Issue by aurianer** [canonical/ubuntu.com#14389]
### Summary

Two links on https://ubuntu.com/tutorials/how-to-verify-ubuntu#3-download-checksums-and-signatures are using http, that's not secure especially for communicating checksums.

### Steps to reproduce the behavior

1. Go to https://ubuntu.com/tutorials/how-to-verify-ubuntu#3-download-checksums-and-signatures
2. Click on the link proposed (without extensions like https everywhere)

### Expected behavior

It should redirect to https

### Browser/device details

- Firefox

### Reported from

GitHub

**Comment by britneywwc** [comment]
Hi @aurianer, thanks for raising an issue. There is a "Suggest changes" link on the bottom of the page, it will lead you to the Discourse post [here](https://discourse.ubuntu.com/t/how-to-verify-your-ubuntu-download/14010?_gl=1*9olfzc*_gcl_au*OTk2MTIyNDYwLjE3MjMxOTI5NjU.&_ga=2.250357318.1561326583.1728265352-702087744.1723192965) where you can directly suggest a change on the original post.
