### ISSUE TITLE
balenaEtcher

### ISSUE THREAD

**Issue by JD2D** [canonical/ubuntu.com#14397]
### Summary

The software should not be recommend as it corrupt usd stick and it not a got one.
Yumi is way better and really straitforwards.

alco mcaffee remove it from the download as it see it as virus

### Steps to reproduce the behavior

just using the tool as stated 

### Expected behavior

just create a pen drive bootable

### Browser/device details

dfdfdfdf

### Reported from

GitHub

**Comment by immortalcodes** [comment]
Hi,
Thanks for reaching out, if you are facing issues with this software, please reach out to https://github.com/balena-io/etcher/issues and report the problem.
