### ISSUE TITLE
test error 24.10 is not LTS

### ISSUE THREAD

**Issue by zombiedk** [canonical/ubuntu.com#14416]
### Summary

https://ubuntu.com/about/release-cycle

in the table with version number, there is a mistake where 24.10 is mentiond to be an LTS version

24.10 LTS (Oracular Oriole)

### Steps to reproduce the behavior

goto https://ubuntu.com/about/release-cycle
search for "24.10 LTS (Oracular Oriole)"

### Expected behavior

page should show "24.10  (Oracular Oriole)"

### Browser/device details

- any Browser version

### Reported from

https://ubuntu.com/about/release-cycle

**Comment by mtruj013** [comment]
Thanks for reporting @zombiedk, this is fixed now
