### ISSUE TITLE
Request for enhancement on lxd-windows tutorial

### ISSUE THREAD

**Issue by wideawakening** [canonical/ubuntu.com#14429]
### Summary

- tutorial: https://ubuntu.com/tutorials/how-to-install-a-windows-11-vm-using-lxd
- step: 3
- issue: when using a cluster setup and trying to `lxc config device` from a node that is not the same as where the instance is place, you get following error
  ```
  (from node03)
  
  $ lxc config device add win11 install disk source="/home/ubuntu/win11.lxd.iso" boot.priority=10
  Error: Failed add validation for device "install": Missing source path "/var/snap/lxd/common/lxd/win11.lxd.iso" for disk "install"
  
  $ ls -lh /var/snap/lxd/common/lxd/win11.lxd.iso
  -rw-r--r-- 1 ubuntu ubuntu 5.7G Oct 14 14:17 /home/ubuntu/win11.lxd.iso
  
  $ lxc info win11
  Name: win11
  Status: STOPPED
  Type: virtual-machine
  Architecture: x86_64
  Location: node01
  Created: 2024/10/17 07:10 UTC
  ```

- suggested solution: add a note on the tutorial raising notice on it
  > Make sure to launch this commands on the same node where the targeted instance is placed with `lxc info win11`
  
thx @VariableDeclared for helping me figure out what was happening

### Steps to reproduce the behavior

follow the tutorial and launch the pointed lxc command from a node different from the one where the instance is placed.

### Expected behavior

you will get previously pointed error

### Browser/device details

-

### Reported from

GitHub

**Comment by immortalcodes** [comment]
Thanks for reporting, this is in process.

**Comment by mionaalex** [comment]
@wideawakening I added a note as per your suggestion
