### ISSUE TITLE
The page doesn't include licenses for 24.04 and 24.10

### ISSUE THREAD

**Issue by toabctl** [canonical/ubuntu.com#14421]
### Summary

The page misses some newer ubuntu releases.

### Steps to reproduce the behavior

look at the page

### Expected behavior

24.04 and 24.10 

### Browser/device details

Firefox snap from 24.10

### Reported from

https://ubuntu.com/legal/open-source-licences

**Comment by immortalcodes** [comment]
Thanks for reporting this.
Please track further updates here on #14052
