### ISSUE TITLE
Padding-bottom missing from some sections on /desktop

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/ubuntu.com#14426]
page - https://ubuntu.com/desktop

The following should be wrapped in a `p-section`, so there's 4rem padding-bottom:

![image](https://github.com/user-attachments/assets/e9f9888f-ee6d-4a30-9db5-5d49946fe187)
![image](https://github.com/user-attachments/assets/db2c1ee3-84a5-48d0-b280-e398c521ecdc)

**Comment by Saurabhyadav0** [comment]
hey can u assing me this issuue
