### ISSUE TITLE
Broken logo strip on https://ubuntu.com/ai/roadshow

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/ubuntu.com#14420]
P-rule class on __items breaks it:
![image](https://github.com/user-attachments/assets/36ef58cb-a445-4a54-b077-e41abe08424c)

**Comment by lyubomir-popov** [comment]
more from here https://ubuntu.com/automotive/resources
![image](https://github.com/user-attachments/assets/a01640ac-7842-438f-9127-15e7331c24a1)

**Comment by petesfrench** [comment]
Closing: Looks like this was fixed in the aforementioned PR
