### ISSUE TITLE
Spelling mistake on FIPS 22.04 page

### ISSUE THREAD

**Issue by ariannatillett** [canonical/ubuntu.com#14441]
### Summary

There appears to be a typo of "includ" when this should say "include" on this webpage.

### Steps to reproduce the behavior

1. Go to https://ubuntu.com/security/certifications/docs/2204/fips
2. Scroll to "Pro channels"
3. In the paragraph under "fips" there appears to be a typo of "includ" when this should say "include" on this webpage.

### Expected behavior

The correct spelling for include.

### Browser/device details

Mac M1, Google Chrome

### Reported from

https://ubuntu.com/security/certifications/docs/2204/fips

**Comment by seniorLikeToCode** [comment]
![image](https://github.com/user-attachments/assets/aff4fe65-8d80-4b97-9704-f6852e95085d)

fix: inclue -> include

**Comment by seniorLikeToCode** [comment]
file path: templates/templates/docs/shared/_docs.html 
line 98: {{ document.body_html | safe }}

This line renders the information, but after inspecting the actual source, I couldn't find where the data is stored. So, where is the information actually located?

**Comment by immortalcodes** [comment]
Hey, this has been corrected.
Thanks a lot for reaching out.

**Comment by immortalcodes** [comment]
> file path: templates/templates/docs/shared/_docs.html line 98: {{ document.body_html | safe }}
> 
> This line renders the information, but after inspecting the actual source, I couldn't find where the data is stored. So, where is the information actually located?

BTW, these blogs are fetched from our discourse API and you can find this and more such blogs here
https://discourse.ubuntu.com/t/fips-for-ubuntu-22-04/39869

**Comment by seniorLikeToCode** [comment]
@immortalcodes thanks, surely I will check for future references too.
