### ISSUE TITLE
Error 500 on https://ubuntu.com/server/docs/install/autoinstall

### ISSUE THREAD

**Issue by DRSuydam** [canonical/ubuntu.com#14447]
Tried to get to https://ubuntu.com/server/docs/install/autoinstall this morning and received an error 500 on multiple devices via multiple networks. 

Also received it on https://ubuntu.com/server/docs/install/autoinstall-reference..

**Comment by immortalcodes** [comment]
Hey @DRSuydam ,
This has been fixed!
