### ISSUE TITLE
pithon

### ISSUE THREAD

**Issue by ericsaviane** [canonical/ubuntu.com#14469]
bonjour j'ai un souci avec python 3.10 dépendance insatisfaite et paquet gardés en l'état

**Comment by petesfrench** [comment]
Hi @ericsaviane, can you provide some more information on exactly what issue you are facing?

**Comment by ericsaviane** [comment]
j''ai installé tout les paquets python 310 dans synaptique j'ai pu envoyer  un rapport de crash dans le relevé du système et je n'ai plus de   dépendances insatisfaites

**Comment by ericsaviane** [comment]
j'ai installé pip aussi

**Comment by petesfrench** [comment]
So are you trying to run the project locally?

If you share the errors you are seeing with me I can see if I can help

**Comment by petesfrench** [comment]
This repository is for the website https://ubuntu.com/, not for the operating system. You can report an issue in the operating system [here](https://help.ubuntu.com/community/ReportingBugs).

However, this sounds more like a Python issue. I would have a look at the [Python docs](https://docs.python.org/) and see if there is any relevant information there.

I will close this issue as it is not relevant to the project.

**Comment by ericsaviane** [comment]
c'est python 3.10 et non python 3.13

**Comment by petesfrench** [comment]
If you go to the [link above](https://docs.python.org/) you find the different versions on the left hand side

![python_docs_v10](https://github.com/user-attachments/assets/fc856e87-6047-4c8e-a2a5-6e72a0505dd2)
