### ISSUE TITLE
"503 Service Unavailable" for URL https://ubuntu.com/credentials/

### ISSUE THREAD

**Issue by Suman99pro** [canonical/ubuntu.com#14464]
Hello there,
I was going through the cannonical credential page and ran into 503 Service Unavailable. Is it a maintenance downtime or an issue?
The URL is https://ubuntu.com/credentials/
<img width="959" alt="image" src="https://github.com/user-attachments/assets/81bb1a6b-8e30-4888-90ce-c36de4b6610a">

**Comment by Suman99pro** [comment]
Also cannot access https://login.ubuntu.com, "ERR_CONNECTION_TIMED_OUT"

**Comment by seniorLikeToCode** [comment]
I checked both links and It is working as it should be. So better to close this issue. @anthonydillon

**Comment by anthonydillon** [comment]
Thanks closing 👍
