### ISSUE TITLE
Repeated content on cheat sheet

### ISSUE THREAD

**Issue by kobenauf** [canonical/ubuntu.com#14471]
### Summary

On the Cheat Sheet, page 2, these sections appear twice:
Firewall management
SSH and remote access

It looks like a copy/paste mistake.

### Steps to reproduce the behavior

1. Open the Ubuntu Server CLI cheat sheet:
https://assets.ubuntu.com/v1/3bd0daaf-Ubuntu%20Server%20CLI%20cheat%20sheet%202024%20v6.pdf
2. Go to Page 2.

### Expected behavior

No duplicate content

### Browser/device details

N/A

### Reported from

https://ubuntu.com/download/server/thank-you?version=24.04.1

**Comment by immortalcodes** [comment]
Thanks for reporting, this is duplicate for #13846 
Please track further actions here.
