### ISSUE TITLE
Is this a known issue? Cannot login, and got the below message

### ISSUE THREAD

**Issue by newhavenyankee** [canonical/ubuntu.com#14481]
Something's gone wrong.

Your browser session appears to be missing the expected authentication macaroon.

If the error persists, please note that it may be a [known issue](https://github.com/canonical-websites/www.ubuntu.com/issues). If not, please [file a new issue](https://github.com/canonical-websites/www.ubuntu.com/issues/new).

**Comment by immortalcodes** [comment]
Hrey @newhavenyankee ,
Could you please provide more context on it!

**Comment by immortalcodes** [comment]
I am closing this issue due to lack of context, but @newhavenyankee please feel free to re-open this more context.
Thanks for reaching out to us!

**Comment by newhavenyankee** [comment]
Closing it is fine. It seems to have been a one-off.

Sorry for any wasted time.
