### ISSUE TITLE
WTF is wrong with you people

### ISSUE THREAD

**Issue by WeStartThen** [canonical/ubuntu.com#14518]
### Summary

Really... minimal server install ships with no text editor?  Who's the fucking clown that signed off on that?  Should be ashamed of yourself.  What a fucking joke.

### Steps to reproduce the behavior

Install ubuntu server 24.04.1 minimal without correct internet config.  Struggle for hours.

### Expected behavior

I would expect to have vi, nano, something anything.  What the fuck.

### Browser/device details

Any machine.  It's your distro's fault.

### Reported from

https://ubuntu.com/blog/tag/ubuntu-24-04-lts

**Comment by britneywwc** [comment]
Closing this as it does not comply with the [Ubuntu Code of Conduct](https://ubuntu.com/community/ethos/code-of-conduct), thanks.
