### ISSUE TITLE
outdated os releases

### ISSUE THREAD

**Issue by Kevinisagirl21** [canonical/ubuntu.com#14521]
### Summary

Packages on GitHub are from 21.10, and [ubuntu's site(https://ubuntu.com/download/desktop) shows the latest release as 24.04.1.

p.s. on your [GitHub Actions page](https://github.com/canonical/ubuntu.com/actions) most of the workflows are failing

### Steps to reproduce the behavior

Go to the [Ubuntu GitHub page](https://github.com/canonical/ubuntu.com/releases), look at releases, and compare to [ubuntu.com](https://ubuntu.com/download/desktop)'s latest release.

### Expected behavior

releases should be different

### Browser/device details

Google Chrome

### Reported from

GitHub

**Comment by akbarkz** [comment]
@Kevinisagirl21 Thanks for reporting this. We don't use Ubuntu OS related release names for our website anymore. As a matter of fact we don't use Releases for the website anymore. We just deploy changes on a daily basis and do not relate them to a specific Ubuntu OS release. As you can see yourself from https://github.com/canonical/ubuntu.com/releases the last time it was done like that was back in 2021.
