### ISSUE TITLE
Etcher URL needs updated on Ubuntu image flashing tutorial

### ISSUE THREAD

**Issue by dhenrich** [canonical/ubuntu.com#14520]
### Summary

Etcher has moved their site to https://etcher.balena.io/ so the tutorial needs updated.

### Steps to reproduce the behavior

...

### Expected behavior

...

### Browser/device details

...

### Reported from

GitHub

**Comment by britneywwc** [comment]
Hi @dhenrich, thank you for raising an issue. Could you please specify which tutorial that the Etcher URL has to be updated on?

**Comment by dhenrich** [comment]
https://ubuntu.com/tutorials/create-a-usb-stick-on-macos

**Comment by britneywwc** [comment]
Thanks @dhenrich! I have updated the link, you should be able to see it live on https://ubuntu.com/tutorials/create-a-usb-stick-on-macos#4-install-and-run-etcher now. Closing this as solved.
