### ISSUE TITLE
500 Gateway Error

### ISSUE THREAD

**Issue by raymoncada** [canonical/ubuntu.com#14535]
When I try to register an account the site crashes, 500: Server error.
https://ubuntu.com/login?next=/pro/dashboard?

**Comment by learnlinuxnow** [comment]
Same here for https://ubuntu.com/login

I get either 500:Server Error or 504 Gateway Time-out

**Comment by samhotep** [comment]
@raymoncada @learnlinuxnow can you try again now?

**Comment by raymoncada** [comment]
Thank you that worked.

**Comment by raymoncada** [comment]
Thanks

**Comment by britneywwc** [comment]
Closing this as it has been solved, thanks.
