### ISSUE TITLE
Clicking Pay with PayPal then returning to the website goes to 'Thank you for your contribution'

### ISSUE THREAD

**Issue by Ads20000** [canonical/ubuntu.com#3244]
Clicking 'Cancel and return to Canonical' (or similar, can't remember exactly what it said, but it's in the bottom-left) on the PayPal donate page (reached by clicking Pay with PayPal at the bottom of [the Donate page](https://www.ubuntu.com/download/desktop/contribute)) produces the 'Thank you for your contribution' webpage even though I haven't contributed any money!

---
*Reported from: https://www.ubuntu.com/download/desktop/thank-you?country=GB

**Comment by steverydz** [comment]
@Ads20000 Thanks for taking the time to file an issue. I agree this is confusing. We'll hopefully have some time soon to review this.

**Comment by anthonydillon** [comment]
This is not stale and is valid. Just low priority...
