### ISSUE TITLE
Robotics takeover - build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical/ubuntu.com#3983]
BRIEF:
https://docs.google.com/document/d/1kfXy2xqOJQ8ZfsOXM6XBfUp9ztz9PJfjj7yE9dW4UHo/edit

WHITEPAPER:
https://drive.google.com/open?id=1pk8j0wuPsfwmaRSrTwaU8MTH_frFX2EV

START DATE: 24TH SEPTEMBER
END DATE: TBD

TO ALTERNATE WITH 'IOT APP STORE' TAKEOVER

**Comment by anasereijo** [comment]
@anthonydillon 
final design [here](https://github.com/ubuntudesign/www.ubuntu.com-design/issues/157)
[robot illustration](https://assets.ubuntu.com/v1/da1043ab-robot.svg)
gradient: `background-image: linear-gradient(-44deg, #171717 0%, #181818 9%, #262626 34%, #2D2D2D 67%, #383838 88%, #2E2E2E 100%, #393939 100%);`

How do you want me to save the background lines? all together as a svg ? thanks
