### ISSUE TITLE
“What would you like to talk to us about?” suggests forgetfulness

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical/ubuntu.com#4437]
1\. Go to any ubuntu.com page that has a “Contact us about _X_” link in the body. For example, ~~there are four on the “Plans and pricing” page, and~~ there is one on [/server](https://ubuntu.com/server), one on [/server/hyperscale](https://ubuntu.com/server/hyperscale), and three on [the Kubernetes page](https://www.ubuntu.com/kubernetes).
2\. ~~Click the link~~ Right-click the link and choose “Open in New Tab” / “Open in New Window”.
3\. Note the `<title>` of the contact page.
4\. Note the main heading on the page.
5\. Scroll down to the last field in the form.

What happens:
3\. The title has the form “Contact us | _X_ | Ubuntu” or “Contact Canonical | _X_ | Ubuntu”.
4\. The main heading is, appropriately, “Contact us about _X_” or “Contact Canonical about _X_”. (On /kubernetes this is currently masked by #5641.)
5\. The final field, however, is labelled “Your comments” — “What would you like to talk to us about?”

![ubuntu com-contact-comments](https://user-images.githubusercontent.com/19801137/49084229-be59f880-f246-11e8-8e02-fdae67676d50.png)

What should happen:
5\. The field should not be labelled as if we’ve just forgotten what you want to talk about.

Instead, perhaps “What would you like to know about _X_?” or “How can we help you with _X_?”

How to tell whether this is a good idea: Measure the proportion, of everyone who follows one of those links, that ends up submitting the form.

---
*Reported from: https://www.ubuntu.com/support/plans-and-pricing*

**Comment by anasereijo** [comment]
@caldav any thoughts about this?

**Comment by tbille** [comment]
Closing the issue since page doesn't exist anymore.

**Comment by matthewpaulthomas** [comment]
Unfortunately, the problem exists as described for the same three examples as it did last August. On [the Kubernetes page](https://ubuntu.com/kubernetes), the three “Contact us” buttons are now two “Get in touch” buttons, but they lead to the same forgetful form.

![image](https://user-images.githubusercontent.com/19801137/81172556-5c9ed180-8f96-11ea-86dc-70a3f85f7e7f.png)

I had assumed that the problem was a generic label in a shared form template. So I’m surprised to discover, now, that it’s actually [individual labels in 19 separate forms](https://github.com/canonical-web-and-design/ubuntu.com/search?q=%22What+would+you+like+to+talk+to+us+about%22), making it much easier to fix. It’s possible that _one_ of those is a generic form that should still ask “What would you like to talk to us about?” — though I doubt even that, since the “Contact us” link in the global footer doesn’t go to a form at all.

**Comment by pmahnke** [comment]
@matthewpaulthomas while I understand your larger point:

1. You _could_ assume we want to know what they want to talk about in reference to the larger topic.  If we expected them to just type 'Kuberbetes' again, we wouldn't even need the question, would we?
2. Most people use the modal form now, these are far less important.
3. It is not a small amount of work to add to every use of the include to get this done and documented in the copy docs.

If you update ALL the copy docs, I will consider doing this work.

**Comment by sowasred2012** [comment]
@pmahnke can this be closed?
