### ISSUE TITLE
Reporting a trademark violation asks nonsense questions

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical/ubuntu.com#4893]
1\. Try to report a violation of an Ubuntu or Canonical trademark.

What happens:
1. [ubuntu.com](https://www.ubuntu.com/) links to “[Legal information](https://www.ubuntu.com/legal)”. So far so good.
2. That legal terms page links to “[Trademarks](https://www.ubuntu.com/legal/trademarks)”. Cool.
3. The Trademarks page does not mention how to report a trademark violation. Huh.
4. If you’re really determined, you’ll find that the sibling “[Terms and policies](https://www.ubuntu.com/legal/terms-and-policies)” page links to “[View intellectual property policy](https://www.ubuntu.com/legal/intellectual-property-policy)”.
5. That “Intellectual property _rights_ policy” page says: “[Please contact us](https://www.ubuntu.com/legal/terms-and-policies/contact-us): …to report a breach of our IPRights Policy.”
6. The linked “Trademark enquiries” page asks nonsense questions:
    - “In what capacity are you requesting to use the trademark?” — you’re not
    - “In what capacity do you propose to use the Ubuntu trademark?”  — again, you’re not
    - “Please describe your request in more detail:” — it’s not a request
7. Meanwhile, there is a “[Trademark violation](https://forms.canonical.com/trademarkviolation/)” form with relevant fields (e.g. “Site where the trademark violation exists”), but it doesn’t seem to be linked to from anywhere.

What should happen:

3\. The “Trademarks” page should mention how to report a trademark infringement.
5\. Either the “Intellectual property rights policy” page should link to a separate, correct form for reporting infringements…
6\. …or the “Trademark enquiries” form should change its contents based on whether you are making a request or reporting an infringement.
7\. If the forms.canonical.com page is no longer used, it should be retired, since it’s showing up in Web search results.

---
*Reported from: https://www.ubuntu.com/legal/intellectual-property-policy*

**Comment by matthewpaulthomas** [comment]
The problem still exists exactly as described.

**Comment by tbille** [comment]
Can this be reported to legal.
Thanks.

**Comment by carkod** [comment]
This seems to be slale? Wouldn't you report a trademark violation to the trademark's office? This is just an informative page.
