### ISSUE TITLE
Marketo libs should only be loaded on pages where and when required

### ISSUE THREAD

**Issue by barrymcgee** [canonical/ubuntu.com#5230]
## Summary

Marketo JS library (97K) is currently being loaded on pages which will never use them, increasing page weight and page load times. Worse still, those libs then load jQuery.

<img width="892" alt="Screenshot 2019-05-30 at 16 43 09" src="https://user-images.githubusercontent.com/505570/58644870-178c0d00-82fa-11e9-9634-ea337f1a7dc5.png">

## Current and expected result

These libs should be loaded only if needed. On page load, JS could search for the existence of a Marketo identifiers and load the lib accordingly.

**Comment by carkod** [comment]
We are using a marketo endpoint now.
