### ISSUE TITLE
Pricing page minimums and exclusions

### ISSUE THREAD

**Issue by cjohnston1158** [canonical/ubuntu.com#5343]
Is it possible to add the * for OpenStack and Kubernetes to indicate that minimums and exclusions apply? This is confusing for customers who read this and think that they can purchase support for 1 machine and get OpenStack/Kubernetes support.

---
*Reported from: https://ubuntu.com/pricing/infra*

**Comment by carkod** [comment]
Thanks. @cjohnston1158 could you add it in the [copy doc](https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit)?
