### ISSUE TITLE
Livepatch datasheet omits HWE for 16.04 LTS / 18.04 LTS

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical/ubuntu.com#6101]
According to [wiki.ubuntu.com/Kernel/Livepatch](https://wiki.ubuntu.com/Kernel/Livepatch), Livepatch is available on HWE kernels for 14.04 LTS, 16.04 LTS, or 18.04 LTS.

According to [the ubuntu.com Livepatch datasheet](https://assets.ubuntu.com/v1/ef19ede0-Datasheet_Livepatch_AW_Web_30.07.18.pdf), it’s available on HWE kernels only for 14.04 LTS.

One of these is wrong, probably the datasheet, and should be fixed.

[Discovered during review of #6070.]

**Comment by petesfrench** [comment]
Closing, it looks like the data has been updated:
![image](https://github.com/user-attachments/assets/dfce66ab-4f0a-4bfe-9afa-b09626a44523)
![image](https://github.com/user-attachments/assets/0518ff45-40c0-4565-b106-09c382f7d25e)
