### ISSUE TITLE
redesign generic contact us page

### ISSUE THREAD

**Issue by anasereijo** [canonical/ubuntu.com#6105]
- [ ] UX to relook at this and make suggestions (@matthewpaulthomas)

- [ ] Redesign of this page following UX suggestions and improving the visual (@anasereijo)

- [ ] Build following Design and UX guidelines (developer)

- [ ] Find and update all pages using this (developer)

---

Individual issues:

- [ ] The intro sentence is styled as `p-heading--four`. There doesn’t seem to be a reason for this, and it results in four different font sizes in the page body (not counting the Captcha), which is probably too many.

- [ ] “Just” is a bit condescending, and “fill in the form below” is obvious. The sentence could be just: “A member of our team will be in touch within one working day.”

- [ ] `<fieldset>` is useful when a form is so complex and dense that headings and spacing alone aren’t enough to help people find elements or understand their relationships. This form is not that complex, so the fieldsets just makes the form noisier, taller, and slightly (and awkwardly) narrower.

- [ ] The fieldset headings are marked up as `<h3>`. If the `<fieldset>`s are retained, their headings really should be `<legend>`, otherwise they should be `<h2>` since they’re the child of an `<h1>`.

- [ ] [The generic contact form](https://ubuntu.com/contact-us/form?product=generic-contact-us) is the one version where “What would you like to talk to us about?” is an appropriate question, because we actually don’t know. Further spread of #4437 could be reduced by adding a source-code comment here, warning people to customise that question whenever they copy the code elsewhere.

- [ ] “I agree to receive information about Canonical’s products and services” reads as if it’s a compulsory GDPR checkbox for allowing responses. More understandable would be “Also notify me of events and new products”. ([blog.ubuntu.com#520](https://github.com/canonical-webteam-archive/blog.ubuntu.com/pull/520) is a previous attempt to fix one case.)

- [ ] “In submitting this form…” is positioned really close to the checkbox, as if it’s a caption for the checkbox itself, when really it applies to the form as a whole. It should be further away.

- [ ] If “Any questions? Call us” was correct, there would be no point to the contact form, because you’re supposed to call us instead. Better would be “Prefer to call us?” or similar.

Feel free to split out any of these issues that are complicated or contentious.

[From review of [charmed-osm.com#2](https://github.com/canonical-web-and-design/charmed-osm.com/pull/2).]

---
*Reported from: https://ubuntu.com/contact-us/form?product=generic-contact-us*

**Comment by matthewpaulthomas** [comment]
Thanks @anasereijo, I was about to report the same, so I’ve pasted in my cleaned-up list of issues.

**Comment by carkod** [comment]
Stale. Open an new updated issue witht he latest contact us if this still applies.
