### ISSUE TITLE
/advantage table row anchors hide the purpose of the table

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical/ubuntu.com#6110]
1\. Go to any of these URLs:
- https://ubuntu.com/advantage/#esm
- https://ubuntu.com/advantage/#livepatch
- https://ubuntu.com/advantage/#fips

What happens:
👍 The relevant row in the “Plans for enterprise use” table is highlighted.
👎 The page is scrolled so that nothing is visible above that table row.

What’s wrong with this:
- Linking to an anchor on a separate page is unusual, so we need to be more careful than usual about ensuring people understand where they’ve ended up.
- Unless you scroll, you can’t even see the table headers, so you don’t know what the table columns are for.
- Unless you scroll, you can’t see the section heading, so you don’t know what the entire table is for.

What should happen:
👍 The relevant row in the “Plans for enterprise use” table is highlighted.
👍 The page is scrolled so that the “Plans for enterprise use” heading and table headers are visible.

[Encountered while reviewing #6085.]

**Comment by matthewpaulthomas** [comment]
Low priority because (AFAIK) nothing is currently linking to these anchors.

**Comment by anasereijo** [comment]
@matthewpaulthomas are we moving this to next iteration? I think this should be in an epic and in the spreadsheet

**Comment by matthewpaulthomas** [comment]
@anasereijo I scheduled this for 19-46 because Ant was fixing a bunch of /advantage issues at the same time, but I neglected to assign it to him. Fortunately that didn’t matter, because (as I wrote above) we aren’t currently using these anchors, which is why it is Low. I don’t know why it’s scheduled now, and I don’t think any issue should be scheduled but not assigned.

**Comment by carkod** [comment]
I don't think this is relevant? The Ubuntu pro changed dramatically
