### ISSUE TITLE
[UA dashboard] Add the ability to refresh a token

### ISSUE THREAD

**Issue by anthonydillon** [canonical/ubuntu.com#6204]

**Comment by britneywwc** [comment]
@minkyngkm @abhigyanghosh30 Could you guys please have a look? Have we added the ability to refresh tokens on the Pro dashboard? As far as I can see from the current Pro dashboard there's no refresh token option for my Free Personal Token.

**Comment by abhigyanghosh30** [comment]
> @minkyngkm @abhigyanghosh30 Could you guys please have a look? Have we added the ability to refresh tokens on the Pro dashboard? As far as I can see from the current Pro dashboard there's no refresh token option for my Free Personal Token.

I don't think we have implemented this yet
