### ISSUE TITLE
developer.ubuntu.com/most-paths redirect to a 404

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical/ubuntu.com#6214]
**Example A**

1\. Go to https://developer.ubuntu.com/api/apps/qml/sdk-15.04.1/Ubuntu.Components.Themes.Palette/

What happens: You’re redirected to https://ubuntu.com/desktop/developersapi/apps/qml/sdk-15.04.1/Ubuntu.Components.Themes.Palette, but it’s a 404.

**Example B**

1\. Go to https://developer.ubuntu.com/api/devel/ubuntu-13.10/python/MessagingMenu-1.0

What happens: You’re redirected to https://ubuntu.com/desktop/developersapi/devel/ubuntu-13.10/python/MessagingMenu-1.0, but it’s a 404.

**What should happen**

- https://developer.ubuntu.com/anything should not redirect to https://ubuntu.com/desktop/developersanything*, because it doesn’t exist.
- Instead, we should redirect to a generic “Developer site is closed” 410 page, containing the original URL, so that you can (for example) copy and paste the URL into the Wayback Machine.

---
*Reported from: https://ubuntu.com/desktop/developerstoolkit*

**Comment by anthonydillon** [comment]
@caldav could you look at this? Do you have a logical mapping?

@matthewpaulthomas agree but would suggest we report a "410: Gone" which indicates that the resource requested is no longer available and will not be available again.

**Comment by matthewpaulthomas** [comment]
If we have a list of every page that no longer exists, then yes, returning 410 Gone for each of those — and 404 for any that never existed — would be ideal. I don’t expect that we do have such a list, though, and it would be a lot of effort for such a small distinction.

Meanwhile, I realise a drawback of my proposal, regardless of error code: it would require us to resume serving HTML from developer.ubuntu.com at all, whereas currently we don’t. That probably has more technical overhead, and would require some sort of barebones visual design.

But it’s still obviously a bug that, for example, https://developer.ubuntu.com/webapp-generator/ redirects to https://ubuntu.com/desktop/developerswebapp-generator. Nobody intended that to happen.

So, alternative proposal: We add a “Developer site is closed” page on ubuntu.com — at, say, `ubuntu.com/developers` — and use that as a catch-all redirect destination. The page can display the URL you entered (to allow copying and pasting), plus links to the top-line items from [ubuntu.com’s Developer menu](https://ubuntu.com/#developer) as likely next steps.

**Comment by carkod** [comment]
If we don't have any specific pages to redirect to, I think we can simply reroute all `/whatever` to https://ubuntu.com/desktop. If we agree, I can work on this.

**Comment by carkod** [comment]
This move has been around for so long now, that I think most users who visited https://developer.ubuntu.com/api/apps/qml/sdk-15.04.1/Ubuntu.Components.Themes.Palette/ probably are used to being redirected to https://ubuntu.com/desktop/developers, so my worry is that creating now a new page for this could be very confusing. So I'm closing this in favor of leaving it to redirect to /desktop/developers, feel free to open for new proposals/suggestions.
