### ISSUE TITLE
CVEs: Allow regex search in descriptions and package names

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical/ubuntu.com#8023]
Regexes would allow, for example, searching for CVEs:
- in all the various Linux kernel packages at the same time
- in a package and its specific dependencies at the same time
- that have descriptions using the word “overflow”, “overflows”, or both

From @nottrobin  in #7883:
> The regex version probably needs a tiny bit more consideration - e.g. how do you indicate you're entering a regex rather than a package name? Is there overlap between regex control characters (e.g. `.`) and existing package names? Most people will not be expecting to talk regex, and almost certainly won't know how.

**Comment by matthewpaulthomas** [comment]
@albertkol I have no opinion on how important this is. If it’s implemented, the only UI change required will be dropping [the requirement](https://docs.google.com/document/d/1VuAElUpFay7MBFNmE3NhSyY9TkXiqHcA1ZHQ11AYO-Q/edit#heading=h.aoek8nxke7k9) that “The ‘Package:’ field should allow only valid characters for source package names” — it should then also allow the characters that signify regular expression patterns.

**Comment by carkod** [comment]
This work should by covered by https://warthogs.atlassian.net/browse/WD-162
