### ISSUE TITLE
Consume ISOs & checksums from APIs

### ISSUE THREAD

**Issue by nottrobin** [canonical/ubuntu.com#8063]
For appliance pages (e.g. [Plex](https://ubuntu.com/appliance/plex)) and releases (e.g. [20.04 desktop](https://ubuntu.com/download/desktop/thank-you?version=20.04.1&architecture=amd64)), we hard-code the checksums in [`appliance.yaml`](https://github.com/canonical-web-and-design/ubuntu.com/blob/master/appliances.yaml#L13) and [`releases.yaml`](https://github.com/canonical-web-and-design/ubuntu.com/blob/master/releases.yaml#L26).

Both of these should be pulled directly from the server where the ISO is hosted, so we don't need to manually manage these checksums. We should update the download thank-you pages and the appliance pages to read the files instead.

All appliance checksums [are here](http://cdimage.ubuntu.com/ubuntu-core/appliances/SHA256SUMS), the release checksums are [stored by version](https://releases.ubuntu.com/20.04.1/SHA256SUMS).

**Comment by anthonydillon** [comment]
This is captured in the improvements to the release process project. cc: @akbarkz
