### ISSUE TITLE
Some users are missing "Start using your appliance" step

### ISSUE THREAD

**Issue by anthonydillon** [canonical/ubuntu.com#8108]
## Summary
On the [appliace installation pages](https://ubuntu.com/appliance/nextcloud/vm#windows) users are missing the "Start using your appliance" section at the bottom of the instructions. This is likely due to looking like totally different content.

 Leading to issues such as: https://github.com/canonical/multipass/issues/1692.

## Process
- Go to https://ubuntu.com/appliance/nextcloud/vm#windows
- Look through the steps 
- At the end, there is a grey strip which users are missing

## Current and expected result
- It should be more clear this is a further action the user needs to take

![image](https://user-images.githubusercontent.com/1413534/90413528-7d52e900-e0a6-11ea-8a37-e8a83d55a2fe.png)

**Comment by pmahnke** [comment]
@anthonydillon do you think we should copy that info into a final step and rewrite the grey box text?

**Comment by anthonydillon** [comment]
I originally thought adding it as a final 5th step would be good but even having it in the same strip. As a row below, the user is likely to follow it. The 4th step could also do with a different title if we require them to do something else. @rhys-the-davies

**Comment by rhys-the-davies** [comment]
Could we replace 'That's it' as a step title with 'Start using your x Ubuntu Appliance' and move the more detailed instructions up and merge them with step 4 (in this case)?

**Comment by carkod** [comment]
Maybe this needs some UX? Can you take a look when you've got time @juanruitina ?
