### ISSUE TITLE
Print formatting is bad at www.ubuntu.com/uasd

### ISSUE THREAD

**Issue by andrewjamessinclair** [canonical/ubuntu.com#8201]
When printing the page at www.ubuntu.com/uasd, there are some messy page breaks at the top of the document and the spacing between list items is very tight (perhaps that's intentional, but it's not consistent with the browser view of that page).

**Comment by barrymcgee** [comment]
## List of items to address

- [ ] The spacing between line items in a ordered list is very tight
- [ ] Spacing above and below tables is very tight
- [ ] Sidebar headings are printed
- [ ] Large blank whitespaces at top of page

**Comment by barrymcgee** [comment]
I dug into this a little to see why the content was being pushed onto the next page in print preview, what I found;

- This only happens on pages where the content is generated from a markdown file
- There's no much rhyme nor reason as to when the content is pushed onto the next page

You can resolve it replicate the bug by removing all content bar the first header and a the first table. You can then fix it by removing the table. However, if you add all content back, bar the table, the bug reappears.

This is as far as I have got so far.

**Comment by anthonydillon** [comment]
This has been improved in the last 6 months.
