### ISSUE TITLE
All download links have `_ga` trailing garbage

### ISSUE THREAD

**Issue by panlinux** [canonical/ubuntu.com#8335]
Hi,

all download links from this page have `_ga` trailing text added to them, which end up being in the downloaded filename. Example:
```
$ wget https://cdimage.ubuntu.com/ubuntu-core/18/stable/current/ubuntu-core-18-amd64.img.xz?_ga=2.40128800.321193887.1600693608-2043246893.1567707049
--2020-09-22 09:39:11--  https://cdimage.ubuntu.com/ubuntu-core/18/stable/current/ubuntu-core-18-amd64.img.xz?_ga=2.40128800.321193887.1600693608-2043246893.1567707049
Resolving cdimage.ubuntu.com (cdimage.ubuntu.com)... 91.189.88.247, 91.189.88.248, 91.189.91.124, ...
Connecting to cdimage.ubuntu.com (cdimage.ubuntu.com)|91.189.88.247|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 312596556 (298M) [application/x-xz]
Saving to: ‘ubuntu-core-18-amd64.img.xz?_ga=2.40128800.321193887.1600693608-2043246893.1567707049’

ubuntu-core-18-amd64.img.xz?_ga=2.40128800.321193887 100%[=====================================================================================================================>] 298,12M  9,70MB/s    in 29s     

2020-09-22 09:39:40 (10,4 MB/s) - ‘ubuntu-core-18-amd64.img.xz?_ga=2.40128800.321193887.1600693608-2043246893.1567707049’ saved [312596556/312596556]
```

---
*Reported from: https://ubuntu.com/download/kvm*

**Comment by pmahnke** [comment]
That _ga code is from google analytics.  It might not be possible to remove it and leave GA on the site.

I will look for some non-hacky way of doing it, but inital searches make it seem impossible, might be easier to make that just a code block if you think people will only be copying the link, not downloading from the page.

**Comment by carkod** [comment]
@pmahnke any luck with this? I think the best way is still doing it on the user's end

**Comment by anthonydillon** [comment]
Sorry I must have missed this issue. I believe it's the Conversion Linker tag from GTM.

**Comment by anthonydillon** [comment]
Since moving to documentation this has been removed.
