### ISSUE TITLE
Headers are not aligned

### ISSUE THREAD

**Issue by anthonydillon** [canonical/ubuntu.com#8510]
On small screens nothing in the header lines up nicely:
![Screenshot_20201017-101718](https://user-images.githubusercontent.com/1413534/96333477-162fc180-1062-11eb-9747-75ef42acb7f1.jpg)

**Comment by albertkol** [comment]
@anthonydillon 

I am not sure I see it.

![image.png](https://images.zenhubusercontent.com/5ee7415a47536a7869302593/d1074964-6dba-4b07-958f-52338b232e75)

Can you give more details? I'd gladly work on it.

Do you mean the canonical logo not aligning with the ubuntu logo?

**Comment by anthonydillon** [comment]
Exactly and for bonus points the enterprise and download should be flush to the gutter.

**Comment by britneywwc** [comment]
I believe the headers and navigation items are aligned properly now. Closing this issue as resolved, thanks!
