### ISSUE TITLE
Refresh desktop metrics with 20.04 LTS data

### ISSUE THREAD

**Issue by jibel** [canonical/ubuntu.com#8515]
## Summary

https://ubuntu.com/desktop/statistics shows data for 18.04 and is more than 2 years old. It be nice to refresh it with data for 20.04 LTS.
I can provide the required data to build this page if needed.

**Comment by pmahnke** [comment]
@jibel it would be great to update the page.  We should have pushed for data, but the original idea was to update each LTS.  What's the best way, should we make a spreadsheet of the data we need?  Is the graphana dashboard still right?

**Comment by jibel** [comment]
The dashboard is still right, but if you prefer a spreadsheet that's fine too. Tell me what works best for you.

**Comment by anthonydillon** [comment]
@tbille this is what your planning to do, right?

**Comment by anthonydillon** [comment]
@pmahnke what is the status on this one?

**Comment by ChrisCheney** [comment]
Why isn't this page continuously up to date? It shouldn't be that hard to do.

The data is being collected continuously but the page being several years stale, combined with news articles about it just being spyware, gives a bad impression to end users making them wonder if it really is just for spying.

**Comment by petesfrench** [comment]
@pmahnke Are we still planning to this?

**Comment by pmahnke** [comment]
yes, we should... likely needed some UX and design to show multiple
versions, but we could start by having a 18.04 and 20.04 version.

**Comment by anthonydillon** [comment]
This page has been removed.
