### ISSUE TITLE
Show a more informative error for Discourse API problems

### ISSUE THREAD

**Issue by nottrobin** [canonical/ubuntu.com#8700]
We've had some issues in the past with retrieving content from the Discourse API for some pages (engage pages, docs). These errors should not result in a 500, but a more informative error message explaining that it's the Discourse API that is causing problems.

> Also, can we make it so fetch failures would show something else for that section on the page rather than render a full 500 Internal Server Error to the client?
https://github.com/canonical-web-and-design/ubuntu.com/issues/8687#issuecomment-723505687

**Comment by carkod** [comment]
Dup https://github.com/canonical/ubuntu.com/issues/8700
