### ISSUE TITLE
RFE: security tracker release selection

### ISSUE THREAD

**Issue by mason-redhat** [canonical/ubuntu.com#8846]
It's be useful if one could have a way to select releases of interest on 
the page and show only those release columns. Like, "just 18.04 and 20.04".
This isn't probably a big deal now, but as more releases hit ESM the page
could become awkward.

As it stands, it's not as straightforward as it could be to run down a 
column in the middle. Maybe having alternating light and dark backgrounds
per-column would help with this visually.

---
*Reported from: https://ubuntu.com/security/cve?q=

**Comment by britneywwc** [comment]
Hi, we have an on-going task to overhaul CVE pages and it addresses the issue of selecting multiple CVE statuses. Will be closing issue for now as it is implemented in the CVE overhaul project but feel free to reopen this if needed.
You can check out the demo here: https://ubuntu-com-13412.demos.haus/security/cves?q=
