### ISSUE TITLE
The priorities aren't defined anywhere

### ISSUE THREAD

**Issue by setharnold** [canonical/ubuntu.com#8935]
Hello, the previous view of the Ubuntu CVE Tracker had an explanatory page to describe the priorities we assign to CVEs https://people.canonical.com/~ubuntu-security/cve/priority.html

I haven't been able to find this on the new site yet; I'd possibly expect to see it linked from the priority on each individual cve, or a 'legend' link underneath them, etc.

Before we made that specific page, we'd direct people to https://git.launchpad.net/ubuntu-cve-tracker/tree/README#n229 which is much less pleasant for everybody.

The HTML of the old page is still available if it would be helpful.

---
*Reported from: https://ubuntu.com/security/cve*

**Comment by setharnold** [comment]
We've added a copy to https://people.canonical.com/~ubuntu-security/priority.html

**Comment by carkod** [comment]
Looks like there is now a new info hover text. Does that work? Feel free to reopen if it's still an issue

<img width="645" alt="Screenshot 2023-08-11 at 12 31 21" src="https://github.com/canonical/ubuntu.com/assets/14939793/99926df4-dcb0-4b8f-8026-c3d63c65335a">
