### ISSUE TITLE
ubuntu.com should handle a /_status/ endpoint

### ISSUE THREAD

**Issue by tcuthbert** [canonical/ubuntu.com#9027]
## Summary

ubuntu.com does not perform status checks which prevents upstream loadbalancers from effectively monitoring the readiness of a given instance of the application.

## Process

Our [wsgi](https://talisker.readthedocs.io/en/latest/endpoints.html) server creates a `/_status/check` endpoint. Without the application handling the request it just returns a `200` response. The ubuntu.com app has external dependencies to other services that can impact how long pages take to load if those dependencies are suffering from performance issues, this means the only time our loadbalancer checks will detect that a server is not ready to service more requests is when the wsgi service is down, unable to respond within the check interval due to load on the underlying platform, or if the wsgi server has exhausted available connections.

## Current and expected result

The application should bind to a `/_status/check` or `/_status/ping` and do a minimum of load the index page. It'd also be useful for the body content to return some kind of detail of the current health of the site, perhaps it could profile a sampling of response times to various endpoints and provide a health score for each?

**Comment by nottrobin** [comment]
Could you provide more detail on what problem you're trying to solve? Was there a specific issue that led you to raise this?

Yes, at the moment `/_status/check` checks the bare minimum - that the python application is running. It doesn't check that the homepage loads or that any other endpoint loads. This is very deliberate, as we use `/_status/check` for Kubernetes to check that the pods haven't crashed.

I'd be very happy to discuss other check endpoints. We could change `/_status/check` to performing a different function and use `/_status/ping` to check the basic health of the pod. However, I do need to understand exactly what you need from such an endpoint.

It sounds a bit like you want `/_status/check` to give you a whole-system-health report or something, which we could talk about. We have functionally static pages which shouldn't rely on any backends to load (and we're working on making the homepage functionally static following the Discourse-related outage), and we also have pages that necessarily rely on Discourse, or others that rely on other backends.

**Comment by tcuthbert** [comment]
> Could you provide more detail on what problem you're trying to solve? Was there a specific issue that led you to raise this?

The problem I'm trying to solve is for our ubuntu.com k8s application replicas to detect when a ubuntu.com application instance is able to respond within a reasonable time frame. Our blackbox monitoring regularly alerts us that the site is down due to response timeouts. Our blackbox monitoring is configured to timeout a response after 30s.

> Yes, at the moment `/_status/check` checks the bare minimum - that the python application is running. It doesn't check that the homepage loads or that any other endpoint loads. This is very deliberate, as we [use `/_status/check` for Kubernetes](https://github.com/canonical-web-and-design/konf/blob/master/templates/deployment.yaml#L77) to check that the pods haven't crashed. Currently, if we made this check more complex we'd risk bringing down the site as Kubernetes will restart pods when this endpoint fails, which, if some endpoints are failing because of some backend, is almost certainly not the right response.


As per the kubernetes [documentation](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/), the readiness probe is designed to check whether the site is able to serve traffic, not whether the service has crashed.

> It sounds a bit like you want /_status/check to give you a whole-system-health report or something, which we could talk about. We have functionally static pages which shouldn't rely on any backends to load (and we're working on making the homepage functionally static following the Discourse-related outage), and we also have pages that necessarily rely on Discourse, or others that rely on other backends.

I'm measuring performance here with the out of the box kubernetes ingress metrics:
```
nginx_ingress_controller_response_duration_seconds_bucket / nginx_ingress_controller_response_duration_seconds_count
```
The default ingress controller metrics give us a maximum 10s response time bucket. We sometimes see 20% of all responses taking +10s which doesn't allow us to properly trace exceptionally slow requests down. It'd be nice if the ubuntu app could expose summaries and histograms but with buckets that sample responses in the order of 1, 2, 3, 5, 8, 10, 15, 20, 25, and 30 seconds. It'd also really help to label the specific application views where slow responses are observed.

**Comment by nottrobin** [comment]
> As per the kubernetes documentation, the readiness probe is designed to check whether the site is able to serve traffic, not whether the service has crashed.

That's a good point. I guess maybe we were using Liveness and switched to Readiness for some reason? Yes it does sound like the liveness check should be `_status/ping`, and then the readiness probe should be `_status/check` which should check something more significant.

As I say though, "readiness" would mean different things for different pages on the site. I guess making it just check the homepage responds would be a good first step though.

**Comment by anthonydillon** [comment]
@nottrobin is this ready to be triaged now or is it too be added to the maintenance sprint?

**Comment by nottrobin** [comment]
Most of the work is captured in those other two issues. I guess this one could remain open, it'll be finally fixed by upgrading to the new version of flask base.

Triage wise, yeah this is medium I guess. I'd be very happy to add it to the sprint.

**Comment by nottrobin** [comment]
OK an update on this:

I don't think we want to start setting a liveness check, because I can't think of a scenario we've ever had where restarting the pod is going to help. In the past, pods auto restarting has only caused problem. I'd certainly want to have a better understanding about what situations a restart would fix before adding automatic restarts.

For the readiness check, the one we have (Talisker's default `/_status/check`) is probably a good default. The only remaining question for me might be whether ubuntu.com should have a special check that checks the homepage loads. However, I don't think we've had problems where the `/_status/check` passed but the homepage failed recently. Again, I'd like to know more about under what scenarios this happens so we can design this check properly.

I'm going to close this until we have an actual incident where this is relevant so we can consider the right solution with a real-world problem-case.
