### ISSUE TITLE
CVE status cells: Make the whole cell clickable

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical/ubuntu.com#9034]
On a CVE page, the help tip explaining the status and priority appear when you click the “ℹ️” icon that appears on hover.

![image](https://user-images.githubusercontent.com/19801137/104728663-258cdc80-572f-11eb-84cb-dc284836acd0.png)

It would be easier if the tip was invoked by clicking _anywhere_ in the cell, not just on the icon.

A complication is that when the cell contains a link (for example, a link to ubuntu.com/advantage), clicking the link should follow it as normal, instead of revealing the tip.

**Comment by petesfrench** [comment]
Closing as this seems to have been addressed by the CVE overhaul we recently went through. The icon now opens the explanation on hover. This decision would have been backed by UX.
