### ISSUE TITLE
Discourse banner erroring

### ISSUE THREAD

**Issue by rhys-the-davies** [canonical/ubuntu.com#9387]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

At discourse.ubuntu.com the secondary navigation banner is separated from the top and overlaps with the rest of the page cutting off the tops of 'category' 'topics and 'lastest'. I am using Chrome and am an admin on the discourse - in case these things make me a special case. 

## Process

Go to discourse.ubuntu.com and look at the secondary navigation bar that lists 'Discourse' on an orange background, categories, latest, New, Unread, and Top.

## Current and expected result

It looks broken. 

## Screenshot
![Screenshot from 2021-03-15 09-54-35](https://user-images.githubusercontent.com/56505487/111135361-79bc0d80-8574-11eb-8af3-e32eda4bfd9f.png)

## Browser details

[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.] ... It looks like mybrowser.fyi has been depreciated

**Comment by anthonydillon** [comment]
@rhys-the-davies I am unable to replicate this in both FF and Chrome. Are you using Chrome 89?

**Comment by rhys-the-davies** [comment]
I am, version 89.0.4389.82 to be exact. I don't have the same issue on FF. Maybe I've configured something weirdly in Chrome but I don't know how to check/reset

**Comment by anthonydillon** [comment]
You could try a private window or create a blank Chrome profile without any extensions and retry.

**Comment by rhys-the-davies** [comment]
Nope, neither worked, sorry. Any other suggestions?

**Comment by anthonydillon** [comment]
I think the best thing would be if we could jump on a call and we can check it out together. I'll put something in the calendar if that is ok?

**Comment by rhys-the-davies** [comment]
Sure good idea

**Comment by anthonydillon** [comment]
This has been resolved now.
