### ISSUE TITLE
Site width doesn't match the agreed width of 72 rem, used in most other canonical sites

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/ubuntu.com#9460]
## Summary
The max-width of fixed-width elements like `.row` is inconsistent with the standard width of 72 rem that we've agreed on a while ago:

## Process
Look up the `max-width` property on an element with class `row`

## Screenshot

Current vs expected:
![image](https://user-images.githubusercontent.com/2741678/112494014-94636300-8d7a-11eb-9119-079a57ecf9a2.png)

**Comment by SirSamTumless** [comment]
@lyubomir-popov  Please triage this accordingly.
