### ISSUE TITLE
usn text rendered funny

### ISSUE THREAD

**Issue by setharnold** [canonical/ubuntu.com#9518]
Hello, a bug number in a USN appears to be getting rendered as a heading.

---
*Reported from: https://ubuntu.com/security/notices/USN-2743-3*

**Comment by setharnold** [comment]
![USN-2743-3](https://user-images.githubusercontent.com/5447148/113919510-364f6a80-97d3-11eb-9ac9-83a002317a55.png)

**Comment by albertkol** [comment]
It's due to parsing the notice.details as markdown. So when it finds a `#` it formats text as a headline.

Needs some investigation to find out how to best approach this.
