### ISSUE TITLE
Google captcha causes website accessibility issues from within China

### ISSUE THREAD

**Issue by leoniscsem** [canonical/ubuntu.com#9753]
When trying to download whitepapers or other documents published on the websites, the Google captcha does not show due to internet access restrictions imposed by the Chinese governments. This might not be a critical bug for average users, but it certainly affects enterprise users, as using a VPN or proxy is uncomfortable.

Suggestion: Change to another captcha framework, for examaple hCaptcha works fine.

---
*Reported from: https://ubuntu.com/*

**Comment by nottrobin** [comment]
That's very interesting, and hcaptcha looks quite good.

I'm curious though - is there a specific reason why Google gets blocked and hcaptcha doesn't? Can we be confident that hcaptcha might not get similarly blocked in the future leading to exactly the same problem?

@anthonydillon shared an article a while ago about how it's actually pretty easy and makes a fair bit of sense to write your own bot busting checks. Which might be worth exploring if we want to avoid entirely the possibility of the great firewall breaking our forms.

**Comment by anthonydillon** [comment]
It looks like there is a [proposed replacement for hcaptcha](https://blog.cloudflare.com/introducing-cryptographic-attestation-of-personhood/) in the future but I am convinced our sites need this level of protection. 

I would like to explore some simplified solutions and cn.ubuntu.com would be a good place to test these.

**Comment by leoniscsem** [comment]
> I'm curious though - is there a specific reason why Google gets blocked and hcaptcha doesn't? Can we be confident that hcaptcha might not get similarly blocked in the future leading to exactly the same problem?

Everything that calls Google services or APIs is blocked here. I do not think that hCaptcha or similar services would be banned, as there are no services attached which cause political issues. It is not about reCaptcha per se, it is just about politcy decisions by the government here to block everything related to Google. hCaptcha is just one of several services that work fine here.

**Comment by anthonydillon** [comment]
Blocked on these changes to land: https://github.com/canonical-web-and-design/ubuntu.com/pull/9590

**Comment by carkod** [comment]
@nottrobin Does this still apply? We are not using captcha anymore
